// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addAlertNotification = `-- name: AddAlertNotification :exec
INSERT INTO alert_notifications (project_id, rule_id, channel_id)
VALUES ($1, $2, $3)
ON CONFLICT (rule_id, channel_id) DO NOTHING
`

type AddAlertNotificationParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	RuleID    uuid.UUID `json:"rule_id"`
	ChannelID uuid.UUID `json:"channel_id"`
}

func (q *Queries) AddAlertNotification(ctx context.Context, arg AddAlertNotificationParams) error {
	_, err := q.db.Exec(ctx, addAlertNotification, arg.ProjectID, arg.RuleID, arg.ChannelID)
	return err
}

const claimNotificationOutbox = `-- name: ClaimNotificationOutbox :many
WITH selected AS (
    SELECT id
    FROM notification_outbox
    WHERE status = 'pending'
      AND next_attempt_at <= now()
    ORDER BY next_attempt_at ASC, created_at ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE notification_outbox
SET status = 'sending',
    last_attempt_at = now()
FROM selected
WHERE notification_outbox.id = selected.id
RETURNING notification_outbox.id,
          notification_outbox.project_id,
          notification_outbox.incident_id,
          notification_outbox.rule_id,
          notification_outbox.channel_id,
          notification_outbox.channel_type,
          notification_outbox.event_type,
          notification_outbox.status,
          notification_outbox.payload,
          notification_outbox.attempt_count,
          notification_outbox.max_attempts,
          notification_outbox.next_attempt_at,
          notification_outbox.last_attempt_at,
          notification_outbox.delivered_at,
          notification_outbox.last_error_kind,
          notification_outbox.last_error_code,
          notification_outbox.last_error,
          notification_outbox.dedupe_key,
          notification_outbox.created_at,
          notification_outbox.updated_at
`

func (q *Queries) ClaimNotificationOutbox(ctx context.Context, limitCount int32) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, claimNotificationOutbox, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationOutbox
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IncidentID,
			&i.RuleID,
			&i.ChannelID,
			&i.ChannelType,
			&i.EventType,
			&i.Status,
			&i.Payload,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.DeliveredAt,
			&i.LastErrorKind,
			&i.LastErrorCode,
			&i.LastError,
			&i.DedupeKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAlertIncident = `-- name: CreateAlertIncident :one
INSERT INTO alert_incidents (
    project_id,
    rule_id,
    probe_id,
    check_id,
    check_type,
    status,
    severity,
    last_evaluation_state,
    opened_at,
    last_evaluated_at,
    last_triggered_at,
    last_value,
    last_summary,
    last_notification_sent_at,
    next_notification_eligible_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'open',
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12::jsonb,
    $13,
    $14
)
ON CONFLICT (rule_id, probe_id, check_id) WHERE status IN ('open', 'acknowledged') DO NOTHING
RETURNING id, project_id, rule_id, probe_id, check_id, check_type, status, severity, last_evaluation_state, opened_at, acknowledged_at, acknowledged_by_user_id, resolved_at, resolved_by_user_id, last_evaluated_at, last_triggered_at, last_value, last_summary, last_notification_sent_at, next_notification_eligible_at, suppressed_notification_count, created_at, updated_at
`

type CreateAlertIncidentParams struct {
	ProjectID                  uuid.UUID            `json:"project_id"`
	RuleID                     uuid.UUID            `json:"rule_id"`
	ProbeID                    uuid.UUID            `json:"probe_id"`
	CheckID                    uuid.UUID            `json:"check_id"`
	CheckType                  CheckType            `json:"check_type"`
	Severity                   AlertSeverity        `json:"severity"`
	LastEvaluationState        AlertEvaluationState `json:"last_evaluation_state"`
	OpenedAt                   time.Time            `json:"opened_at"`
	LastEvaluatedAt            time.Time            `json:"last_evaluated_at"`
	LastTriggeredAt            time.Time            `json:"last_triggered_at"`
	LastValue                  *float64             `json:"last_value"`
	LastSummary                []byte               `json:"last_summary"`
	LastNotificationSentAt     *time.Time           `json:"last_notification_sent_at"`
	NextNotificationEligibleAt *time.Time           `json:"next_notification_eligible_at"`
}

func (q *Queries) CreateAlertIncident(ctx context.Context, arg CreateAlertIncidentParams) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, createAlertIncident,
		arg.ProjectID,
		arg.RuleID,
		arg.ProbeID,
		arg.CheckID,
		arg.CheckType,
		arg.Severity,
		arg.LastEvaluationState,
		arg.OpenedAt,
		arg.LastEvaluatedAt,
		arg.LastTriggeredAt,
		arg.LastValue,
		arg.LastSummary,
		arg.LastNotificationSentAt,
		arg.NextNotificationEligibleAt,
	)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuleID,
		&i.ProbeID,
		&i.CheckID,
		&i.CheckType,
		&i.Status,
		&i.Severity,
		&i.LastEvaluationState,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.LastValue,
		&i.LastSummary,
		&i.LastNotificationSentAt,
		&i.NextNotificationEligibleAt,
		&i.SuppressedNotificationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAlertRule = `-- name: CreateAlertRule :one
INSERT INTO alert_rules (
    project_id,
    name,
    description,
    status,
    severity,
    check_type,
    probe_id,
    check_id,
    probe_selector,
    condition,
    condition_version,
    cooldown_seconds,
    created_by_user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9::jsonb,
    $10::jsonb,
    $11,
    $12,
    $13
)
RETURNING id, project_id, name, description, status, severity, check_type, probe_id, check_id, probe_selector, condition, condition_version, cooldown_seconds, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateAlertRuleParams struct {
	ProjectID        uuid.UUID       `json:"project_id"`
	Name             string          `json:"name"`
	Description      *string         `json:"description"`
	Status           AlertRuleStatus `json:"status"`
	Severity         AlertSeverity   `json:"severity"`
	CheckType        CheckType       `json:"check_type"`
	ProbeID          *uuid.UUID      `json:"probe_id"`
	CheckID          *uuid.UUID      `json:"check_id"`
	ProbeSelector    []byte          `json:"probe_selector"`
	Condition        []byte          `json:"condition"`
	ConditionVersion string          `json:"condition_version"`
	CooldownSeconds  int32           `json:"cooldown_seconds"`
	CreatedByUserID  uuid.UUID       `json:"created_by_user_id"`
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, createAlertRule,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Severity,
		arg.CheckType,
		arg.ProbeID,
		arg.CheckID,
		arg.ProbeSelector,
		arg.Condition,
		arg.ConditionVersion,
		arg.CooldownSeconds,
		arg.CreatedByUserID,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.CheckType,
		&i.ProbeID,
		&i.CheckID,
		&i.ProbeSelector,
		&i.Condition,
		&i.ConditionVersion,
		&i.CooldownSeconds,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (
    project_id,
    name,
    type,
    enabled,
    config,
    created_by_user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::jsonb,
    $6
)
RETURNING id, project_id, name, type, enabled, config, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateNotificationChannelParams struct {
	ProjectID       uuid.UUID               `json:"project_id"`
	Name            string                  `json:"name"`
	ChannelType     NotificationChannelType `json:"channel_type"`
	Enabled         bool                    `json:"enabled"`
	Config          []byte                  `json:"config"`
	CreatedByUserID uuid.UUID               `json:"created_by_user_id"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.ProjectID,
		arg.Name,
		arg.ChannelType,
		arg.Enabled,
		arg.Config,
		arg.CreatedByUserID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const enqueueNotificationOutbox = `-- name: EnqueueNotificationOutbox :one
INSERT INTO notification_outbox (
    project_id,
    incident_id,
    rule_id,
    channel_id,
    channel_type,
    event_type,
    payload,
    dedupe_key
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::jsonb,
    $8
)
ON CONFLICT (dedupe_key) DO NOTHING
RETURNING id
`

type EnqueueNotificationOutboxParams struct {
	ProjectID   uuid.UUID               `json:"project_id"`
	IncidentID  uuid.UUID               `json:"incident_id"`
	RuleID      uuid.UUID               `json:"rule_id"`
	ChannelID   uuid.UUID               `json:"channel_id"`
	ChannelType NotificationChannelType `json:"channel_type"`
	EventType   string                  `json:"event_type"`
	Payload     []byte                  `json:"payload"`
	DedupeKey   string                  `json:"dedupe_key"`
}

func (q *Queries) EnqueueNotificationOutbox(ctx context.Context, arg EnqueueNotificationOutboxParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueNotificationOutbox,
		arg.ProjectID,
		arg.IncidentID,
		arg.RuleID,
		arg.ChannelID,
		arg.ChannelType,
		arg.EventType,
		arg.Payload,
		arg.DedupeKey,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveAlertIncident = `-- name: GetActiveAlertIncident :one
SELECT id,
       project_id,
       rule_id,
       probe_id,
       check_id,
       check_type,
       status,
       severity,
       last_evaluation_state,
       opened_at,
       acknowledged_at,
       acknowledged_by_user_id,
       resolved_at,
       resolved_by_user_id,
       last_evaluated_at,
       last_triggered_at,
       last_value,
       last_summary,
       last_notification_sent_at,
       next_notification_eligible_at,
       suppressed_notification_count,
       created_at,
       updated_at
FROM alert_incidents
WHERE rule_id = $1
  AND probe_id = $2
  AND check_id = $3
  AND status IN ('open', 'acknowledged')
LIMIT 1
`

type GetActiveAlertIncidentParams struct {
	RuleID  uuid.UUID `json:"rule_id"`
	ProbeID uuid.UUID `json:"probe_id"`
	CheckID uuid.UUID `json:"check_id"`
}

func (q *Queries) GetActiveAlertIncident(ctx context.Context, arg GetActiveAlertIncidentParams) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, getActiveAlertIncident, arg.RuleID, arg.ProbeID, arg.CheckID)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuleID,
		&i.ProbeID,
		&i.CheckID,
		&i.CheckType,
		&i.Status,
		&i.Severity,
		&i.LastEvaluationState,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.LastValue,
		&i.LastSummary,
		&i.LastNotificationSentAt,
		&i.NextNotificationEligibleAt,
		&i.SuppressedNotificationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertIncident = `-- name: GetAlertIncident :one
SELECT alert_incidents.id,
       alert_incidents.project_id,
       alert_incidents.rule_id,
       alert_incidents.probe_id,
       alert_incidents.check_id,
       alert_incidents.check_type,
       alert_incidents.status,
       alert_incidents.severity,
       alert_incidents.last_evaluation_state,
       alert_incidents.opened_at,
       alert_incidents.acknowledged_at,
       alert_incidents.acknowledged_by_user_id,
       alert_incidents.resolved_at,
       alert_incidents.resolved_by_user_id,
       alert_incidents.last_evaluated_at,
       alert_incidents.last_triggered_at,
       alert_incidents.last_value,
       alert_incidents.last_summary,
       alert_incidents.last_notification_sent_at,
       alert_incidents.next_notification_eligible_at,
       alert_incidents.suppressed_notification_count,
       alert_incidents.created_at,
       alert_incidents.updated_at,
       probes.name AS probe_name,
       checks.name AS check_name,
       checks.check_type AS check_summary_type,
       checks.target AS check_target
FROM alert_incidents
JOIN probes
  ON probes.project_id = alert_incidents.project_id
 AND probes.id = alert_incidents.probe_id
JOIN checks
  ON checks.project_id = alert_incidents.project_id
 AND checks.id = alert_incidents.check_id
WHERE alert_incidents.project_id = $1
  AND alert_incidents.id = $2
`

type GetAlertIncidentParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

type GetAlertIncidentRow struct {
	ID                          uuid.UUID            `json:"id"`
	ProjectID                   uuid.UUID            `json:"project_id"`
	RuleID                      uuid.UUID            `json:"rule_id"`
	ProbeID                     uuid.UUID            `json:"probe_id"`
	CheckID                     uuid.UUID            `json:"check_id"`
	CheckType                   CheckType            `json:"check_type"`
	Status                      AlertIncidentStatus  `json:"status"`
	Severity                    AlertSeverity        `json:"severity"`
	LastEvaluationState         AlertEvaluationState `json:"last_evaluation_state"`
	OpenedAt                    time.Time            `json:"opened_at"`
	AcknowledgedAt              *time.Time           `json:"acknowledged_at"`
	AcknowledgedByUserID        *uuid.UUID           `json:"acknowledged_by_user_id"`
	ResolvedAt                  *time.Time           `json:"resolved_at"`
	ResolvedByUserID            *uuid.UUID           `json:"resolved_by_user_id"`
	LastEvaluatedAt             time.Time            `json:"last_evaluated_at"`
	LastTriggeredAt             time.Time            `json:"last_triggered_at"`
	LastValue                   *float64             `json:"last_value"`
	LastSummary                 []byte               `json:"last_summary"`
	LastNotificationSentAt      *time.Time           `json:"last_notification_sent_at"`
	NextNotificationEligibleAt  *time.Time           `json:"next_notification_eligible_at"`
	SuppressedNotificationCount int32                `json:"suppressed_notification_count"`
	CreatedAt                   time.Time            `json:"created_at"`
	UpdatedAt                   time.Time            `json:"updated_at"`
	ProbeName                   string               `json:"probe_name"`
	CheckName                   string               `json:"check_name"`
	CheckSummaryType            CheckType            `json:"check_summary_type"`
	CheckTarget                 string               `json:"check_target"`
}

func (q *Queries) GetAlertIncident(ctx context.Context, arg GetAlertIncidentParams) (GetAlertIncidentRow, error) {
	row := q.db.QueryRow(ctx, getAlertIncident, arg.ProjectID, arg.ID)
	var i GetAlertIncidentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuleID,
		&i.ProbeID,
		&i.CheckID,
		&i.CheckType,
		&i.Status,
		&i.Severity,
		&i.LastEvaluationState,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.LastValue,
		&i.LastSummary,
		&i.LastNotificationSentAt,
		&i.NextNotificationEligibleAt,
		&i.SuppressedNotificationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProbeName,
		&i.CheckName,
		&i.CheckSummaryType,
		&i.CheckTarget,
	)
	return i, err
}

const getAlertRule = `-- name: GetAlertRule :one
SELECT alert_rules.id,
       alert_rules.project_id,
       alert_rules.name,
       alert_rules.description,
       alert_rules.status,
       alert_rules.severity,
       alert_rules.check_type,
       alert_rules.probe_id,
       alert_rules.check_id,
       alert_rules.probe_selector,
       alert_rules.condition,
       alert_rules.condition_version,
       alert_rules.cooldown_seconds,
       alert_rules.created_by_user_id,
       alert_rules.created_at,
       alert_rules.updated_at,
       alert_rules.deleted_at
FROM alert_rules
WHERE alert_rules.project_id = $1
  AND alert_rules.id = $2
  AND alert_rules.deleted_at IS NULL
`

type GetAlertRuleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetAlertRule(ctx context.Context, arg GetAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, getAlertRule, arg.ProjectID, arg.ID)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.CheckType,
		&i.ProbeID,
		&i.CheckID,
		&i.ProbeSelector,
		&i.Condition,
		&i.ConditionVersion,
		&i.CooldownSeconds,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id,
       project_id,
       name,
       type,
       enabled,
       config,
       created_by_user_id,
       created_at,
       updated_at,
       deleted_at
FROM notification_channels
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetNotificationChannelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ProjectID, arg.ID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPingAlertMetricSummary = `-- name: GetPingAlertMetricSummary :one
SELECT count(*) FILTER (
           WHERE CASE
               WHEN $1::text IN ('ping.average_rtt_ms') THEN rtt_avg_ms IS NOT NULL
               WHEN $1::text IN ('ping.max_rtt_ms') THEN rtt_max_ms IS NOT NULL
               ELSE true
           END
       )::bigint AS samples,
       coalesce(CASE $1::text
           WHEN 'ping.loss_percent' THEN avg(loss_percent)::double precision
           WHEN 'ping.success_rate' THEN (100.0 * count(*) FILTER (WHERE status = 'successful') / NULLIF(count(*), 0))::double precision
           WHEN 'ping.average_rtt_ms' THEN avg(rtt_avg_ms)::double precision
           WHEN 'ping.max_rtt_ms' THEN max(rtt_max_ms)::double precision
           ELSE NULL::double precision
       END, 0)::double precision AS value
FROM ping_results
WHERE probe_id = $2
  AND check_id = $3
  AND started_at >= $4
  AND started_at < $5
`

type GetPingAlertMetricSummaryParams struct {
	Metric         string    `json:"metric"`
	ProbeStorageID int64     `json:"probe_storage_id"`
	CheckStorageID int64     `json:"check_storage_id"`
	StartedAtFrom  time.Time `json:"started_at_from"`
	StartedAtTo    time.Time `json:"started_at_to"`
}

type GetPingAlertMetricSummaryRow struct {
	Samples int64   `json:"samples"`
	Value   float64 `json:"value"`
}

func (q *Queries) GetPingAlertMetricSummary(ctx context.Context, arg GetPingAlertMetricSummaryParams) (GetPingAlertMetricSummaryRow, error) {
	row := q.db.QueryRow(ctx, getPingAlertMetricSummary,
		arg.Metric,
		arg.ProbeStorageID,
		arg.CheckStorageID,
		arg.StartedAtFrom,
		arg.StartedAtTo,
	)
	var i GetPingAlertMetricSummaryRow
	err := row.Scan(&i.Samples, &i.Value)
	return i, err
}

const getRecentResolvedAlertIncident = `-- name: GetRecentResolvedAlertIncident :one
SELECT id,
       project_id,
       rule_id,
       probe_id,
       check_id,
       check_type,
       status,
       severity,
       last_evaluation_state,
       opened_at,
       acknowledged_at,
       acknowledged_by_user_id,
       resolved_at,
       resolved_by_user_id,
       last_evaluated_at,
       last_triggered_at,
       last_value,
       last_summary,
       last_notification_sent_at,
       next_notification_eligible_at,
       suppressed_notification_count,
       created_at,
       updated_at
FROM alert_incidents
WHERE rule_id = $1
  AND probe_id = $2
  AND check_id = $3
  AND status = 'resolved'
  AND resolved_at >= $4
ORDER BY resolved_at DESC
LIMIT 1
`

type GetRecentResolvedAlertIncidentParams struct {
	RuleID        uuid.UUID  `json:"rule_id"`
	ProbeID       uuid.UUID  `json:"probe_id"`
	CheckID       uuid.UUID  `json:"check_id"`
	ResolvedAfter *time.Time `json:"resolved_after"`
}

func (q *Queries) GetRecentResolvedAlertIncident(ctx context.Context, arg GetRecentResolvedAlertIncidentParams) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, getRecentResolvedAlertIncident,
		arg.RuleID,
		arg.ProbeID,
		arg.CheckID,
		arg.ResolvedAfter,
	)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuleID,
		&i.ProbeID,
		&i.CheckID,
		&i.CheckType,
		&i.Status,
		&i.Severity,
		&i.LastEvaluationState,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.LastValue,
		&i.LastSummary,
		&i.LastNotificationSentAt,
		&i.NextNotificationEligibleAt,
		&i.SuppressedNotificationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTCPAlertMetricSummary = `-- name: GetTCPAlertMetricSummary :one
SELECT count(*) FILTER (
           WHERE CASE
               WHEN $1::text IN ('tcp.average_connect_ms', 'tcp.max_connect_ms') THEN connect_duration_ms IS NOT NULL
               ELSE true
           END
       )::bigint AS samples,
       coalesce(CASE $1::text
           WHEN 'tcp.failure_percent' THEN (100.0 * count(*) FILTER (WHERE status IN ('timeout', 'error')) / NULLIF(count(*), 0))::double precision
           WHEN 'tcp.success_rate' THEN (100.0 * count(*) FILTER (WHERE status = 'successful') / NULLIF(count(*), 0))::double precision
           WHEN 'tcp.average_connect_ms' THEN avg(connect_duration_ms)::double precision
           WHEN 'tcp.max_connect_ms' THEN max(connect_duration_ms)::double precision
           ELSE NULL::double precision
       END, 0)::double precision AS value
FROM tcp_results
WHERE probe_id = $2
  AND check_id = $3
  AND started_at >= $4
  AND started_at < $5
`

type GetTCPAlertMetricSummaryParams struct {
	Metric         string    `json:"metric"`
	ProbeStorageID int64     `json:"probe_storage_id"`
	CheckStorageID int64     `json:"check_storage_id"`
	StartedAtFrom  time.Time `json:"started_at_from"`
	StartedAtTo    time.Time `json:"started_at_to"`
}

type GetTCPAlertMetricSummaryRow struct {
	Samples int64   `json:"samples"`
	Value   float64 `json:"value"`
}

func (q *Queries) GetTCPAlertMetricSummary(ctx context.Context, arg GetTCPAlertMetricSummaryParams) (GetTCPAlertMetricSummaryRow, error) {
	row := q.db.QueryRow(ctx, getTCPAlertMetricSummary,
		arg.Metric,
		arg.ProbeStorageID,
		arg.CheckStorageID,
		arg.StartedAtFrom,
		arg.StartedAtTo,
	)
	var i GetTCPAlertMetricSummaryRow
	err := row.Scan(&i.Samples, &i.Value)
	return i, err
}

const incrementAlertIncidentSuppressedNotifications = `-- name: IncrementAlertIncidentSuppressedNotifications :exec
UPDATE alert_incidents
SET suppressed_notification_count = suppressed_notification_count + 1
WHERE id = $1
`

func (q *Queries) IncrementAlertIncidentSuppressedNotifications(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementAlertIncidentSuppressedNotifications, id)
	return err
}

const listAlertIncidents = `-- name: ListAlertIncidents :many
SELECT alert_incidents.id,
       alert_incidents.project_id,
       alert_incidents.rule_id,
       alert_incidents.probe_id,
       alert_incidents.check_id,
       alert_incidents.check_type,
       alert_incidents.status,
       alert_incidents.severity,
       alert_incidents.last_evaluation_state,
       alert_incidents.opened_at,
       alert_incidents.acknowledged_at,
       alert_incidents.acknowledged_by_user_id,
       alert_incidents.resolved_at,
       alert_incidents.resolved_by_user_id,
       alert_incidents.last_evaluated_at,
       alert_incidents.last_triggered_at,
       alert_incidents.last_value,
       alert_incidents.last_summary,
       alert_incidents.last_notification_sent_at,
       alert_incidents.next_notification_eligible_at,
       alert_incidents.suppressed_notification_count,
       alert_incidents.created_at,
       alert_incidents.updated_at,
       probes.name AS probe_name,
       checks.name AS check_name,
       checks.check_type AS check_summary_type,
       checks.target AS check_target
FROM alert_incidents
JOIN probes
  ON probes.project_id = alert_incidents.project_id
 AND probes.id = alert_incidents.probe_id
JOIN checks
  ON checks.project_id = alert_incidents.project_id
 AND checks.id = alert_incidents.check_id
WHERE alert_incidents.project_id = $1
  AND (
      $2::alert_incident_status IS NULL
      OR alert_incidents.status = $2::alert_incident_status
  )
  AND (
      $3::uuid IS NULL
      OR alert_incidents.rule_id = $3::uuid
  )
  AND (
      $4::uuid IS NULL
      OR alert_incidents.probe_id = $4::uuid
  )
  AND (
      $5::uuid IS NULL
      OR alert_incidents.check_id = $5::uuid
  )
ORDER BY alert_incidents.opened_at DESC, alert_incidents.id DESC
LIMIT $6
`

type ListAlertIncidentsParams struct {
	ProjectID  uuid.UUID            `json:"project_id"`
	Status     *AlertIncidentStatus `json:"status"`
	RuleID     *uuid.UUID           `json:"rule_id"`
	ProbeID    *uuid.UUID           `json:"probe_id"`
	CheckID    *uuid.UUID           `json:"check_id"`
	LimitCount int32                `json:"limit_count"`
}

type ListAlertIncidentsRow struct {
	ID                          uuid.UUID            `json:"id"`
	ProjectID                   uuid.UUID            `json:"project_id"`
	RuleID                      uuid.UUID            `json:"rule_id"`
	ProbeID                     uuid.UUID            `json:"probe_id"`
	CheckID                     uuid.UUID            `json:"check_id"`
	CheckType                   CheckType            `json:"check_type"`
	Status                      AlertIncidentStatus  `json:"status"`
	Severity                    AlertSeverity        `json:"severity"`
	LastEvaluationState         AlertEvaluationState `json:"last_evaluation_state"`
	OpenedAt                    time.Time            `json:"opened_at"`
	AcknowledgedAt              *time.Time           `json:"acknowledged_at"`
	AcknowledgedByUserID        *uuid.UUID           `json:"acknowledged_by_user_id"`
	ResolvedAt                  *time.Time           `json:"resolved_at"`
	ResolvedByUserID            *uuid.UUID           `json:"resolved_by_user_id"`
	LastEvaluatedAt             time.Time            `json:"last_evaluated_at"`
	LastTriggeredAt             time.Time            `json:"last_triggered_at"`
	LastValue                   *float64             `json:"last_value"`
	LastSummary                 []byte               `json:"last_summary"`
	LastNotificationSentAt      *time.Time           `json:"last_notification_sent_at"`
	NextNotificationEligibleAt  *time.Time           `json:"next_notification_eligible_at"`
	SuppressedNotificationCount int32                `json:"suppressed_notification_count"`
	CreatedAt                   time.Time            `json:"created_at"`
	UpdatedAt                   time.Time            `json:"updated_at"`
	ProbeName                   string               `json:"probe_name"`
	CheckName                   string               `json:"check_name"`
	CheckSummaryType            CheckType            `json:"check_summary_type"`
	CheckTarget                 string               `json:"check_target"`
}

func (q *Queries) ListAlertIncidents(ctx context.Context, arg ListAlertIncidentsParams) ([]ListAlertIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listAlertIncidents,
		arg.ProjectID,
		arg.Status,
		arg.RuleID,
		arg.ProbeID,
		arg.CheckID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertIncidentsRow
	for rows.Next() {
		var i ListAlertIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RuleID,
			&i.ProbeID,
			&i.CheckID,
			&i.CheckType,
			&i.Status,
			&i.Severity,
			&i.LastEvaluationState,
			&i.OpenedAt,
			&i.AcknowledgedAt,
			&i.AcknowledgedByUserID,
			&i.ResolvedAt,
			&i.ResolvedByUserID,
			&i.LastEvaluatedAt,
			&i.LastTriggeredAt,
			&i.LastValue,
			&i.LastSummary,
			&i.LastNotificationSentAt,
			&i.NextNotificationEligibleAt,
			&i.SuppressedNotificationCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProbeName,
			&i.CheckName,
			&i.CheckSummaryType,
			&i.CheckTarget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertNotificationChannelIDs = `-- name: ListAlertNotificationChannelIDs :many
SELECT channel_id
FROM alert_notifications
WHERE project_id = $1
  AND rule_id = ANY($2::uuid[])
ORDER BY created_at ASC, channel_id ASC
`

type ListAlertNotificationChannelIDsParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	RuleIds   []uuid.UUID `json:"rule_ids"`
}

func (q *Queries) ListAlertNotificationChannelIDs(ctx context.Context, arg ListAlertNotificationChannelIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAlertNotificationChannelIDs, arg.ProjectID, arg.RuleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var channel_id uuid.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertRules = `-- name: ListAlertRules :many
SELECT alert_rules.id,
       alert_rules.project_id,
       alert_rules.name,
       alert_rules.description,
       alert_rules.status,
       alert_rules.severity,
       alert_rules.check_type,
       alert_rules.probe_id,
       alert_rules.check_id,
       alert_rules.probe_selector,
       alert_rules.condition,
       alert_rules.condition_version,
       alert_rules.cooldown_seconds,
       alert_rules.created_by_user_id,
       alert_rules.created_at,
       alert_rules.updated_at,
       alert_rules.deleted_at
FROM alert_rules
WHERE alert_rules.project_id = $1
  AND alert_rules.deleted_at IS NULL
  AND (
      $2::alert_rule_status IS NULL
      OR alert_rules.status = $2::alert_rule_status
  )
  AND (
      $3::check_type IS NULL
      OR alert_rules.check_type = $3::check_type
  )
ORDER BY alert_rules.created_at DESC, alert_rules.id DESC
`

type ListAlertRulesParams struct {
	ProjectID uuid.UUID        `json:"project_id"`
	Status    *AlertRuleStatus `json:"status"`
	CheckType *CheckType       `json:"check_type"`
}

func (q *Queries) ListAlertRules(ctx context.Context, arg ListAlertRulesParams) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRules, arg.ProjectID, arg.Status, arg.CheckType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Severity,
			&i.CheckType,
			&i.ProbeID,
			&i.CheckID,
			&i.ProbeSelector,
			&i.Condition,
			&i.ConditionVersion,
			&i.CooldownSeconds,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAlertRulesForAssignment = `-- name: ListEnabledAlertRulesForAssignment :many
SELECT alert_rules.id,
       alert_rules.project_id,
       alert_rules.name,
       alert_rules.description,
       alert_rules.status,
       alert_rules.severity,
       alert_rules.check_type,
       alert_rules.probe_id,
       alert_rules.check_id,
       alert_rules.probe_selector,
       alert_rules.condition,
       alert_rules.condition_version,
       alert_rules.cooldown_seconds,
       alert_rules.created_by_user_id,
       alert_rules.created_at,
       alert_rules.updated_at,
       alert_rules.deleted_at
FROM alert_rules
WHERE alert_rules.project_id = $1
  AND alert_rules.check_type = $2
  AND alert_rules.status = 'enabled'
  AND alert_rules.deleted_at IS NULL
  AND (alert_rules.probe_id IS NULL OR alert_rules.probe_id = $3)
  AND (alert_rules.check_id IS NULL OR alert_rules.check_id = $4)
ORDER BY alert_rules.created_at ASC, alert_rules.id ASC
`

type ListEnabledAlertRulesForAssignmentParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	CheckType CheckType  `json:"check_type"`
	ProbeID   *uuid.UUID `json:"probe_id"`
	CheckID   *uuid.UUID `json:"check_id"`
}

func (q *Queries) ListEnabledAlertRulesForAssignment(ctx context.Context, arg ListEnabledAlertRulesForAssignmentParams) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listEnabledAlertRulesForAssignment,
		arg.ProjectID,
		arg.CheckType,
		arg.ProbeID,
		arg.CheckID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertRule
	for rows.Next() {
		var i AlertRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Severity,
			&i.CheckType,
			&i.ProbeID,
			&i.CheckID,
			&i.ProbeSelector,
			&i.Condition,
			&i.ConditionVersion,
			&i.CooldownSeconds,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChannelsForRule = `-- name: ListEnabledChannelsForRule :many
SELECT notification_channels.id,
       notification_channels.project_id,
       notification_channels.name,
       notification_channels.type,
       notification_channels.enabled,
       notification_channels.config,
       notification_channels.created_by_user_id,
       notification_channels.created_at,
       notification_channels.updated_at,
       notification_channels.deleted_at
FROM alert_notifications
JOIN notification_channels
    ON notification_channels.project_id = alert_notifications.project_id
    AND notification_channels.id = alert_notifications.channel_id
WHERE alert_notifications.project_id = $1
  AND alert_notifications.rule_id = $2
  AND notification_channels.enabled = true
  AND notification_channels.deleted_at IS NULL
ORDER BY alert_notifications.created_at ASC, notification_channels.id ASC
`

type ListEnabledChannelsForRuleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	RuleID    uuid.UUID `json:"rule_id"`
}

func (q *Queries) ListEnabledChannelsForRule(ctx context.Context, arg ListEnabledChannelsForRuleParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledChannelsForRule, arg.ProjectID, arg.RuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Config,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id,
       project_id,
       name,
       type,
       enabled,
       config,
       created_by_user_id,
       created_at,
       updated_at,
       deleted_at
FROM notification_channels
WHERE project_id = $1
  AND deleted_at IS NULL
  AND (
      $2::notification_channel_type IS NULL
      OR type = $2::notification_channel_type
  )
ORDER BY created_at DESC, id DESC
`

type ListNotificationChannelsParams struct {
	ProjectID   uuid.UUID                `json:"project_id"`
	ChannelType *NotificationChannelType `json:"channel_type"`
}

func (q *Queries) ListNotificationChannels(ctx context.Context, arg ListNotificationChannelsParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, arg.ProjectID, arg.ChannelType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.Config,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationOutboxDelivered = `-- name: MarkNotificationOutboxDelivered :exec
UPDATE notification_outbox
SET status = 'delivered',
    delivered_at = $1,
    last_error_kind = NULL,
    last_error_code = NULL,
    last_error = NULL
WHERE id = $2
`

type MarkNotificationOutboxDeliveredParams struct {
	DeliveredAt *time.Time `json:"delivered_at"`
	ID          uuid.UUID  `json:"id"`
}

func (q *Queries) MarkNotificationOutboxDelivered(ctx context.Context, arg MarkNotificationOutboxDeliveredParams) error {
	_, err := q.db.Exec(ctx, markNotificationOutboxDelivered, arg.DeliveredAt, arg.ID)
	return err
}

const markNotificationOutboxDiscarded = `-- name: MarkNotificationOutboxDiscarded :exec
UPDATE notification_outbox
SET status = 'discarded',
    attempt_count = attempt_count + 1,
    last_error_kind = $1,
    last_error_code = $2,
    last_error = $3
WHERE id = $4
`

type MarkNotificationOutboxDiscardedParams struct {
	LastErrorKind *string   `json:"last_error_kind"`
	LastErrorCode *string   `json:"last_error_code"`
	LastError     *string   `json:"last_error"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) MarkNotificationOutboxDiscarded(ctx context.Context, arg MarkNotificationOutboxDiscardedParams) error {
	_, err := q.db.Exec(ctx, markNotificationOutboxDiscarded,
		arg.LastErrorKind,
		arg.LastErrorCode,
		arg.LastError,
		arg.ID,
	)
	return err
}

const markNotificationOutboxFailed = `-- name: MarkNotificationOutboxFailed :exec
UPDATE notification_outbox
SET status = 'failed',
    attempt_count = attempt_count + 1,
    last_error_kind = $1,
    last_error_code = $2,
    last_error = $3
WHERE id = $4
`

type MarkNotificationOutboxFailedParams struct {
	LastErrorKind *string   `json:"last_error_kind"`
	LastErrorCode *string   `json:"last_error_code"`
	LastError     *string   `json:"last_error"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) MarkNotificationOutboxFailed(ctx context.Context, arg MarkNotificationOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationOutboxFailed,
		arg.LastErrorKind,
		arg.LastErrorCode,
		arg.LastError,
		arg.ID,
	)
	return err
}

const markNotificationOutboxRetry = `-- name: MarkNotificationOutboxRetry :exec
UPDATE notification_outbox
SET status = 'pending',
    attempt_count = attempt_count + 1,
    next_attempt_at = $1,
    last_error_kind = $2,
    last_error_code = $3,
    last_error = $4
WHERE id = $5
`

type MarkNotificationOutboxRetryParams struct {
	NextAttemptAt time.Time `json:"next_attempt_at"`
	LastErrorKind *string   `json:"last_error_kind"`
	LastErrorCode *string   `json:"last_error_code"`
	LastError     *string   `json:"last_error"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) MarkNotificationOutboxRetry(ctx context.Context, arg MarkNotificationOutboxRetryParams) error {
	_, err := q.db.Exec(ctx, markNotificationOutboxRetry,
		arg.NextAttemptAt,
		arg.LastErrorKind,
		arg.LastErrorCode,
		arg.LastError,
		arg.ID,
	)
	return err
}

const recoverStaleNotificationOutbox = `-- name: RecoverStaleNotificationOutbox :execrows
UPDATE notification_outbox
SET status = 'pending',
    next_attempt_at = now()
WHERE status = 'sending'
  AND last_attempt_at < $1
`

func (q *Queries) RecoverStaleNotificationOutbox(ctx context.Context, staleBefore *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, recoverStaleNotificationOutbox, staleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceAlertNotifications = `-- name: ReplaceAlertNotifications :exec
DELETE FROM alert_notifications
WHERE project_id = $1
  AND rule_id = $2
`

type ReplaceAlertNotificationsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	RuleID    uuid.UUID `json:"rule_id"`
}

func (q *Queries) ReplaceAlertNotifications(ctx context.Context, arg ReplaceAlertNotificationsParams) error {
	_, err := q.db.Exec(ctx, replaceAlertNotifications, arg.ProjectID, arg.RuleID)
	return err
}

const resolveActiveAlertIncident = `-- name: ResolveActiveAlertIncident :one
UPDATE alert_incidents
SET status = 'resolved',
    last_evaluation_state = 'clear',
    resolved_at = $1,
    resolved_by_user_id = NULL,
    last_evaluated_at = $2,
    last_summary = $3::jsonb
WHERE id = $4
  AND status IN ('open', 'acknowledged')
RETURNING id, project_id, rule_id, probe_id, check_id, check_type, status, severity, last_evaluation_state, opened_at, acknowledged_at, acknowledged_by_user_id, resolved_at, resolved_by_user_id, last_evaluated_at, last_triggered_at, last_value, last_summary, last_notification_sent_at, next_notification_eligible_at, suppressed_notification_count, created_at, updated_at
`

type ResolveActiveAlertIncidentParams struct {
	ResolvedAt      *time.Time `json:"resolved_at"`
	LastEvaluatedAt time.Time  `json:"last_evaluated_at"`
	LastSummary     []byte     `json:"last_summary"`
	ID              uuid.UUID  `json:"id"`
}

func (q *Queries) ResolveActiveAlertIncident(ctx context.Context, arg ResolveActiveAlertIncidentParams) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, resolveActiveAlertIncident,
		arg.ResolvedAt,
		arg.LastEvaluatedAt,
		arg.LastSummary,
		arg.ID,
	)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuleID,
		&i.ProbeID,
		&i.CheckID,
		&i.CheckType,
		&i.Status,
		&i.Severity,
		&i.LastEvaluationState,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.LastValue,
		&i.LastSummary,
		&i.LastNotificationSentAt,
		&i.NextNotificationEligibleAt,
		&i.SuppressedNotificationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteAlertRule = `-- name: SoftDeleteAlertRule :execrows
UPDATE alert_rules
SET deleted_at = now(),
    status = 'disabled'
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type SoftDeleteAlertRuleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteAlertRule(ctx context.Context, arg SoftDeleteAlertRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAlertRule, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteNotificationChannel = `-- name: SoftDeleteNotificationChannel :execrows
UPDATE notification_channels
SET deleted_at = now(),
    enabled = false
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type SoftDeleteNotificationChannelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteNotificationChannel(ctx context.Context, arg SoftDeleteNotificationChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteNotificationChannel, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateActiveAlertIncidentInsufficient = `-- name: UpdateActiveAlertIncidentInsufficient :one
UPDATE alert_incidents
SET last_evaluation_state = $1,
    last_evaluated_at = $2,
    last_summary = $3::jsonb
WHERE id = $4
  AND status IN ('open', 'acknowledged')
RETURNING id, project_id, rule_id, probe_id, check_id, check_type, status, severity, last_evaluation_state, opened_at, acknowledged_at, acknowledged_by_user_id, resolved_at, resolved_by_user_id, last_evaluated_at, last_triggered_at, last_value, last_summary, last_notification_sent_at, next_notification_eligible_at, suppressed_notification_count, created_at, updated_at
`

type UpdateActiveAlertIncidentInsufficientParams struct {
	LastEvaluationState AlertEvaluationState `json:"last_evaluation_state"`
	LastEvaluatedAt     time.Time            `json:"last_evaluated_at"`
	LastSummary         []byte               `json:"last_summary"`
	ID                  uuid.UUID            `json:"id"`
}

func (q *Queries) UpdateActiveAlertIncidentInsufficient(ctx context.Context, arg UpdateActiveAlertIncidentInsufficientParams) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, updateActiveAlertIncidentInsufficient,
		arg.LastEvaluationState,
		arg.LastEvaluatedAt,
		arg.LastSummary,
		arg.ID,
	)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuleID,
		&i.ProbeID,
		&i.CheckID,
		&i.CheckType,
		&i.Status,
		&i.Severity,
		&i.LastEvaluationState,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.LastValue,
		&i.LastSummary,
		&i.LastNotificationSentAt,
		&i.NextNotificationEligibleAt,
		&i.SuppressedNotificationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateActiveAlertIncidentTriggered = `-- name: UpdateActiveAlertIncidentTriggered :one
UPDATE alert_incidents
SET last_evaluation_state = 'firing',
    last_evaluated_at = $1,
    last_triggered_at = $2,
    last_value = $3,
    last_summary = $4::jsonb
WHERE id = $5
  AND status IN ('open', 'acknowledged')
RETURNING id, project_id, rule_id, probe_id, check_id, check_type, status, severity, last_evaluation_state, opened_at, acknowledged_at, acknowledged_by_user_id, resolved_at, resolved_by_user_id, last_evaluated_at, last_triggered_at, last_value, last_summary, last_notification_sent_at, next_notification_eligible_at, suppressed_notification_count, created_at, updated_at
`

type UpdateActiveAlertIncidentTriggeredParams struct {
	LastEvaluatedAt time.Time `json:"last_evaluated_at"`
	LastTriggeredAt time.Time `json:"last_triggered_at"`
	LastValue       *float64  `json:"last_value"`
	LastSummary     []byte    `json:"last_summary"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) UpdateActiveAlertIncidentTriggered(ctx context.Context, arg UpdateActiveAlertIncidentTriggeredParams) (AlertIncident, error) {
	row := q.db.QueryRow(ctx, updateActiveAlertIncidentTriggered,
		arg.LastEvaluatedAt,
		arg.LastTriggeredAt,
		arg.LastValue,
		arg.LastSummary,
		arg.ID,
	)
	var i AlertIncident
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RuleID,
		&i.ProbeID,
		&i.CheckID,
		&i.CheckType,
		&i.Status,
		&i.Severity,
		&i.LastEvaluationState,
		&i.OpenedAt,
		&i.AcknowledgedAt,
		&i.AcknowledgedByUserID,
		&i.ResolvedAt,
		&i.ResolvedByUserID,
		&i.LastEvaluatedAt,
		&i.LastTriggeredAt,
		&i.LastValue,
		&i.LastSummary,
		&i.LastNotificationSentAt,
		&i.NextNotificationEligibleAt,
		&i.SuppressedNotificationCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertIncidentNotificationSent = `-- name: UpdateAlertIncidentNotificationSent :exec
UPDATE alert_incidents
SET last_notification_sent_at = $1,
    next_notification_eligible_at = $2
WHERE id = $3
`

type UpdateAlertIncidentNotificationSentParams struct {
	SentAt         *time.Time `json:"sent_at"`
	NextEligibleAt *time.Time `json:"next_eligible_at"`
	ID             uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateAlertIncidentNotificationSent(ctx context.Context, arg UpdateAlertIncidentNotificationSentParams) error {
	_, err := q.db.Exec(ctx, updateAlertIncidentNotificationSent, arg.SentAt, arg.NextEligibleAt, arg.ID)
	return err
}

const updateAlertRule = `-- name: UpdateAlertRule :one
UPDATE alert_rules
SET name = $1,
    description = $2,
    status = $3,
    severity = $4,
    check_type = $5,
    probe_id = $6,
    check_id = $7,
    probe_selector = $8::jsonb,
    condition = $9::jsonb,
    condition_version = $10,
    cooldown_seconds = $11
WHERE project_id = $12
  AND id = $13
  AND deleted_at IS NULL
RETURNING id, project_id, name, description, status, severity, check_type, probe_id, check_id, probe_selector, condition, condition_version, cooldown_seconds, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateAlertRuleParams struct {
	Name             string          `json:"name"`
	Description      *string         `json:"description"`
	Status           AlertRuleStatus `json:"status"`
	Severity         AlertSeverity   `json:"severity"`
	CheckType        CheckType       `json:"check_type"`
	ProbeID          *uuid.UUID      `json:"probe_id"`
	CheckID          *uuid.UUID      `json:"check_id"`
	ProbeSelector    []byte          `json:"probe_selector"`
	Condition        []byte          `json:"condition"`
	ConditionVersion string          `json:"condition_version"`
	CooldownSeconds  int32           `json:"cooldown_seconds"`
	ProjectID        uuid.UUID       `json:"project_id"`
	ID               uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateAlertRule(ctx context.Context, arg UpdateAlertRuleParams) (AlertRule, error) {
	row := q.db.QueryRow(ctx, updateAlertRule,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Severity,
		arg.CheckType,
		arg.ProbeID,
		arg.CheckID,
		arg.ProbeSelector,
		arg.Condition,
		arg.ConditionVersion,
		arg.CooldownSeconds,
		arg.ProjectID,
		arg.ID,
	)
	var i AlertRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Severity,
		&i.CheckType,
		&i.ProbeID,
		&i.CheckID,
		&i.ProbeSelector,
		&i.Condition,
		&i.ConditionVersion,
		&i.CooldownSeconds,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET name = $1,
    type = $2,
    enabled = $3,
    config = $4::jsonb
WHERE project_id = $5
  AND id = $6
  AND deleted_at IS NULL
RETURNING id, project_id, name, type, enabled, config, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateNotificationChannelParams struct {
	Name        string                  `json:"name"`
	ChannelType NotificationChannelType `json:"channel_type"`
	Enabled     bool                    `json:"enabled"`
	Config      []byte                  `json:"config"`
	ProjectID   uuid.UUID               `json:"project_id"`
	ID          uuid.UUID               `json:"id"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.Name,
		arg.ChannelType,
		arg.Enabled,
		arg.Config,
		arg.ProjectID,
		arg.ID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.Config,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
