// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listProjectAssignments = `-- name: ListProjectAssignments :many
SELECT probe_check_assignments.id AS assignment_id,
       probe_check_assignments.project_id,
       probe_check_assignments.probe_id,
       probe_check_assignments.check_id,
       probes.internal_id AS probe_internal_id,
       probes.name AS probe_name,
       probes.enabled AS probe_enabled,
       probes.location AS probe_location,
       probes.location_name AS probe_location_name,
       probes.created_at AS probe_created_at,
       probes.updated_at AS probe_updated_at,
       probes.deleted_at AS probe_deleted_at,
       checks.internal_id AS check_internal_id,
       probe_check_assignments.check_version,
       probe_check_assignments.selector_version,
       checks.name AS check_name,
       checks.check_type,
       checks.target,
       checks.selector,
       checks.description,
       checks.interval_seconds,
       checks.created_at AS check_created_at,
       checks.updated_at AS check_updated_at,
       checks.deleted_at AS check_deleted_at,
       ping_check_configs.packet_count AS ping_packet_count,
       ping_check_configs.packet_size_bytes AS ping_packet_size_bytes,
       ping_check_configs.timeout_ms AS ping_timeout_ms,
       ping_check_configs.ip_family AS ping_ip_family,
       tcp_check_configs.port AS tcp_port,
       tcp_check_configs.timeout_ms AS tcp_timeout_ms,
       tcp_check_configs.ip_family AS tcp_ip_family,
       traceroute_check_configs.protocol AS traceroute_protocol,
       traceroute_check_configs.max_hops AS traceroute_max_hops,
       traceroute_check_configs.timeout_ms AS traceroute_timeout_ms,
       traceroute_check_configs.queries_per_hop AS traceroute_queries_per_hop,
       traceroute_check_configs.packet_size_bytes AS traceroute_packet_size_bytes,
       traceroute_check_configs.port AS traceroute_port,
       traceroute_check_configs.ip_family AS traceroute_ip_family
FROM probe_check_assignments
JOIN probes
    ON probes.project_id = probe_check_assignments.project_id
    AND probes.id = probe_check_assignments.probe_id
JOIN checks
    ON checks.project_id = probe_check_assignments.project_id
    AND checks.id = probe_check_assignments.check_id
LEFT JOIN ping_check_configs ON ping_check_configs.check_id = checks.id
LEFT JOIN tcp_check_configs ON tcp_check_configs.check_id = checks.id
LEFT JOIN traceroute_check_configs ON traceroute_check_configs.check_id = checks.id
WHERE probe_check_assignments.project_id = $1
  AND (
      $2::uuid IS NULL
      OR probe_check_assignments.probe_id = $2::uuid
  )
  AND (
      $3::uuid IS NULL
      OR probe_check_assignments.check_id = $3::uuid
  )
  AND probe_check_assignments.deleted_at IS NULL
  AND probes.deleted_at IS NULL
  AND checks.deleted_at IS NULL
ORDER BY probes.created_at ASC,
         probes.id ASC,
         checks.created_at ASC,
         checks.id ASC
`

type ListProjectAssignmentsParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	ProbeID   *uuid.UUID `json:"probe_id"`
	CheckID   *uuid.UUID `json:"check_id"`
}

type ListProjectAssignmentsRow struct {
	AssignmentID              uuid.UUID              `json:"assignment_id"`
	ProjectID                 uuid.UUID              `json:"project_id"`
	ProbeID                   uuid.UUID              `json:"probe_id"`
	CheckID                   uuid.UUID              `json:"check_id"`
	ProbeInternalID           int64                  `json:"probe_internal_id"`
	ProbeName                 string                 `json:"probe_name"`
	ProbeEnabled              bool                   `json:"probe_enabled"`
	ProbeLocation             pgtype.Point           `json:"probe_location"`
	ProbeLocationName         *string                `json:"probe_location_name"`
	ProbeCreatedAt            pgtype.Timestamptz     `json:"probe_created_at"`
	ProbeUpdatedAt            pgtype.Timestamptz     `json:"probe_updated_at"`
	ProbeDeletedAt            pgtype.Timestamptz     `json:"probe_deleted_at"`
	CheckInternalID           int64                  `json:"check_internal_id"`
	CheckVersion              string                 `json:"check_version"`
	SelectorVersion           string                 `json:"selector_version"`
	CheckName                 string                 `json:"check_name"`
	CheckType                 CheckType              `json:"check_type"`
	Target                    string                 `json:"target"`
	Selector                  []byte                 `json:"selector"`
	Description               *string                `json:"description"`
	IntervalSeconds           int32                  `json:"interval_seconds"`
	CheckCreatedAt            pgtype.Timestamptz     `json:"check_created_at"`
	CheckUpdatedAt            pgtype.Timestamptz     `json:"check_updated_at"`
	CheckDeletedAt            pgtype.Timestamptz     `json:"check_deleted_at"`
	PingPacketCount           *int32                 `json:"ping_packet_count"`
	PingPacketSizeBytes       *int32                 `json:"ping_packet_size_bytes"`
	PingTimeoutMs             *int32                 `json:"ping_timeout_ms"`
	PingIpFamily              NullIpFamily           `json:"ping_ip_family"`
	TcpPort                   *int32                 `json:"tcp_port"`
	TcpTimeoutMs              *int32                 `json:"tcp_timeout_ms"`
	TcpIpFamily               NullIpFamily           `json:"tcp_ip_family"`
	TracerouteProtocol        NullTracerouteProtocol `json:"traceroute_protocol"`
	TracerouteMaxHops         *int32                 `json:"traceroute_max_hops"`
	TracerouteTimeoutMs       *int32                 `json:"traceroute_timeout_ms"`
	TracerouteQueriesPerHop   *int32                 `json:"traceroute_queries_per_hop"`
	TraceroutePacketSizeBytes *int32                 `json:"traceroute_packet_size_bytes"`
	TraceroutePort            *int32                 `json:"traceroute_port"`
	TracerouteIpFamily        NullIpFamily           `json:"traceroute_ip_family"`
}

func (q *Queries) ListProjectAssignments(ctx context.Context, arg ListProjectAssignmentsParams) ([]ListProjectAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listProjectAssignments, arg.ProjectID, arg.ProbeID, arg.CheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectAssignmentsRow
	for rows.Next() {
		var i ListProjectAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.ProjectID,
			&i.ProbeID,
			&i.CheckID,
			&i.ProbeInternalID,
			&i.ProbeName,
			&i.ProbeEnabled,
			&i.ProbeLocation,
			&i.ProbeLocationName,
			&i.ProbeCreatedAt,
			&i.ProbeUpdatedAt,
			&i.ProbeDeletedAt,
			&i.CheckInternalID,
			&i.CheckVersion,
			&i.SelectorVersion,
			&i.CheckName,
			&i.CheckType,
			&i.Target,
			&i.Selector,
			&i.Description,
			&i.IntervalSeconds,
			&i.CheckCreatedAt,
			&i.CheckUpdatedAt,
			&i.CheckDeletedAt,
			&i.PingPacketCount,
			&i.PingPacketSizeBytes,
			&i.PingTimeoutMs,
			&i.PingIpFamily,
			&i.TcpPort,
			&i.TcpTimeoutMs,
			&i.TcpIpFamily,
			&i.TracerouteProtocol,
			&i.TracerouteMaxHops,
			&i.TracerouteTimeoutMs,
			&i.TracerouteQueriesPerHop,
			&i.TraceroutePacketSizeBytes,
			&i.TraceroutePort,
			&i.TracerouteIpFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
