// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    user_id,
    token_hash,
    csrf_token_hash,
    created_at,
    last_used_at,
    idle_expires_at,
    absolute_expires_at,
    user_agent
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id,
          user_id,
          token_hash,
          csrf_token_hash,
          created_at,
          last_used_at,
          idle_expires_at,
          absolute_expires_at,
          revoked_at,
          revoked_reason,
          user_agent
`

type CreateAuthSessionParams struct {
	UserID            uuid.UUID `json:"user_id"`
	TokenHash         []byte    `json:"token_hash"`
	CsrfTokenHash     []byte    `json:"csrf_token_hash"`
	CreatedAt         time.Time `json:"created_at"`
	LastUsedAt        time.Time `json:"last_used_at"`
	IdleExpiresAt     time.Time `json:"idle_expires_at"`
	AbsoluteExpiresAt time.Time `json:"absolute_expires_at"`
	UserAgent         string    `json:"user_agent"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfTokenHash,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.UserAgent,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.UserAgent,
	)
	return i, err
}

const getActiveAuthSessionByID = `-- name: GetActiveAuthSessionByID :one
SELECT auth_sessions.id,
       auth_sessions.user_id,
       auth_sessions.token_hash,
       auth_sessions.csrf_token_hash,
       auth_sessions.created_at,
       auth_sessions.last_used_at,
       auth_sessions.idle_expires_at,
       auth_sessions.absolute_expires_at,
       auth_sessions.revoked_at,
       auth_sessions.revoked_reason,
       auth_sessions.user_agent
FROM auth_sessions
JOIN users ON users.id = auth_sessions.user_id
WHERE auth_sessions.id = $1
  AND auth_sessions.revoked_at IS NULL
  AND auth_sessions.idle_expires_at > $2
  AND auth_sessions.absolute_expires_at > $2
  AND users.disabled_at IS NULL
`

type GetActiveAuthSessionByIDParams struct {
	ID    uuid.UUID `json:"id"`
	NowAt time.Time `json:"now_at"`
}

func (q *Queries) GetActiveAuthSessionByID(ctx context.Context, arg GetActiveAuthSessionByIDParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getActiveAuthSessionByID, arg.ID, arg.NowAt)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.UserAgent,
	)
	return i, err
}

const getActiveAuthSessionByTokenHash = `-- name: GetActiveAuthSessionByTokenHash :one
SELECT auth_sessions.id,
       auth_sessions.user_id,
       auth_sessions.token_hash,
       auth_sessions.csrf_token_hash,
       auth_sessions.created_at,
       auth_sessions.last_used_at,
       auth_sessions.idle_expires_at,
       auth_sessions.absolute_expires_at,
       auth_sessions.revoked_at,
       auth_sessions.revoked_reason,
       auth_sessions.user_agent
FROM auth_sessions
JOIN users ON users.id = auth_sessions.user_id
WHERE auth_sessions.token_hash = $1
  AND auth_sessions.revoked_at IS NULL
  AND auth_sessions.idle_expires_at > $2
  AND auth_sessions.absolute_expires_at > $2
  AND users.disabled_at IS NULL
`

type GetActiveAuthSessionByTokenHashParams struct {
	TokenHash []byte    `json:"token_hash"`
	NowAt     time.Time `json:"now_at"`
}

func (q *Queries) GetActiveAuthSessionByTokenHash(ctx context.Context, arg GetActiveAuthSessionByTokenHashParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getActiveAuthSessionByTokenHash, arg.TokenHash, arg.NowAt)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.UserAgent,
	)
	return i, err
}

const listActiveAuthSessionsForUser = `-- name: ListActiveAuthSessionsForUser :many
SELECT auth_sessions.id,
       auth_sessions.user_id,
       auth_sessions.token_hash,
       auth_sessions.csrf_token_hash,
       auth_sessions.created_at,
       auth_sessions.last_used_at,
       auth_sessions.idle_expires_at,
       auth_sessions.absolute_expires_at,
       auth_sessions.revoked_at,
       auth_sessions.revoked_reason,
       auth_sessions.user_agent
FROM auth_sessions
JOIN users ON users.id = auth_sessions.user_id
WHERE auth_sessions.user_id = $1
  AND auth_sessions.revoked_at IS NULL
  AND auth_sessions.idle_expires_at > $2
  AND auth_sessions.absolute_expires_at > $2
  AND users.disabled_at IS NULL
ORDER BY auth_sessions.last_used_at DESC, auth_sessions.created_at DESC
`

type ListActiveAuthSessionsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	NowAt  time.Time `json:"now_at"`
}

func (q *Queries) ListActiveAuthSessionsForUser(ctx context.Context, arg ListActiveAuthSessionsForUserParams) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listActiveAuthSessionsForUser, arg.UserID, arg.NowAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthSession
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CsrfTokenHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAuthSessionByIDForUser = `-- name: RevokeAuthSessionByIDForUser :one
UPDATE auth_sessions
SET revoked_at = $1,
    revoked_reason = $2
WHERE id = $3
  AND user_id = $4
  AND revoked_at IS NULL
  AND idle_expires_at > $1
  AND absolute_expires_at > $1
RETURNING id
`

type RevokeAuthSessionByIDForUserParams struct {
	RevokedAt     *time.Time `json:"revoked_at"`
	RevokedReason *string    `json:"revoked_reason"`
	ID            uuid.UUID  `json:"id"`
	UserID        uuid.UUID  `json:"user_id"`
}

func (q *Queries) RevokeAuthSessionByIDForUser(ctx context.Context, arg RevokeAuthSessionByIDForUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeAuthSessionByIDForUser,
		arg.RevokedAt,
		arg.RevokedReason,
		arg.ID,
		arg.UserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const revokeAuthSessionByTokenHash = `-- name: RevokeAuthSessionByTokenHash :exec
UPDATE auth_sessions
SET revoked_at = $1,
    revoked_reason = $2
WHERE token_hash = $3
  AND revoked_at IS NULL
`

type RevokeAuthSessionByTokenHashParams struct {
	RevokedAt     *time.Time `json:"revoked_at"`
	RevokedReason *string    `json:"revoked_reason"`
	TokenHash     []byte     `json:"token_hash"`
}

func (q *Queries) RevokeAuthSessionByTokenHash(ctx context.Context, arg RevokeAuthSessionByTokenHashParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionByTokenHash, arg.RevokedAt, arg.RevokedReason, arg.TokenHash)
	return err
}

const revokeAuthSessionsForUser = `-- name: RevokeAuthSessionsForUser :exec
UPDATE auth_sessions
SET revoked_at = $1,
    revoked_reason = $2
WHERE user_id = $3
  AND revoked_at IS NULL
`

type RevokeAuthSessionsForUserParams struct {
	RevokedAt     *time.Time `json:"revoked_at"`
	RevokedReason *string    `json:"revoked_reason"`
	UserID        uuid.UUID  `json:"user_id"`
}

func (q *Queries) RevokeAuthSessionsForUser(ctx context.Context, arg RevokeAuthSessionsForUserParams) error {
	_, err := q.db.Exec(ctx, revokeAuthSessionsForUser, arg.RevokedAt, arg.RevokedReason, arg.UserID)
	return err
}

const touchAuthSession = `-- name: TouchAuthSession :exec
UPDATE auth_sessions
SET last_used_at = $1,
    idle_expires_at = $2
WHERE id = $3
  AND revoked_at IS NULL
  AND absolute_expires_at > $1
`

type TouchAuthSessionParams struct {
	LastUsedAt    time.Time `json:"last_used_at"`
	IdleExpiresAt time.Time `json:"idle_expires_at"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) error {
	_, err := q.db.Exec(ctx, touchAuthSession, arg.LastUsedAt, arg.IdleExpiresAt, arg.ID)
	return err
}

const updateAuthSessionCSRFTokenHash = `-- name: UpdateAuthSessionCSRFTokenHash :exec
UPDATE auth_sessions
SET csrf_token_hash = $1
WHERE id = $2
  AND revoked_at IS NULL
  AND idle_expires_at > $3
  AND absolute_expires_at > $3
`

type UpdateAuthSessionCSRFTokenHashParams struct {
	CsrfTokenHash []byte    `json:"csrf_token_hash"`
	ID            uuid.UUID `json:"id"`
	NowAt         time.Time `json:"now_at"`
}

func (q *Queries) UpdateAuthSessionCSRFTokenHash(ctx context.Context, arg UpdateAuthSessionCSRFTokenHashParams) error {
	_, err := q.db.Exec(ctx, updateAuthSessionCSRFTokenHash, arg.CsrfTokenHash, arg.ID, arg.NowAt)
	return err
}
