// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (project_id, name, check_type, target, selector, description, interval_seconds)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::jsonb,
    $6,
    $7
)
RETURNING id, internal_id, project_id, name, check_type, target, selector, description, interval_seconds, created_at, updated_at, deleted_at
`

type CreateCheckParams struct {
	ProjectID       uuid.UUID `json:"project_id"`
	Name            string    `json:"name"`
	CheckType       CheckType `json:"check_type"`
	Target          string    `json:"target"`
	Selector        []byte    `json:"selector"`
	Description     *string   `json:"description"`
	IntervalSeconds int32     `json:"interval_seconds"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, createCheck,
		arg.ProjectID,
		arg.Name,
		arg.CheckType,
		arg.Target,
		arg.Selector,
		arg.Description,
		arg.IntervalSeconds,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.ProjectID,
		&i.Name,
		&i.CheckType,
		&i.Target,
		&i.Selector,
		&i.Description,
		&i.IntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCheckLabel = `-- name: CreateCheckLabel :exec
INSERT INTO check_labels (project_id, check_id, label_id)
VALUES ($1, $2, $3)
`

type CreateCheckLabelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	CheckID   uuid.UUID `json:"check_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

func (q *Queries) CreateCheckLabel(ctx context.Context, arg CreateCheckLabelParams) error {
	_, err := q.db.Exec(ctx, createCheckLabel, arg.ProjectID, arg.CheckID, arg.LabelID)
	return err
}

const createPingCheckConfig = `-- name: CreatePingCheckConfig :one
INSERT INTO ping_check_configs (check_id, packet_count, packet_size_bytes, timeout_ms, ip_family)
VALUES ($1, $2, $3, $4, $5)
RETURNING check_id, packet_count, packet_size_bytes, timeout_ms, ip_family
`

type CreatePingCheckConfigParams struct {
	CheckID         uuid.UUID `json:"check_id"`
	PacketCount     int32     `json:"packet_count"`
	PacketSizeBytes int32     `json:"packet_size_bytes"`
	TimeoutMs       int32     `json:"timeout_ms"`
	IpFamily        *IpFamily `json:"ip_family"`
}

func (q *Queries) CreatePingCheckConfig(ctx context.Context, arg CreatePingCheckConfigParams) (PingCheckConfig, error) {
	row := q.db.QueryRow(ctx, createPingCheckConfig,
		arg.CheckID,
		arg.PacketCount,
		arg.PacketSizeBytes,
		arg.TimeoutMs,
		arg.IpFamily,
	)
	var i PingCheckConfig
	err := row.Scan(
		&i.CheckID,
		&i.PacketCount,
		&i.PacketSizeBytes,
		&i.TimeoutMs,
		&i.IpFamily,
	)
	return i, err
}

const createProbeCheckAssignment = `-- name: CreateProbeCheckAssignment :exec
INSERT INTO probe_check_assignments (project_id, probe_id, check_id, check_version, selector_version)
VALUES ($1, $2, $3, $4, $5)
`

type CreateProbeCheckAssignmentParams struct {
	ProjectID       uuid.UUID `json:"project_id"`
	ProbeID         uuid.UUID `json:"probe_id"`
	CheckID         uuid.UUID `json:"check_id"`
	CheckVersion    string    `json:"check_version"`
	SelectorVersion string    `json:"selector_version"`
}

func (q *Queries) CreateProbeCheckAssignment(ctx context.Context, arg CreateProbeCheckAssignmentParams) error {
	_, err := q.db.Exec(ctx, createProbeCheckAssignment,
		arg.ProjectID,
		arg.ProbeID,
		arg.CheckID,
		arg.CheckVersion,
		arg.SelectorVersion,
	)
	return err
}

const createTCPCheckConfig = `-- name: CreateTCPCheckConfig :one
INSERT INTO tcp_check_configs (check_id, port, timeout_ms, ip_family)
VALUES ($1, $2, $3, $4)
RETURNING check_id, port, timeout_ms, ip_family
`

type CreateTCPCheckConfigParams struct {
	CheckID   uuid.UUID `json:"check_id"`
	Port      int32     `json:"port"`
	TimeoutMs int32     `json:"timeout_ms"`
	IpFamily  *IpFamily `json:"ip_family"`
}

func (q *Queries) CreateTCPCheckConfig(ctx context.Context, arg CreateTCPCheckConfigParams) (TcpCheckConfig, error) {
	row := q.db.QueryRow(ctx, createTCPCheckConfig,
		arg.CheckID,
		arg.Port,
		arg.TimeoutMs,
		arg.IpFamily,
	)
	var i TcpCheckConfig
	err := row.Scan(
		&i.CheckID,
		&i.Port,
		&i.TimeoutMs,
		&i.IpFamily,
	)
	return i, err
}

const createTracerouteCheckConfig = `-- name: CreateTracerouteCheckConfig :one
INSERT INTO traceroute_check_configs (check_id, protocol, max_hops, timeout_ms, queries_per_hop, packet_size_bytes, port, ip_family)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING check_id, protocol, max_hops, timeout_ms, queries_per_hop, packet_size_bytes, port, ip_family
`

type CreateTracerouteCheckConfigParams struct {
	CheckID         uuid.UUID          `json:"check_id"`
	Protocol        TracerouteProtocol `json:"protocol"`
	MaxHops         int32              `json:"max_hops"`
	TimeoutMs       int32              `json:"timeout_ms"`
	QueriesPerHop   int32              `json:"queries_per_hop"`
	PacketSizeBytes int32              `json:"packet_size_bytes"`
	Port            int32              `json:"port"`
	IpFamily        *IpFamily          `json:"ip_family"`
}

func (q *Queries) CreateTracerouteCheckConfig(ctx context.Context, arg CreateTracerouteCheckConfigParams) (TracerouteCheckConfig, error) {
	row := q.db.QueryRow(ctx, createTracerouteCheckConfig,
		arg.CheckID,
		arg.Protocol,
		arg.MaxHops,
		arg.TimeoutMs,
		arg.QueriesPerHop,
		arg.PacketSizeBytes,
		arg.Port,
		arg.IpFamily,
	)
	var i TracerouteCheckConfig
	err := row.Scan(
		&i.CheckID,
		&i.Protocol,
		&i.MaxHops,
		&i.TimeoutMs,
		&i.QueriesPerHop,
		&i.PacketSizeBytes,
		&i.Port,
		&i.IpFamily,
	)
	return i, err
}

const deleteCheckLabels = `-- name: DeleteCheckLabels :exec
DELETE FROM check_labels
WHERE project_id = $1
  AND check_id = $2
`

type DeleteCheckLabelsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	CheckID   uuid.UUID `json:"check_id"`
}

func (q *Queries) DeleteCheckLabels(ctx context.Context, arg DeleteCheckLabelsParams) error {
	_, err := q.db.Exec(ctx, deleteCheckLabels, arg.ProjectID, arg.CheckID)
	return err
}

const deleteProbeCheckAssignmentsForCheck = `-- name: DeleteProbeCheckAssignmentsForCheck :exec
DELETE FROM probe_check_assignments
WHERE project_id = $1
  AND check_id = $2
`

type DeleteProbeCheckAssignmentsForCheckParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	CheckID   uuid.UUID `json:"check_id"`
}

func (q *Queries) DeleteProbeCheckAssignmentsForCheck(ctx context.Context, arg DeleteProbeCheckAssignmentsForCheckParams) error {
	_, err := q.db.Exec(ctx, deleteProbeCheckAssignmentsForCheck, arg.ProjectID, arg.CheckID)
	return err
}

const deleteStaleProbeCheckAssignments = `-- name: DeleteStaleProbeCheckAssignments :exec
DELETE FROM probe_check_assignments
WHERE project_id = $1
  AND check_id = $2
  AND deleted_at IS NULL
  AND (
      check_version <> $3
      OR selector_version <> $4
      OR probe_id <> ALL($5::uuid[])
  )
`

type DeleteStaleProbeCheckAssignmentsParams struct {
	ProjectID       uuid.UUID   `json:"project_id"`
	CheckID         uuid.UUID   `json:"check_id"`
	CheckVersion    string      `json:"check_version"`
	SelectorVersion string      `json:"selector_version"`
	ProbeIds        []uuid.UUID `json:"probe_ids"`
}

func (q *Queries) DeleteStaleProbeCheckAssignments(ctx context.Context, arg DeleteStaleProbeCheckAssignmentsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleProbeCheckAssignments,
		arg.ProjectID,
		arg.CheckID,
		arg.CheckVersion,
		arg.SelectorVersion,
		arg.ProbeIds,
	)
	return err
}

const getActiveCheckForProject = `-- name: GetActiveCheckForProject :one
SELECT checks.internal_id,
       checks.id,
       checks.project_id,
       checks.name,
       checks.check_type,
       checks.target,
       checks.selector,
       checks.description,
       checks.interval_seconds,
       checks.created_at,
       checks.updated_at,
       checks.deleted_at,
       ping_check_configs.packet_count AS ping_packet_count,
       ping_check_configs.packet_size_bytes AS ping_packet_size_bytes,
       ping_check_configs.timeout_ms AS ping_timeout_ms,
       ping_check_configs.ip_family AS ping_ip_family,
       tcp_check_configs.port AS tcp_port,
       tcp_check_configs.timeout_ms AS tcp_timeout_ms,
       tcp_check_configs.ip_family AS tcp_ip_family,
       traceroute_check_configs.protocol AS traceroute_protocol,
       traceroute_check_configs.max_hops AS traceroute_max_hops,
       traceroute_check_configs.timeout_ms AS traceroute_timeout_ms,
       traceroute_check_configs.queries_per_hop AS traceroute_queries_per_hop,
       traceroute_check_configs.packet_size_bytes AS traceroute_packet_size_bytes,
       traceroute_check_configs.port AS traceroute_port,
       traceroute_check_configs.ip_family AS traceroute_ip_family
FROM checks
LEFT JOIN ping_check_configs ON ping_check_configs.check_id = checks.id
LEFT JOIN tcp_check_configs ON tcp_check_configs.check_id = checks.id
LEFT JOIN traceroute_check_configs ON traceroute_check_configs.check_id = checks.id
WHERE checks.project_id = $1
  AND checks.id = $2
  AND checks.deleted_at IS NULL
`

type GetActiveCheckForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

type GetActiveCheckForProjectRow struct {
	InternalID                int64               `json:"internal_id"`
	ID                        uuid.UUID           `json:"id"`
	ProjectID                 uuid.UUID           `json:"project_id"`
	Name                      string              `json:"name"`
	CheckType                 CheckType           `json:"check_type"`
	Target                    string              `json:"target"`
	Selector                  []byte              `json:"selector"`
	Description               *string             `json:"description"`
	IntervalSeconds           int32               `json:"interval_seconds"`
	CreatedAt                 time.Time           `json:"created_at"`
	UpdatedAt                 time.Time           `json:"updated_at"`
	DeletedAt                 *time.Time          `json:"deleted_at"`
	PingPacketCount           *int32              `json:"ping_packet_count"`
	PingPacketSizeBytes       *int32              `json:"ping_packet_size_bytes"`
	PingTimeoutMs             *int32              `json:"ping_timeout_ms"`
	PingIpFamily              *IpFamily           `json:"ping_ip_family"`
	TcpPort                   *int32              `json:"tcp_port"`
	TcpTimeoutMs              *int32              `json:"tcp_timeout_ms"`
	TcpIpFamily               *IpFamily           `json:"tcp_ip_family"`
	TracerouteProtocol        *TracerouteProtocol `json:"traceroute_protocol"`
	TracerouteMaxHops         *int32              `json:"traceroute_max_hops"`
	TracerouteTimeoutMs       *int32              `json:"traceroute_timeout_ms"`
	TracerouteQueriesPerHop   *int32              `json:"traceroute_queries_per_hop"`
	TraceroutePacketSizeBytes *int32              `json:"traceroute_packet_size_bytes"`
	TraceroutePort            *int32              `json:"traceroute_port"`
	TracerouteIpFamily        *IpFamily           `json:"traceroute_ip_family"`
}

func (q *Queries) GetActiveCheckForProject(ctx context.Context, arg GetActiveCheckForProjectParams) (GetActiveCheckForProjectRow, error) {
	row := q.db.QueryRow(ctx, getActiveCheckForProject, arg.ProjectID, arg.ID)
	var i GetActiveCheckForProjectRow
	err := row.Scan(
		&i.InternalID,
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.CheckType,
		&i.Target,
		&i.Selector,
		&i.Description,
		&i.IntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PingPacketCount,
		&i.PingPacketSizeBytes,
		&i.PingTimeoutMs,
		&i.PingIpFamily,
		&i.TcpPort,
		&i.TcpTimeoutMs,
		&i.TcpIpFamily,
		&i.TracerouteProtocol,
		&i.TracerouteMaxHops,
		&i.TracerouteTimeoutMs,
		&i.TracerouteQueriesPerHop,
		&i.TraceroutePacketSizeBytes,
		&i.TraceroutePort,
		&i.TracerouteIpFamily,
	)
	return i, err
}

const listActiveChecksForProject = `-- name: ListActiveChecksForProject :many
SELECT checks.internal_id,
       checks.id,
       checks.project_id,
       checks.name,
       checks.check_type,
       checks.target,
       checks.selector,
       checks.description,
       checks.interval_seconds,
       checks.created_at,
       checks.updated_at,
       checks.deleted_at,
       ping_check_configs.packet_count AS ping_packet_count,
       ping_check_configs.packet_size_bytes AS ping_packet_size_bytes,
       ping_check_configs.timeout_ms AS ping_timeout_ms,
       ping_check_configs.ip_family AS ping_ip_family,
       tcp_check_configs.port AS tcp_port,
       tcp_check_configs.timeout_ms AS tcp_timeout_ms,
       tcp_check_configs.ip_family AS tcp_ip_family,
       traceroute_check_configs.protocol AS traceroute_protocol,
       traceroute_check_configs.max_hops AS traceroute_max_hops,
       traceroute_check_configs.timeout_ms AS traceroute_timeout_ms,
       traceroute_check_configs.queries_per_hop AS traceroute_queries_per_hop,
       traceroute_check_configs.packet_size_bytes AS traceroute_packet_size_bytes,
       traceroute_check_configs.port AS traceroute_port,
       traceroute_check_configs.ip_family AS traceroute_ip_family
FROM checks
LEFT JOIN ping_check_configs ON ping_check_configs.check_id = checks.id
LEFT JOIN tcp_check_configs ON tcp_check_configs.check_id = checks.id
LEFT JOIN traceroute_check_configs ON traceroute_check_configs.check_id = checks.id
WHERE checks.project_id = $1
  AND checks.deleted_at IS NULL
ORDER BY checks.created_at DESC, checks.id DESC
`

type ListActiveChecksForProjectRow struct {
	InternalID                int64               `json:"internal_id"`
	ID                        uuid.UUID           `json:"id"`
	ProjectID                 uuid.UUID           `json:"project_id"`
	Name                      string              `json:"name"`
	CheckType                 CheckType           `json:"check_type"`
	Target                    string              `json:"target"`
	Selector                  []byte              `json:"selector"`
	Description               *string             `json:"description"`
	IntervalSeconds           int32               `json:"interval_seconds"`
	CreatedAt                 time.Time           `json:"created_at"`
	UpdatedAt                 time.Time           `json:"updated_at"`
	DeletedAt                 *time.Time          `json:"deleted_at"`
	PingPacketCount           *int32              `json:"ping_packet_count"`
	PingPacketSizeBytes       *int32              `json:"ping_packet_size_bytes"`
	PingTimeoutMs             *int32              `json:"ping_timeout_ms"`
	PingIpFamily              *IpFamily           `json:"ping_ip_family"`
	TcpPort                   *int32              `json:"tcp_port"`
	TcpTimeoutMs              *int32              `json:"tcp_timeout_ms"`
	TcpIpFamily               *IpFamily           `json:"tcp_ip_family"`
	TracerouteProtocol        *TracerouteProtocol `json:"traceroute_protocol"`
	TracerouteMaxHops         *int32              `json:"traceroute_max_hops"`
	TracerouteTimeoutMs       *int32              `json:"traceroute_timeout_ms"`
	TracerouteQueriesPerHop   *int32              `json:"traceroute_queries_per_hop"`
	TraceroutePacketSizeBytes *int32              `json:"traceroute_packet_size_bytes"`
	TraceroutePort            *int32              `json:"traceroute_port"`
	TracerouteIpFamily        *IpFamily           `json:"traceroute_ip_family"`
}

func (q *Queries) ListActiveChecksForProject(ctx context.Context, projectID uuid.UUID) ([]ListActiveChecksForProjectRow, error) {
	rows, err := q.db.Query(ctx, listActiveChecksForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveChecksForProjectRow
	for rows.Next() {
		var i ListActiveChecksForProjectRow
		if err := rows.Scan(
			&i.InternalID,
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.CheckType,
			&i.Target,
			&i.Selector,
			&i.Description,
			&i.IntervalSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PingPacketCount,
			&i.PingPacketSizeBytes,
			&i.PingTimeoutMs,
			&i.PingIpFamily,
			&i.TcpPort,
			&i.TcpTimeoutMs,
			&i.TcpIpFamily,
			&i.TracerouteProtocol,
			&i.TracerouteMaxHops,
			&i.TracerouteTimeoutMs,
			&i.TracerouteQueriesPerHop,
			&i.TraceroutePacketSizeBytes,
			&i.TraceroutePort,
			&i.TracerouteIpFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveEnabledProbeLabelsForProject = `-- name: ListActiveEnabledProbeLabelsForProject :many
SELECT probes.id AS probe_id,
       probes.internal_id AS probe_internal_id,
       probes.project_id AS probe_project_id,
       probes.name AS probe_name,
       probes.enabled AS probe_enabled,
       labels.id AS label_id,
       labels.project_id AS label_project_id,
       labels.key AS label_key,
       labels.value AS label_value,
       labels.created_at AS label_created_at,
       labels.updated_at AS label_updated_at,
       labels.deleted_at AS label_deleted_at
FROM probes
LEFT JOIN probe_labels
    ON probe_labels.project_id = probes.project_id
    AND probe_labels.probe_id = probes.id
LEFT JOIN labels
    ON labels.project_id = probe_labels.project_id
    AND labels.id = probe_labels.label_id
    AND labels.deleted_at IS NULL
WHERE probes.project_id = $1
  AND probes.enabled = true
  AND probes.deleted_at IS NULL
ORDER BY probes.created_at ASC,
         probes.id ASC,
         labels.key ASC NULLS LAST,
         labels.value ASC NULLS LAST,
         labels.id ASC NULLS LAST
`

type ListActiveEnabledProbeLabelsForProjectRow struct {
	ProbeID         uuid.UUID  `json:"probe_id"`
	ProbeInternalID int64      `json:"probe_internal_id"`
	ProbeProjectID  uuid.UUID  `json:"probe_project_id"`
	ProbeName       string     `json:"probe_name"`
	ProbeEnabled    bool       `json:"probe_enabled"`
	LabelID         *uuid.UUID `json:"label_id"`
	LabelProjectID  *uuid.UUID `json:"label_project_id"`
	LabelKey        *string    `json:"label_key"`
	LabelValue      *string    `json:"label_value"`
	LabelCreatedAt  *time.Time `json:"label_created_at"`
	LabelUpdatedAt  *time.Time `json:"label_updated_at"`
	LabelDeletedAt  *time.Time `json:"label_deleted_at"`
}

func (q *Queries) ListActiveEnabledProbeLabelsForProject(ctx context.Context, projectID uuid.UUID) ([]ListActiveEnabledProbeLabelsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listActiveEnabledProbeLabelsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveEnabledProbeLabelsForProjectRow
	for rows.Next() {
		var i ListActiveEnabledProbeLabelsForProjectRow
		if err := rows.Scan(
			&i.ProbeID,
			&i.ProbeInternalID,
			&i.ProbeProjectID,
			&i.ProbeName,
			&i.ProbeEnabled,
			&i.LabelID,
			&i.LabelProjectID,
			&i.LabelKey,
			&i.LabelValue,
			&i.LabelCreatedAt,
			&i.LabelUpdatedAt,
			&i.LabelDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLabelsForCheck = `-- name: ListActiveLabelsForCheck :many
SELECT labels.id,
       labels.project_id,
       labels.key,
       labels.value,
       labels.created_at,
       labels.updated_at,
       labels.deleted_at
FROM check_labels
JOIN labels
    ON labels.project_id = check_labels.project_id
    AND labels.id = check_labels.label_id
WHERE check_labels.project_id = $1
  AND check_labels.check_id = $2
  AND labels.deleted_at IS NULL
ORDER BY labels.key ASC, labels.value ASC, labels.id ASC
`

type ListActiveLabelsForCheckParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	CheckID   uuid.UUID `json:"check_id"`
}

func (q *Queries) ListActiveLabelsForCheck(ctx context.Context, arg ListActiveLabelsForCheckParams) ([]Label, error) {
	rows, err := q.db.Query(ctx, listActiveLabelsForCheck, arg.ProjectID, arg.CheckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCheck = `-- name: SoftDeleteCheck :one
UPDATE checks
SET deleted_at = now()
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteCheckParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteCheck(ctx context.Context, arg SoftDeleteCheckParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteCheck, arg.ProjectID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCheck = `-- name: UpdateCheck :one
UPDATE checks
SET name = $1,
    check_type = $2,
    target = $3,
    selector = $4::jsonb,
    description = $5,
    interval_seconds = $6
WHERE project_id = $7
  AND id = $8
  AND deleted_at IS NULL
RETURNING id, internal_id, project_id, name, check_type, target, selector, description, interval_seconds, created_at, updated_at, deleted_at
`

type UpdateCheckParams struct {
	Name            string    `json:"name"`
	CheckType       CheckType `json:"check_type"`
	Target          string    `json:"target"`
	Selector        []byte    `json:"selector"`
	Description     *string   `json:"description"`
	IntervalSeconds int32     `json:"interval_seconds"`
	ProjectID       uuid.UUID `json:"project_id"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCheck(ctx context.Context, arg UpdateCheckParams) (Check, error) {
	row := q.db.QueryRow(ctx, updateCheck,
		arg.Name,
		arg.CheckType,
		arg.Target,
		arg.Selector,
		arg.Description,
		arg.IntervalSeconds,
		arg.ProjectID,
		arg.ID,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.ProjectID,
		&i.Name,
		&i.CheckType,
		&i.Target,
		&i.Selector,
		&i.Description,
		&i.IntervalSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePingCheckConfig = `-- name: UpdatePingCheckConfig :one
UPDATE ping_check_configs
SET packet_count = $2,
    packet_size_bytes = $3,
    timeout_ms = $4,
    ip_family = $5
WHERE check_id = $1
RETURNING check_id, packet_count, packet_size_bytes, timeout_ms, ip_family
`

type UpdatePingCheckConfigParams struct {
	CheckID         uuid.UUID `json:"check_id"`
	PacketCount     int32     `json:"packet_count"`
	PacketSizeBytes int32     `json:"packet_size_bytes"`
	TimeoutMs       int32     `json:"timeout_ms"`
	IpFamily        *IpFamily `json:"ip_family"`
}

func (q *Queries) UpdatePingCheckConfig(ctx context.Context, arg UpdatePingCheckConfigParams) (PingCheckConfig, error) {
	row := q.db.QueryRow(ctx, updatePingCheckConfig,
		arg.CheckID,
		arg.PacketCount,
		arg.PacketSizeBytes,
		arg.TimeoutMs,
		arg.IpFamily,
	)
	var i PingCheckConfig
	err := row.Scan(
		&i.CheckID,
		&i.PacketCount,
		&i.PacketSizeBytes,
		&i.TimeoutMs,
		&i.IpFamily,
	)
	return i, err
}

const updateTCPCheckConfig = `-- name: UpdateTCPCheckConfig :one
UPDATE tcp_check_configs
SET port = $2,
    timeout_ms = $3,
    ip_family = $4
WHERE check_id = $1
RETURNING check_id, port, timeout_ms, ip_family
`

type UpdateTCPCheckConfigParams struct {
	CheckID   uuid.UUID `json:"check_id"`
	Port      int32     `json:"port"`
	TimeoutMs int32     `json:"timeout_ms"`
	IpFamily  *IpFamily `json:"ip_family"`
}

func (q *Queries) UpdateTCPCheckConfig(ctx context.Context, arg UpdateTCPCheckConfigParams) (TcpCheckConfig, error) {
	row := q.db.QueryRow(ctx, updateTCPCheckConfig,
		arg.CheckID,
		arg.Port,
		arg.TimeoutMs,
		arg.IpFamily,
	)
	var i TcpCheckConfig
	err := row.Scan(
		&i.CheckID,
		&i.Port,
		&i.TimeoutMs,
		&i.IpFamily,
	)
	return i, err
}

const updateTracerouteCheckConfig = `-- name: UpdateTracerouteCheckConfig :one
UPDATE traceroute_check_configs
SET protocol = $2,
    max_hops = $3,
    timeout_ms = $4,
    queries_per_hop = $5,
    packet_size_bytes = $6,
    port = $7,
    ip_family = $8
WHERE check_id = $1
RETURNING check_id, protocol, max_hops, timeout_ms, queries_per_hop, packet_size_bytes, port, ip_family
`

type UpdateTracerouteCheckConfigParams struct {
	CheckID         uuid.UUID          `json:"check_id"`
	Protocol        TracerouteProtocol `json:"protocol"`
	MaxHops         int32              `json:"max_hops"`
	TimeoutMs       int32              `json:"timeout_ms"`
	QueriesPerHop   int32              `json:"queries_per_hop"`
	PacketSizeBytes int32              `json:"packet_size_bytes"`
	Port            int32              `json:"port"`
	IpFamily        *IpFamily          `json:"ip_family"`
}

func (q *Queries) UpdateTracerouteCheckConfig(ctx context.Context, arg UpdateTracerouteCheckConfigParams) (TracerouteCheckConfig, error) {
	row := q.db.QueryRow(ctx, updateTracerouteCheckConfig,
		arg.CheckID,
		arg.Protocol,
		arg.MaxHops,
		arg.TimeoutMs,
		arg.QueriesPerHop,
		arg.PacketSizeBytes,
		arg.Port,
		arg.IpFamily,
	)
	var i TracerouteCheckConfig
	err := row.Scan(
		&i.CheckID,
		&i.Protocol,
		&i.MaxHops,
		&i.TimeoutMs,
		&i.QueriesPerHop,
		&i.PacketSizeBytes,
		&i.Port,
		&i.IpFamily,
	)
	return i, err
}

const upsertProbeCheckAssignment = `-- name: UpsertProbeCheckAssignment :exec
INSERT INTO probe_check_assignments (project_id, probe_id, check_id, check_version, selector_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, probe_id, check_id) WHERE deleted_at IS NULL
DO UPDATE SET check_version = EXCLUDED.check_version,
              selector_version = EXCLUDED.selector_version
`

type UpsertProbeCheckAssignmentParams struct {
	ProjectID       uuid.UUID `json:"project_id"`
	ProbeID         uuid.UUID `json:"probe_id"`
	CheckID         uuid.UUID `json:"check_id"`
	CheckVersion    string    `json:"check_version"`
	SelectorVersion string    `json:"selector_version"`
}

func (q *Queries) UpsertProbeCheckAssignment(ctx context.Context, arg UpsertProbeCheckAssignmentParams) error {
	_, err := q.db.Exec(ctx, upsertProbeCheckAssignment,
		arg.ProjectID,
		arg.ProbeID,
		arg.CheckID,
		arg.CheckVersion,
		arg.SelectorVersion,
	)
	return err
}
