// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveEmailVerificationTokenByHash = `-- name: GetActiveEmailVerificationTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM email_verification_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > $2
LIMIT 1
`

type GetActiveEmailVerificationTokenByHashParams struct {
	TokenHash string    `json:"token_hash"`
	NowAt     time.Time `json:"now_at"`
}

func (q *Queries) GetActiveEmailVerificationTokenByHash(ctx context.Context, arg GetActiveEmailVerificationTokenByHashParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getActiveEmailVerificationTokenByHash, arg.TokenHash, arg.NowAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateActiveEmailVerificationTokens = `-- name: InvalidateActiveEmailVerificationTokens :exec
UPDATE email_verification_tokens
SET used_at = $1
WHERE user_id = $2
  AND used_at IS NULL
`

type InvalidateActiveEmailVerificationTokensParams struct {
	UsedAt *time.Time `json:"used_at"`
	UserID uuid.UUID  `json:"user_id"`
}

func (q *Queries) InvalidateActiveEmailVerificationTokens(ctx context.Context, arg InvalidateActiveEmailVerificationTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateActiveEmailVerificationTokens, arg.UsedAt, arg.UserID)
	return err
}

const markEmailVerificationTokenUsed = `-- name: MarkEmailVerificationTokenUsed :exec
UPDATE email_verification_tokens
SET used_at = $1
WHERE id = $2
  AND used_at IS NULL
`

type MarkEmailVerificationTokenUsedParams struct {
	UsedAt *time.Time `json:"used_at"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) MarkEmailVerificationTokenUsed(ctx context.Context, arg MarkEmailVerificationTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markEmailVerificationTokenUsed, arg.UsedAt, arg.ID)
	return err
}
