// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (project_id, key, value)
VALUES ($1, $2, $3)
RETURNING id, project_id, key, value, created_at, updated_at, deleted_at
`

type CreateLabelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel, arg.ProjectID, arg.Key, arg.Value)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveLabelForProject = `-- name: GetActiveLabelForProject :one
SELECT id, project_id, key, value, created_at, updated_at, deleted_at
FROM labels
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetActiveLabelForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetActiveLabelForProject(ctx context.Context, arg GetActiveLabelForProjectParams) (Label, error) {
	row := q.db.QueryRow(ctx, getActiveLabelForProject, arg.ProjectID, arg.ID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveLabelsByIDsForProject = `-- name: GetActiveLabelsByIDsForProject :many
WITH requested AS (
    SELECT label_id, position
    FROM unnest($2::uuid[]) WITH ORDINALITY AS requested(label_id, position)
)
SELECT labels.id,
       labels.project_id,
       labels.key,
       labels.value,
       labels.created_at,
       labels.updated_at,
       labels.deleted_at
FROM requested
JOIN labels
    ON labels.project_id = $1
    AND labels.id = requested.label_id
WHERE labels.deleted_at IS NULL
ORDER BY requested.position
`

type GetActiveLabelsByIDsForProjectParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	LabelIds  []uuid.UUID `json:"label_ids"`
}

func (q *Queries) GetActiveLabelsByIDsForProject(ctx context.Context, arg GetActiveLabelsByIDsForProjectParams) ([]Label, error) {
	rows, err := q.db.Query(ctx, getActiveLabelsByIDsForProject, arg.ProjectID, arg.LabelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLabelsForProject = `-- name: ListActiveLabelsForProject :many
SELECT id, project_id, key, value, created_at, updated_at, deleted_at
FROM labels
WHERE project_id = $1
  AND deleted_at IS NULL
ORDER BY key ASC, value ASC, id ASC
`

func (q *Queries) ListActiveLabelsForProject(ctx context.Context, projectID uuid.UUID) ([]Label, error) {
	rows, err := q.db.Query(ctx, listActiveLabelsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLabel = `-- name: SoftDeleteLabel :one
UPDATE labels
SET deleted_at = now()
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteLabelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteLabel(ctx context.Context, arg SoftDeleteLabelParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteLabel, arg.ProjectID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels
SET key = $3,
    value = $4
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id, project_id, key, value, created_at, updated_at, deleted_at
`

type UpdateLabelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabel,
		arg.ProjectID,
		arg.ID,
		arg.Key,
		arg.Value,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
