// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CheckType string

const (
	CheckTypePing       CheckType = "ping"
	CheckTypeTraceroute CheckType = "traceroute"
)

func (e *CheckType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CheckType(s)
	case string:
		*e = CheckType(s)
	default:
		return fmt.Errorf("unsupported scan type for CheckType: %T", src)
	}
	return nil
}

type NullCheckType struct {
	CheckType CheckType `json:"check_type"`
	Valid     bool      `json:"valid"` // Valid is true if CheckType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCheckType) Scan(value interface{}) error {
	if value == nil {
		ns.CheckType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CheckType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCheckType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CheckType), nil
}

type IpFamily string

const (
	IpFamilyInet  IpFamily = "inet"
	IpFamilyInet6 IpFamily = "inet6"
)

func (e *IpFamily) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IpFamily(s)
	case string:
		*e = IpFamily(s)
	default:
		return fmt.Errorf("unsupported scan type for IpFamily: %T", src)
	}
	return nil
}

type NullIpFamily struct {
	IpFamily IpFamily `json:"ip_family"`
	Valid    bool     `json:"valid"` // Valid is true if IpFamily is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIpFamily) Scan(value interface{}) error {
	if value == nil {
		ns.IpFamily, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IpFamily.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIpFamily) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IpFamily), nil
}

type PingStatus string

const (
	PingStatusSuccessful PingStatus = "successful"
	PingStatusTimeout    PingStatus = "timeout"
	PingStatusError      PingStatus = "error"
)

func (e *PingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PingStatus(s)
	case string:
		*e = PingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PingStatus: %T", src)
	}
	return nil
}

type NullPingStatus struct {
	PingStatus PingStatus `json:"ping_status"`
	Valid      bool       `json:"valid"` // Valid is true if PingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PingStatus), nil
}

type ProbeState string

const (
	ProbeStateOnline  ProbeState = "online"
	ProbeStateOffline ProbeState = "offline"
)

func (e *ProbeState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProbeState(s)
	case string:
		*e = ProbeState(s)
	default:
		return fmt.Errorf("unsupported scan type for ProbeState: %T", src)
	}
	return nil
}

type NullProbeState struct {
	ProbeState ProbeState `json:"probe_state"`
	Valid      bool       `json:"valid"` // Valid is true if ProbeState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProbeState) Scan(value interface{}) error {
	if value == nil {
		ns.ProbeState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProbeState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProbeState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProbeState), nil
}

type ProjectMemberRole string

const (
	ProjectMemberRoleOwner  ProjectMemberRole = "owner"
	ProjectMemberRoleAdmin  ProjectMemberRole = "admin"
	ProjectMemberRoleEditor ProjectMemberRole = "editor"
	ProjectMemberRoleViewer ProjectMemberRole = "viewer"
)

func (e *ProjectMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectMemberRole(s)
	case string:
		*e = ProjectMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectMemberRole: %T", src)
	}
	return nil
}

type NullProjectMemberRole struct {
	ProjectMemberRole ProjectMemberRole `json:"project_member_role"`
	Valid             bool              `json:"valid"` // Valid is true if ProjectMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectMemberRole), nil
}

type TracerouteProtocol string

const (
	TracerouteProtocolIcmp TracerouteProtocol = "icmp"
	TracerouteProtocolUdp  TracerouteProtocol = "udp"
)

func (e *TracerouteProtocol) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TracerouteProtocol(s)
	case string:
		*e = TracerouteProtocol(s)
	default:
		return fmt.Errorf("unsupported scan type for TracerouteProtocol: %T", src)
	}
	return nil
}

type NullTracerouteProtocol struct {
	TracerouteProtocol TracerouteProtocol `json:"traceroute_protocol"`
	Valid              bool               `json:"valid"` // Valid is true if TracerouteProtocol is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTracerouteProtocol) Scan(value interface{}) error {
	if value == nil {
		ns.TracerouteProtocol, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TracerouteProtocol.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTracerouteProtocol) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TracerouteProtocol), nil
}

type TracerouteStatus string

const (
	TracerouteStatusSuccessful TracerouteStatus = "successful"
	TracerouteStatusTimeout    TracerouteStatus = "timeout"
	TracerouteStatusError      TracerouteStatus = "error"
	TracerouteStatusPartial    TracerouteStatus = "partial"
)

func (e *TracerouteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TracerouteStatus(s)
	case string:
		*e = TracerouteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TracerouteStatus: %T", src)
	}
	return nil
}

type NullTracerouteStatus struct {
	TracerouteStatus TracerouteStatus `json:"traceroute_status"`
	Valid            bool             `json:"valid"` // Valid is true if TracerouteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTracerouteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TracerouteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TracerouteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTracerouteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TracerouteStatus), nil
}

type Check struct {
	ID              uuid.UUID          `json:"id"`
	InternalID      int64              `json:"internal_id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	Name            string             `json:"name"`
	CheckType       CheckType          `json:"check_type"`
	Target          string             `json:"target"`
	Selector        []byte             `json:"selector"`
	Description     *string            `json:"description"`
	IntervalSeconds int32              `json:"interval_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type CheckLabel struct {
	ProjectID uuid.UUID `json:"project_id"`
	CheckID   uuid.UUID `json:"check_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

type Label struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type PingCheckConfig struct {
	CheckID         uuid.UUID    `json:"check_id"`
	PacketCount     int32        `json:"packet_count"`
	PacketSizeBytes int32        `json:"packet_size_bytes"`
	TimeoutMs       int32        `json:"timeout_ms"`
	IpFamily        NullIpFamily `json:"ip_family"`
}

type PingResult struct {
	ProbeID       int64              `json:"probe_id"`
	CheckID       int64              `json:"check_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	DurationMs    int32              `json:"duration_ms"`
	Status        PingStatus         `json:"status"`
	SentCount     int32              `json:"sent_count"`
	ReceivedCount int32              `json:"received_count"`
	LossPercent   float64            `json:"loss_percent"`
	RttMinMs      *float64           `json:"rtt_min_ms"`
	RttAvgMs      *float64           `json:"rtt_avg_ms"`
	RttMedianMs   *float64           `json:"rtt_median_ms"`
	RttMaxMs      *float64           `json:"rtt_max_ms"`
	RttStddevMs   *float64           `json:"rtt_stddev_ms"`
	RttSamplesMs  []float64          `json:"rtt_samples_ms"`
	ResolvedIp    *netip.Addr        `json:"resolved_ip"`
	IpFamily      NullIpFamily       `json:"ip_family"`
	ErrorCode     *string            `json:"error_code"`
	ErrorMessage  *string            `json:"error_message"`
}

type Probe struct {
	ID              uuid.UUID          `json:"id"`
	InternalID      int64              `json:"internal_id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	Name            string             `json:"name"`
	Enabled         bool               `json:"enabled"`
	Location        pgtype.Point       `json:"location"`
	SubdivisionCode *string            `json:"subdivision_code"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ProbeCheckAssignment struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	ProbeID         uuid.UUID          `json:"probe_id"`
	CheckID         uuid.UUID          `json:"check_id"`
	CheckVersion    string             `json:"check_version"`
	SelectorVersion string             `json:"selector_version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ProbeCredential struct {
	ProbeID       uuid.UUID          `json:"probe_id"`
	SecretHash    string             `json:"secret_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastRotatedAt pgtype.Timestamptz `json:"last_rotated_at"`
}

type ProbeLabel struct {
	ProjectID uuid.UUID `json:"project_id"`
	ProbeID   uuid.UUID `json:"probe_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

type ProbeStatus struct {
	ProbeID      uuid.UUID          `json:"probe_id"`
	Status       ProbeState         `json:"status"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	AgentVersion *string            `json:"agent_version"`
	PublicV4     *netip.Addr        `json:"public_v4"`
	PublicV6     *netip.Addr        `json:"public_v6"`
	As           *string            `json:"as"`
	Addrs        []netip.Addr       `json:"addrs"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Slug            string             `json:"slug"`
	CreatedByUserID uuid.UUID          `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ProjectMember struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      ProjectMemberRole  `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TracerouteCheckConfig struct {
	CheckID         uuid.UUID          `json:"check_id"`
	Protocol        TracerouteProtocol `json:"protocol"`
	MaxHops         int32              `json:"max_hops"`
	TimeoutMs       int32              `json:"timeout_ms"`
	QueriesPerHop   int32              `json:"queries_per_hop"`
	PacketSizeBytes int32              `json:"packet_size_bytes"`
	Port            int32              `json:"port"`
	IpFamily        NullIpFamily       `json:"ip_family"`
}

type TracerouteResult struct {
	ProbeID            int64              `json:"probe_id"`
	CheckID            int64              `json:"check_id"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	FinishedAt         pgtype.Timestamptz `json:"finished_at"`
	DurationMs         int32              `json:"duration_ms"`
	Status             TracerouteStatus   `json:"status"`
	ResolvedIp         *netip.Addr        `json:"resolved_ip"`
	IpFamily           NullIpFamily       `json:"ip_family"`
	DestinationReached bool               `json:"destination_reached"`
	HopCount           int32              `json:"hop_count"`
	ErrorCode          *string            `json:"error_code"`
	ErrorMessage       *string            `json:"error_message"`
}

type TracerouteResultHop struct {
	ProbeID       int64              `json:"probe_id"`
	CheckID       int64              `json:"check_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	HopIndex      int32              `json:"hop_index"`
	Address       *netip.Addr        `json:"address"`
	Hostname      *string            `json:"hostname"`
	SentCount     int32              `json:"sent_count"`
	ReceivedCount int32              `json:"received_count"`
	LossPercent   float64            `json:"loss_percent"`
	RttMinMs      *float64           `json:"rtt_min_ms"`
	RttAvgMs      *float64           `json:"rtt_avg_ms"`
	RttMedianMs   *float64           `json:"rtt_median_ms"`
	RttMaxMs      *float64           `json:"rtt_max_ms"`
	RttStddevMs   *float64           `json:"rtt_stddev_ms"`
	RttSamplesMs  []float64          `json:"rtt_samples_ms"`
	ErrorCode     *string            `json:"error_code"`
	ErrorMessage  *string            `json:"error_message"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
