// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: probes.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProbe = `-- name: CreateProbe :one
INSERT INTO probes (project_id, name, enabled, location, location_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, internal_id, project_id, name, enabled, location, location_name, created_at, updated_at, deleted_at
`

type CreateProbeParams struct {
	ProjectID    uuid.UUID    `json:"project_id"`
	Name         string       `json:"name"`
	Enabled      bool         `json:"enabled"`
	Location     pgtype.Point `json:"location"`
	LocationName *string      `json:"location_name"`
}

type CreateProbeRow struct {
	ID           uuid.UUID    `json:"id"`
	InternalID   int64        `json:"internal_id"`
	ProjectID    uuid.UUID    `json:"project_id"`
	Name         string       `json:"name"`
	Enabled      bool         `json:"enabled"`
	Location     pgtype.Point `json:"location"`
	LocationName *string      `json:"location_name"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    *time.Time   `json:"deleted_at"`
}

func (q *Queries) CreateProbe(ctx context.Context, arg CreateProbeParams) (CreateProbeRow, error) {
	row := q.db.QueryRow(ctx, createProbe,
		arg.ProjectID,
		arg.Name,
		arg.Enabled,
		arg.Location,
		arg.LocationName,
	)
	var i CreateProbeRow
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.Location,
		&i.LocationName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProbeCredential = `-- name: CreateProbeCredential :one
INSERT INTO probe_credentials (probe_id, secret_hash)
VALUES ($1, $2)
RETURNING probe_id, secret_hash, created_at, last_rotated_at
`

type CreateProbeCredentialParams struct {
	ProbeID    uuid.UUID `json:"probe_id"`
	SecretHash string    `json:"secret_hash"`
}

func (q *Queries) CreateProbeCredential(ctx context.Context, arg CreateProbeCredentialParams) (ProbeCredential, error) {
	row := q.db.QueryRow(ctx, createProbeCredential, arg.ProbeID, arg.SecretHash)
	var i ProbeCredential
	err := row.Scan(
		&i.ProbeID,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastRotatedAt,
	)
	return i, err
}

const createProbeLabel = `-- name: CreateProbeLabel :exec
INSERT INTO probe_labels (project_id, probe_id, label_id)
VALUES ($1, $2, $3)
`

type CreateProbeLabelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ProbeID   uuid.UUID `json:"probe_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

func (q *Queries) CreateProbeLabel(ctx context.Context, arg CreateProbeLabelParams) error {
	_, err := q.db.Exec(ctx, createProbeLabel, arg.ProjectID, arg.ProbeID, arg.LabelID)
	return err
}

const createProbeStatus = `-- name: CreateProbeStatus :one
INSERT INTO probe_statuses (probe_id, status)
VALUES ($1, $2)
RETURNING probe_id, status, last_seen_at, agent_version, public_v4, public_v6, "as", addrs, updated_at
`

type CreateProbeStatusParams struct {
	ProbeID uuid.UUID  `json:"probe_id"`
	Status  ProbeState `json:"status"`
}

func (q *Queries) CreateProbeStatus(ctx context.Context, arg CreateProbeStatusParams) (ProbeStatus, error) {
	row := q.db.QueryRow(ctx, createProbeStatus, arg.ProbeID, arg.Status)
	var i ProbeStatus
	err := row.Scan(
		&i.ProbeID,
		&i.Status,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.PublicV4,
		&i.PublicV6,
		&i.As,
		&i.Addrs,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProbeCheckAssignmentsForProbe = `-- name: DeleteProbeCheckAssignmentsForProbe :exec
DELETE FROM probe_check_assignments
WHERE project_id = $1
  AND probe_id = $2
`

type DeleteProbeCheckAssignmentsForProbeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ProbeID   uuid.UUID `json:"probe_id"`
}

func (q *Queries) DeleteProbeCheckAssignmentsForProbe(ctx context.Context, arg DeleteProbeCheckAssignmentsForProbeParams) error {
	_, err := q.db.Exec(ctx, deleteProbeCheckAssignmentsForProbe, arg.ProjectID, arg.ProbeID)
	return err
}

const deleteProbeLabels = `-- name: DeleteProbeLabels :exec
DELETE FROM probe_labels
WHERE project_id = $1
  AND probe_id = $2
`

type DeleteProbeLabelsParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ProbeID   uuid.UUID `json:"probe_id"`
}

func (q *Queries) DeleteProbeLabels(ctx context.Context, arg DeleteProbeLabelsParams) error {
	_, err := q.db.Exec(ctx, deleteProbeLabels, arg.ProjectID, arg.ProbeID)
	return err
}

const deleteStaleProbeCheckAssignmentsForProbe = `-- name: DeleteStaleProbeCheckAssignmentsForProbe :exec
DELETE FROM probe_check_assignments
WHERE project_id = $1
  AND probe_id = $2
  AND deleted_at IS NULL
  AND check_id <> ALL($3::uuid[])
`

type DeleteStaleProbeCheckAssignmentsForProbeParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	ProbeID   uuid.UUID   `json:"probe_id"`
	CheckIds  []uuid.UUID `json:"check_ids"`
}

func (q *Queries) DeleteStaleProbeCheckAssignmentsForProbe(ctx context.Context, arg DeleteStaleProbeCheckAssignmentsForProbeParams) error {
	_, err := q.db.Exec(ctx, deleteStaleProbeCheckAssignmentsForProbe, arg.ProjectID, arg.ProbeID, arg.CheckIds)
	return err
}

const getActiveProbeCredential = `-- name: GetActiveProbeCredential :one
SELECT probes.id,
       probes.project_id,
       probes.internal_id AS probe_internal_id,
       probes.enabled,
       probe_credentials.secret_hash
FROM probes
JOIN probe_credentials ON probe_credentials.probe_id = probes.id
WHERE probes.id = $1
  AND probes.deleted_at IS NULL
`

type GetActiveProbeCredentialRow struct {
	ID              uuid.UUID `json:"id"`
	ProjectID       uuid.UUID `json:"project_id"`
	ProbeInternalID int64     `json:"probe_internal_id"`
	Enabled         bool      `json:"enabled"`
	SecretHash      string    `json:"secret_hash"`
}

func (q *Queries) GetActiveProbeCredential(ctx context.Context, id uuid.UUID) (GetActiveProbeCredentialRow, error) {
	row := q.db.QueryRow(ctx, getActiveProbeCredential, id)
	var i GetActiveProbeCredentialRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ProbeInternalID,
		&i.Enabled,
		&i.SecretHash,
	)
	return i, err
}

const getActiveProbeRowsForProject = `-- name: GetActiveProbeRowsForProject :many
SELECT probes.internal_id,
       probes.id,
       probes.project_id,
       probes.name,
       probes.enabled,
       probes.location,
       probes.location_name,
       probes.created_at,
       probes.updated_at,
       probes.deleted_at,
       (CASE
           WHEN probe_statuses.last_seen_at IS NULL THEN 'offline'::probe_state
           WHEN probe_statuses.last_seen_at < now() - interval '35 seconds' THEN 'offline'::probe_state
           ELSE probe_statuses.status
       END)::probe_state AS status,
       probe_statuses.last_seen_at AS status_last_seen_at,
       probe_statuses.agent_version AS status_agent_version,
       probe_statuses.public_v4 AS status_public_v4,
       probe_statuses.public_v6 AS status_public_v6,
       probe_statuses."as" AS status_as,
       probe_statuses.addrs AS status_addrs,
       probe_statuses.updated_at AS status_updated_at,
       labels.id AS label_id,
       labels.project_id AS label_project_id,
       labels.key AS label_key,
       labels.value AS label_value,
       labels.created_at AS label_created_at,
       labels.updated_at AS label_updated_at,
       labels.deleted_at AS label_deleted_at
FROM probes
LEFT JOIN probe_statuses ON probe_statuses.probe_id = probes.id
LEFT JOIN probe_labels
    ON probe_labels.project_id = probes.project_id
    AND probe_labels.probe_id = probes.id
LEFT JOIN labels
    ON labels.project_id = probe_labels.project_id
    AND labels.id = probe_labels.label_id
    AND labels.deleted_at IS NULL
WHERE probes.project_id = $1
  AND probes.id = $2
  AND probes.deleted_at IS NULL
ORDER BY labels.key ASC NULLS LAST,
         labels.value ASC NULLS LAST,
         labels.id ASC NULLS LAST
`

type GetActiveProbeRowsForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

type GetActiveProbeRowsForProjectRow struct {
	InternalID         int64        `json:"internal_id"`
	ID                 uuid.UUID    `json:"id"`
	ProjectID          uuid.UUID    `json:"project_id"`
	Name               string       `json:"name"`
	Enabled            bool         `json:"enabled"`
	Location           pgtype.Point `json:"location"`
	LocationName       *string      `json:"location_name"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	DeletedAt          *time.Time   `json:"deleted_at"`
	Status             ProbeState   `json:"status"`
	StatusLastSeenAt   *time.Time   `json:"status_last_seen_at"`
	StatusAgentVersion *string      `json:"status_agent_version"`
	StatusPublicV4     *netip.Addr  `json:"status_public_v4"`
	StatusPublicV6     *netip.Addr  `json:"status_public_v6"`
	StatusAs           *string      `json:"status_as"`
	StatusAddrs        []netip.Addr `json:"status_addrs"`
	StatusUpdatedAt    *time.Time   `json:"status_updated_at"`
	LabelID            *uuid.UUID   `json:"label_id"`
	LabelProjectID     *uuid.UUID   `json:"label_project_id"`
	LabelKey           *string      `json:"label_key"`
	LabelValue         *string      `json:"label_value"`
	LabelCreatedAt     *time.Time   `json:"label_created_at"`
	LabelUpdatedAt     *time.Time   `json:"label_updated_at"`
	LabelDeletedAt     *time.Time   `json:"label_deleted_at"`
}

func (q *Queries) GetActiveProbeRowsForProject(ctx context.Context, arg GetActiveProbeRowsForProjectParams) ([]GetActiveProbeRowsForProjectRow, error) {
	rows, err := q.db.Query(ctx, getActiveProbeRowsForProject, arg.ProjectID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveProbeRowsForProjectRow
	for rows.Next() {
		var i GetActiveProbeRowsForProjectRow
		if err := rows.Scan(
			&i.InternalID,
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Enabled,
			&i.Location,
			&i.LocationName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Status,
			&i.StatusLastSeenAt,
			&i.StatusAgentVersion,
			&i.StatusPublicV4,
			&i.StatusPublicV6,
			&i.StatusAs,
			&i.StatusAddrs,
			&i.StatusUpdatedAt,
			&i.LabelID,
			&i.LabelProjectID,
			&i.LabelKey,
			&i.LabelValue,
			&i.LabelCreatedAt,
			&i.LabelUpdatedAt,
			&i.LabelDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAssignmentsForProbe = `-- name: ListActiveAssignmentsForProbe :many
SELECT probe_check_assignments.id AS assignment_id,
       probe_check_assignments.project_id,
       probe_check_assignments.probe_id,
       probe_check_assignments.check_id,
       probes.internal_id AS probe_internal_id,
       checks.internal_id AS check_internal_id,
       probe_check_assignments.check_version,
       probe_check_assignments.selector_version,
       checks.check_type,
       checks.target,
       checks.interval_seconds,
       ping_check_configs.packet_count AS ping_packet_count,
       ping_check_configs.packet_size_bytes AS ping_packet_size_bytes,
       ping_check_configs.timeout_ms AS ping_timeout_ms,
       ping_check_configs.ip_family AS ping_ip_family,
       tcp_check_configs.port AS tcp_port,
       tcp_check_configs.timeout_ms AS tcp_timeout_ms,
       tcp_check_configs.ip_family AS tcp_ip_family,
       traceroute_check_configs.protocol AS traceroute_protocol,
       traceroute_check_configs.max_hops AS traceroute_max_hops,
       traceroute_check_configs.timeout_ms AS traceroute_timeout_ms,
       traceroute_check_configs.queries_per_hop AS traceroute_queries_per_hop,
       traceroute_check_configs.packet_size_bytes AS traceroute_packet_size_bytes,
       traceroute_check_configs.port AS traceroute_port,
       traceroute_check_configs.ip_family AS traceroute_ip_family
FROM probe_check_assignments
JOIN probes
    ON probes.project_id = probe_check_assignments.project_id
    AND probes.id = probe_check_assignments.probe_id
JOIN checks
    ON checks.project_id = probe_check_assignments.project_id
    AND checks.id = probe_check_assignments.check_id
LEFT JOIN ping_check_configs ON ping_check_configs.check_id = checks.id
LEFT JOIN tcp_check_configs ON tcp_check_configs.check_id = checks.id
LEFT JOIN traceroute_check_configs ON traceroute_check_configs.check_id = checks.id
WHERE probe_check_assignments.probe_id = $1
  AND probe_check_assignments.deleted_at IS NULL
  AND probes.enabled = true
  AND probes.deleted_at IS NULL
  AND checks.deleted_at IS NULL
ORDER BY checks.created_at ASC,
         checks.id ASC
`

type ListActiveAssignmentsForProbeRow struct {
	AssignmentID              uuid.UUID           `json:"assignment_id"`
	ProjectID                 uuid.UUID           `json:"project_id"`
	ProbeID                   uuid.UUID           `json:"probe_id"`
	CheckID                   uuid.UUID           `json:"check_id"`
	ProbeInternalID           int64               `json:"probe_internal_id"`
	CheckInternalID           int64               `json:"check_internal_id"`
	CheckVersion              string              `json:"check_version"`
	SelectorVersion           string              `json:"selector_version"`
	CheckType                 CheckType           `json:"check_type"`
	Target                    string              `json:"target"`
	IntervalSeconds           int32               `json:"interval_seconds"`
	PingPacketCount           *int32              `json:"ping_packet_count"`
	PingPacketSizeBytes       *int32              `json:"ping_packet_size_bytes"`
	PingTimeoutMs             *int32              `json:"ping_timeout_ms"`
	PingIpFamily              *IpFamily           `json:"ping_ip_family"`
	TcpPort                   *int32              `json:"tcp_port"`
	TcpTimeoutMs              *int32              `json:"tcp_timeout_ms"`
	TcpIpFamily               *IpFamily           `json:"tcp_ip_family"`
	TracerouteProtocol        *TracerouteProtocol `json:"traceroute_protocol"`
	TracerouteMaxHops         *int32              `json:"traceroute_max_hops"`
	TracerouteTimeoutMs       *int32              `json:"traceroute_timeout_ms"`
	TracerouteQueriesPerHop   *int32              `json:"traceroute_queries_per_hop"`
	TraceroutePacketSizeBytes *int32              `json:"traceroute_packet_size_bytes"`
	TraceroutePort            *int32              `json:"traceroute_port"`
	TracerouteIpFamily        *IpFamily           `json:"traceroute_ip_family"`
}

func (q *Queries) ListActiveAssignmentsForProbe(ctx context.Context, probeID uuid.UUID) ([]ListActiveAssignmentsForProbeRow, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentsForProbe, probeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAssignmentsForProbeRow
	for rows.Next() {
		var i ListActiveAssignmentsForProbeRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.ProjectID,
			&i.ProbeID,
			&i.CheckID,
			&i.ProbeInternalID,
			&i.CheckInternalID,
			&i.CheckVersion,
			&i.SelectorVersion,
			&i.CheckType,
			&i.Target,
			&i.IntervalSeconds,
			&i.PingPacketCount,
			&i.PingPacketSizeBytes,
			&i.PingTimeoutMs,
			&i.PingIpFamily,
			&i.TcpPort,
			&i.TcpTimeoutMs,
			&i.TcpIpFamily,
			&i.TracerouteProtocol,
			&i.TracerouteMaxHops,
			&i.TracerouteTimeoutMs,
			&i.TracerouteQueriesPerHop,
			&i.TraceroutePacketSizeBytes,
			&i.TraceroutePort,
			&i.TracerouteIpFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAssignmentsForProbeChecks = `-- name: ListActiveAssignmentsForProbeChecks :many
SELECT probe_check_assignments.id AS assignment_id,
       probe_check_assignments.project_id,
       probe_check_assignments.probe_id,
       probe_check_assignments.check_id,
       probes.internal_id AS probe_internal_id,
       checks.internal_id AS check_internal_id,
       probe_check_assignments.check_version,
       probe_check_assignments.selector_version,
       checks.check_type,
       checks.target,
       checks.interval_seconds,
       ping_check_configs.packet_count AS ping_packet_count,
       ping_check_configs.packet_size_bytes AS ping_packet_size_bytes,
       ping_check_configs.timeout_ms AS ping_timeout_ms,
       ping_check_configs.ip_family AS ping_ip_family,
       tcp_check_configs.port AS tcp_port,
       tcp_check_configs.timeout_ms AS tcp_timeout_ms,
       tcp_check_configs.ip_family AS tcp_ip_family,
       traceroute_check_configs.protocol AS traceroute_protocol,
       traceroute_check_configs.max_hops AS traceroute_max_hops,
       traceroute_check_configs.timeout_ms AS traceroute_timeout_ms,
       traceroute_check_configs.queries_per_hop AS traceroute_queries_per_hop,
       traceroute_check_configs.packet_size_bytes AS traceroute_packet_size_bytes,
       traceroute_check_configs.port AS traceroute_port,
       traceroute_check_configs.ip_family AS traceroute_ip_family
FROM probe_check_assignments
JOIN probes
    ON probes.project_id = probe_check_assignments.project_id
    AND probes.id = probe_check_assignments.probe_id
JOIN checks
    ON checks.project_id = probe_check_assignments.project_id
    AND checks.id = probe_check_assignments.check_id
LEFT JOIN ping_check_configs ON ping_check_configs.check_id = checks.id
LEFT JOIN tcp_check_configs ON tcp_check_configs.check_id = checks.id
LEFT JOIN traceroute_check_configs ON traceroute_check_configs.check_id = checks.id
WHERE probe_check_assignments.probe_id = $1
  AND probe_check_assignments.check_id = ANY($2::uuid[])
  AND probe_check_assignments.deleted_at IS NULL
  AND probes.enabled = true
  AND probes.deleted_at IS NULL
  AND checks.deleted_at IS NULL
ORDER BY checks.created_at ASC,
         checks.id ASC
`

type ListActiveAssignmentsForProbeChecksParams struct {
	ProbeID  uuid.UUID   `json:"probe_id"`
	CheckIds []uuid.UUID `json:"check_ids"`
}

type ListActiveAssignmentsForProbeChecksRow struct {
	AssignmentID              uuid.UUID           `json:"assignment_id"`
	ProjectID                 uuid.UUID           `json:"project_id"`
	ProbeID                   uuid.UUID           `json:"probe_id"`
	CheckID                   uuid.UUID           `json:"check_id"`
	ProbeInternalID           int64               `json:"probe_internal_id"`
	CheckInternalID           int64               `json:"check_internal_id"`
	CheckVersion              string              `json:"check_version"`
	SelectorVersion           string              `json:"selector_version"`
	CheckType                 CheckType           `json:"check_type"`
	Target                    string              `json:"target"`
	IntervalSeconds           int32               `json:"interval_seconds"`
	PingPacketCount           *int32              `json:"ping_packet_count"`
	PingPacketSizeBytes       *int32              `json:"ping_packet_size_bytes"`
	PingTimeoutMs             *int32              `json:"ping_timeout_ms"`
	PingIpFamily              *IpFamily           `json:"ping_ip_family"`
	TcpPort                   *int32              `json:"tcp_port"`
	TcpTimeoutMs              *int32              `json:"tcp_timeout_ms"`
	TcpIpFamily               *IpFamily           `json:"tcp_ip_family"`
	TracerouteProtocol        *TracerouteProtocol `json:"traceroute_protocol"`
	TracerouteMaxHops         *int32              `json:"traceroute_max_hops"`
	TracerouteTimeoutMs       *int32              `json:"traceroute_timeout_ms"`
	TracerouteQueriesPerHop   *int32              `json:"traceroute_queries_per_hop"`
	TraceroutePacketSizeBytes *int32              `json:"traceroute_packet_size_bytes"`
	TraceroutePort            *int32              `json:"traceroute_port"`
	TracerouteIpFamily        *IpFamily           `json:"traceroute_ip_family"`
}

func (q *Queries) ListActiveAssignmentsForProbeChecks(ctx context.Context, arg ListActiveAssignmentsForProbeChecksParams) ([]ListActiveAssignmentsForProbeChecksRow, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentsForProbeChecks, arg.ProbeID, arg.CheckIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAssignmentsForProbeChecksRow
	for rows.Next() {
		var i ListActiveAssignmentsForProbeChecksRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.ProjectID,
			&i.ProbeID,
			&i.CheckID,
			&i.ProbeInternalID,
			&i.CheckInternalID,
			&i.CheckVersion,
			&i.SelectorVersion,
			&i.CheckType,
			&i.Target,
			&i.IntervalSeconds,
			&i.PingPacketCount,
			&i.PingPacketSizeBytes,
			&i.PingTimeoutMs,
			&i.PingIpFamily,
			&i.TcpPort,
			&i.TcpTimeoutMs,
			&i.TcpIpFamily,
			&i.TracerouteProtocol,
			&i.TracerouteMaxHops,
			&i.TracerouteTimeoutMs,
			&i.TracerouteQueriesPerHop,
			&i.TraceroutePacketSizeBytes,
			&i.TraceroutePort,
			&i.TracerouteIpFamily,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLabelsForProbe = `-- name: ListActiveLabelsForProbe :many
SELECT labels.id,
       labels.project_id,
       labels.key,
       labels.value,
       labels.created_at,
       labels.updated_at,
       labels.deleted_at
FROM probe_labels
JOIN labels
    ON labels.project_id = probe_labels.project_id
    AND labels.id = probe_labels.label_id
WHERE probe_labels.project_id = $1
  AND probe_labels.probe_id = $2
  AND labels.deleted_at IS NULL
ORDER BY labels.key ASC, labels.value ASC, labels.id ASC
`

type ListActiveLabelsForProbeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ProbeID   uuid.UUID `json:"probe_id"`
}

func (q *Queries) ListActiveLabelsForProbe(ctx context.Context, arg ListActiveLabelsForProbeParams) ([]Label, error) {
	rows, err := q.db.Query(ctx, listActiveLabelsForProbe, arg.ProjectID, arg.ProbeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProbesForProject = `-- name: ListActiveProbesForProject :many
SELECT probes.internal_id,
       probes.id,
       probes.project_id,
       probes.name,
       probes.enabled,
       probes.location,
       probes.location_name,
       probes.created_at,
       probes.updated_at,
       probes.deleted_at,
       (CASE
           WHEN probe_statuses.last_seen_at IS NULL THEN 'offline'::probe_state
           WHEN probe_statuses.last_seen_at < now() - interval '35 seconds' THEN 'offline'::probe_state
           ELSE probe_statuses.status
       END)::probe_state AS status,
       probe_statuses.last_seen_at AS status_last_seen_at,
       probe_statuses.agent_version AS status_agent_version,
       probe_statuses.public_v4 AS status_public_v4,
       probe_statuses.public_v6 AS status_public_v6,
       probe_statuses."as" AS status_as,
       probe_statuses.addrs AS status_addrs,
       probe_statuses.updated_at AS status_updated_at,
       labels.id AS label_id,
       labels.project_id AS label_project_id,
       labels.key AS label_key,
       labels.value AS label_value,
       labels.created_at AS label_created_at,
       labels.updated_at AS label_updated_at,
       labels.deleted_at AS label_deleted_at
FROM probes
LEFT JOIN probe_statuses ON probe_statuses.probe_id = probes.id
LEFT JOIN probe_labels
    ON probe_labels.project_id = probes.project_id
    AND probe_labels.probe_id = probes.id
LEFT JOIN labels
    ON labels.project_id = probe_labels.project_id
    AND labels.id = probe_labels.label_id
    AND labels.deleted_at IS NULL
WHERE probes.project_id = $1
  AND probes.deleted_at IS NULL
ORDER BY probes.created_at DESC,
         probes.id DESC,
         labels.key ASC NULLS LAST,
         labels.value ASC NULLS LAST,
         labels.id ASC NULLS LAST
`

type ListActiveProbesForProjectRow struct {
	InternalID         int64        `json:"internal_id"`
	ID                 uuid.UUID    `json:"id"`
	ProjectID          uuid.UUID    `json:"project_id"`
	Name               string       `json:"name"`
	Enabled            bool         `json:"enabled"`
	Location           pgtype.Point `json:"location"`
	LocationName       *string      `json:"location_name"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	DeletedAt          *time.Time   `json:"deleted_at"`
	Status             ProbeState   `json:"status"`
	StatusLastSeenAt   *time.Time   `json:"status_last_seen_at"`
	StatusAgentVersion *string      `json:"status_agent_version"`
	StatusPublicV4     *netip.Addr  `json:"status_public_v4"`
	StatusPublicV6     *netip.Addr  `json:"status_public_v6"`
	StatusAs           *string      `json:"status_as"`
	StatusAddrs        []netip.Addr `json:"status_addrs"`
	StatusUpdatedAt    *time.Time   `json:"status_updated_at"`
	LabelID            *uuid.UUID   `json:"label_id"`
	LabelProjectID     *uuid.UUID   `json:"label_project_id"`
	LabelKey           *string      `json:"label_key"`
	LabelValue         *string      `json:"label_value"`
	LabelCreatedAt     *time.Time   `json:"label_created_at"`
	LabelUpdatedAt     *time.Time   `json:"label_updated_at"`
	LabelDeletedAt     *time.Time   `json:"label_deleted_at"`
}

func (q *Queries) ListActiveProbesForProject(ctx context.Context, projectID uuid.UUID) ([]ListActiveProbesForProjectRow, error) {
	rows, err := q.db.Query(ctx, listActiveProbesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProbesForProjectRow
	for rows.Next() {
		var i ListActiveProbesForProjectRow
		if err := rows.Scan(
			&i.InternalID,
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Enabled,
			&i.Location,
			&i.LocationName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Status,
			&i.StatusLastSeenAt,
			&i.StatusAgentVersion,
			&i.StatusPublicV4,
			&i.StatusPublicV6,
			&i.StatusAs,
			&i.StatusAddrs,
			&i.StatusUpdatedAt,
			&i.LabelID,
			&i.LabelProjectID,
			&i.LabelKey,
			&i.LabelValue,
			&i.LabelCreatedAt,
			&i.LabelUpdatedAt,
			&i.LabelDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProbeRefreshTargetsForLabel = `-- name: ListProbeRefreshTargetsForLabel :many
SELECT probes.id, probes.enabled
FROM probe_labels
JOIN probes
    ON probes.project_id = probe_labels.project_id
    AND probes.id = probe_labels.probe_id
WHERE probe_labels.project_id = $1
  AND probe_labels.label_id = $2
  AND probes.deleted_at IS NULL
ORDER BY probes.id
`

type ListProbeRefreshTargetsForLabelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

type ListProbeRefreshTargetsForLabelRow struct {
	ID      uuid.UUID `json:"id"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) ListProbeRefreshTargetsForLabel(ctx context.Context, arg ListProbeRefreshTargetsForLabelParams) ([]ListProbeRefreshTargetsForLabelRow, error) {
	rows, err := q.db.Query(ctx, listProbeRefreshTargetsForLabel, arg.ProjectID, arg.LabelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProbeRefreshTargetsForLabelRow
	for rows.Next() {
		var i ListProbeRefreshTargetsForLabelRow
		if err := rows.Scan(&i.ID, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateProbeCredential = `-- name: RotateProbeCredential :one
UPDATE probe_credentials
SET secret_hash = $3,
    last_rotated_at = now()
FROM probes
WHERE probe_credentials.probe_id = probes.id
  AND probes.project_id = $1
  AND probes.id = $2
  AND probes.deleted_at IS NULL
RETURNING probe_credentials.probe_id
`

type RotateProbeCredentialParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	ID         uuid.UUID `json:"id"`
	SecretHash string    `json:"secret_hash"`
}

func (q *Queries) RotateProbeCredential(ctx context.Context, arg RotateProbeCredentialParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, rotateProbeCredential, arg.ProjectID, arg.ID, arg.SecretHash)
	var probe_id uuid.UUID
	err := row.Scan(&probe_id)
	return probe_id, err
}

const softDeleteProbe = `-- name: SoftDeleteProbe :one
UPDATE probes
SET deleted_at = now()
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteProbeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeleteProbe(ctx context.Context, arg SoftDeleteProbeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteProbe, arg.ProjectID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateProbe = `-- name: UpdateProbe :one
UPDATE probes
SET name = $3,
    enabled = $4,
    location = $5,
    location_name = $6
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id, internal_id, project_id, name, enabled, location, location_name, created_at, updated_at, deleted_at
`

type UpdateProbeParams struct {
	ProjectID    uuid.UUID    `json:"project_id"`
	ID           uuid.UUID    `json:"id"`
	Name         string       `json:"name"`
	Enabled      bool         `json:"enabled"`
	Location     pgtype.Point `json:"location"`
	LocationName *string      `json:"location_name"`
}

type UpdateProbeRow struct {
	ID           uuid.UUID    `json:"id"`
	InternalID   int64        `json:"internal_id"`
	ProjectID    uuid.UUID    `json:"project_id"`
	Name         string       `json:"name"`
	Enabled      bool         `json:"enabled"`
	Location     pgtype.Point `json:"location"`
	LocationName *string      `json:"location_name"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
	DeletedAt    *time.Time   `json:"deleted_at"`
}

func (q *Queries) UpdateProbe(ctx context.Context, arg UpdateProbeParams) (UpdateProbeRow, error) {
	row := q.db.QueryRow(ctx, updateProbe,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Location,
		arg.LocationName,
	)
	var i UpdateProbeRow
	err := row.Scan(
		&i.ID,
		&i.InternalID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.Location,
		&i.LocationName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProbeIPFamilyCapabilities = `-- name: UpdateProbeIPFamilyCapabilities :one
UPDATE probe_statuses
SET public_v4 = CASE WHEN $1::boolean THEN $2::inet ELSE public_v4 END,
    public_v6 = CASE WHEN $3::boolean THEN $4::inet ELSE public_v6 END,
    updated_at = now()
WHERE probe_id = $5
RETURNING probe_id, status, last_seen_at, agent_version, public_v4, public_v6, "as", addrs, updated_at
`

type UpdateProbeIPFamilyCapabilitiesParams struct {
	UpdateV4 bool        `json:"update_v4"`
	PublicV4 *netip.Addr `json:"public_v4"`
	UpdateV6 bool        `json:"update_v6"`
	PublicV6 *netip.Addr `json:"public_v6"`
	ProbeID  uuid.UUID   `json:"probe_id"`
}

func (q *Queries) UpdateProbeIPFamilyCapabilities(ctx context.Context, arg UpdateProbeIPFamilyCapabilitiesParams) (ProbeStatus, error) {
	row := q.db.QueryRow(ctx, updateProbeIPFamilyCapabilities,
		arg.UpdateV4,
		arg.PublicV4,
		arg.UpdateV6,
		arg.PublicV6,
		arg.ProbeID,
	)
	var i ProbeStatus
	err := row.Scan(
		&i.ProbeID,
		&i.Status,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.PublicV4,
		&i.PublicV6,
		&i.As,
		&i.Addrs,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProbeStatus = `-- name: UpdateProbeStatus :one
UPDATE probe_statuses
SET status = $2,
    last_seen_at = now(),
    agent_version = $3,
    addrs = $4,
    updated_at = now()
WHERE probe_id = $1
RETURNING probe_id, status, last_seen_at, agent_version, public_v4, public_v6, "as", addrs, updated_at
`

type UpdateProbeStatusParams struct {
	ProbeID      uuid.UUID    `json:"probe_id"`
	Status       ProbeState   `json:"status"`
	AgentVersion *string      `json:"agent_version"`
	Addrs        []netip.Addr `json:"addrs"`
}

func (q *Queries) UpdateProbeStatus(ctx context.Context, arg UpdateProbeStatusParams) (ProbeStatus, error) {
	row := q.db.QueryRow(ctx, updateProbeStatus,
		arg.ProbeID,
		arg.Status,
		arg.AgentVersion,
		arg.Addrs,
	)
	var i ProbeStatus
	err := row.Scan(
		&i.ProbeID,
		&i.Status,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.PublicV4,
		&i.PublicV6,
		&i.As,
		&i.Addrs,
		&i.UpdatedAt,
	)
	return i, err
}
