// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveProjectOwners = `-- name: CountActiveProjectOwners :one
SELECT count(*)::int4
FROM project_members
JOIN users ON users.id = project_members.user_id
WHERE project_id = $1
  AND role = 'owner'
  AND users.disabled_at IS NULL
`

func (q *Queries) CountActiveProjectOwners(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveProjectOwners, projectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, slug, created_by_user_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	Name            string    `json:"name"`
	Slug            string    `json:"slug"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.Slug, arg.CreatedByUserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProjectMember = `-- name: CreateProjectMember :one
WITH inserted AS (
    INSERT INTO project_members (project_id, user_id, role)
    VALUES ($1, $2, $3)
    RETURNING id, project_id, user_id, role, created_at, updated_at
)
SELECT inserted.id,
       inserted.project_id,
       inserted.user_id,
       inserted.role,
       inserted.created_at,
       inserted.updated_at,
       users.email AS user_email,
       users.display_name AS user_display_name
FROM inserted
JOIN users ON users.id = inserted.user_id
`

type CreateProjectMemberParams struct {
	ProjectID uuid.UUID         `json:"project_id"`
	UserID    uuid.UUID         `json:"user_id"`
	Role      ProjectMemberRole `json:"role"`
}

type CreateProjectMemberRow struct {
	ID              uuid.UUID         `json:"id"`
	ProjectID       uuid.UUID         `json:"project_id"`
	UserID          uuid.UUID         `json:"user_id"`
	Role            ProjectMemberRole `json:"role"`
	CreatedAt       time.Time         `json:"created_at"`
	UpdatedAt       time.Time         `json:"updated_at"`
	UserEmail       string            `json:"user_email"`
	UserDisplayName string            `json:"user_display_name"`
}

func (q *Queries) CreateProjectMember(ctx context.Context, arg CreateProjectMemberParams) (CreateProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, createProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i CreateProjectMemberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserEmail,
		&i.UserDisplayName,
	)
	return i, err
}

const deleteProjectMember = `-- name: DeleteProjectMember :one
DELETE FROM project_members
WHERE project_id = $1
  AND user_id = $2
RETURNING id
`

type DeleteProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProjectMember, arg.ProjectID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveProjectMember = `-- name: GetActiveProjectMember :one
SELECT project_members.id,
       project_members.project_id,
       project_members.user_id,
       project_members.role,
       project_members.created_at,
       project_members.updated_at,
       users.email AS user_email,
       users.display_name AS user_display_name
FROM project_members
JOIN projects ON projects.id = project_members.project_id
JOIN users ON users.id = project_members.user_id
WHERE project_members.project_id = $1
  AND project_members.user_id = $2
  AND users.disabled_at IS NULL
  AND projects.deleted_at IS NULL
`

type GetActiveProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetActiveProjectMemberRow struct {
	ID              uuid.UUID         `json:"id"`
	ProjectID       uuid.UUID         `json:"project_id"`
	UserID          uuid.UUID         `json:"user_id"`
	Role            ProjectMemberRole `json:"role"`
	CreatedAt       time.Time         `json:"created_at"`
	UpdatedAt       time.Time         `json:"updated_at"`
	UserEmail       string            `json:"user_email"`
	UserDisplayName string            `json:"user_display_name"`
}

func (q *Queries) GetActiveProjectMember(ctx context.Context, arg GetActiveProjectMemberParams) (GetActiveProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, getActiveProjectMember, arg.ProjectID, arg.UserID)
	var i GetActiveProjectMemberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserEmail,
		&i.UserDisplayName,
	)
	return i, err
}

const getActiveProjectMemberRole = `-- name: GetActiveProjectMemberRole :one
SELECT project_members.role
FROM project_members
JOIN projects ON projects.id = project_members.project_id
JOIN users ON users.id = project_members.user_id
WHERE project_members.project_id = $1
  AND project_members.user_id = $2
  AND users.disabled_at IS NULL
  AND projects.deleted_at IS NULL
`

type GetActiveProjectMemberRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActiveProjectMemberRole(ctx context.Context, arg GetActiveProjectMemberRoleParams) (ProjectMemberRole, error) {
	row := q.db.QueryRow(ctx, getActiveProjectMemberRole, arg.ProjectID, arg.UserID)
	var role ProjectMemberRole
	err := row.Scan(&role)
	return role, err
}

const getProjectBySlugForUser = `-- name: GetProjectBySlugForUser :one
SELECT projects.id, projects.name, projects.slug, projects.created_by_user_id, projects.created_at, projects.updated_at, projects.deleted_at
FROM projects
JOIN project_members
    ON project_members.project_id = projects.id
    AND project_members.user_id = $2
JOIN users
    ON users.id = project_members.user_id
    AND users.disabled_at IS NULL
WHERE projects.slug = $1
  AND projects.deleted_at IS NULL
`

type GetProjectBySlugForUserParams struct {
	Slug   string    `json:"slug"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectBySlugForUser(ctx context.Context, arg GetProjectBySlugForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySlugForUser, arg.Slug, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectForUser = `-- name: GetProjectForUser :one
SELECT projects.id, projects.name, projects.slug, projects.created_by_user_id, projects.created_at, projects.updated_at, projects.deleted_at
FROM projects
JOIN project_members
    ON project_members.project_id = projects.id
    AND project_members.user_id = $2
JOIN users
    ON users.id = project_members.user_id
    AND users.disabled_at IS NULL
WHERE projects.id = $1
  AND projects.deleted_at IS NULL
`

type GetProjectForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveProjectMembers = `-- name: ListActiveProjectMembers :many
SELECT project_members.id,
       project_members.project_id,
       project_members.user_id,
       project_members.role,
       project_members.created_at,
       project_members.updated_at,
       users.email AS user_email,
       users.display_name AS user_display_name
FROM project_members
JOIN projects ON projects.id = project_members.project_id
JOIN users ON users.id = project_members.user_id
WHERE project_members.project_id = $1
  AND users.disabled_at IS NULL
  AND projects.deleted_at IS NULL
ORDER BY project_members.created_at ASC, project_members.id ASC
`

type ListActiveProjectMembersRow struct {
	ID              uuid.UUID         `json:"id"`
	ProjectID       uuid.UUID         `json:"project_id"`
	UserID          uuid.UUID         `json:"user_id"`
	Role            ProjectMemberRole `json:"role"`
	CreatedAt       time.Time         `json:"created_at"`
	UpdatedAt       time.Time         `json:"updated_at"`
	UserEmail       string            `json:"user_email"`
	UserDisplayName string            `json:"user_display_name"`
}

func (q *Queries) ListActiveProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListActiveProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listActiveProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProjectMembersRow
	for rows.Next() {
		var i ListActiveProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
			&i.UserDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT projects.id, projects.name, projects.slug, projects.created_by_user_id, projects.created_at, projects.updated_at, projects.deleted_at
FROM projects
JOIN project_members
    ON project_members.project_id = projects.id
    AND project_members.user_id = $1
JOIN users
    ON users.id = project_members.user_id
    AND users.disabled_at IS NULL
WHERE projects.deleted_at IS NULL
ORDER BY projects.created_at DESC, projects.id DESC
`

func (q *Queries) ListProjectsForUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :one
UPDATE projects
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteProject, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2,
    slug = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :one
WITH updated AS (
    UPDATE project_members
    SET role = $3
    WHERE project_id = $1
      AND user_id = $2
    RETURNING id, project_id, user_id, role, created_at, updated_at
)
SELECT updated.id,
       updated.project_id,
       updated.user_id,
       updated.role,
       updated.created_at,
       updated.updated_at,
       users.email AS user_email,
       users.display_name AS user_display_name
FROM updated
JOIN users ON users.id = updated.user_id
WHERE users.disabled_at IS NULL
`

type UpdateProjectMemberRoleParams struct {
	ProjectID uuid.UUID         `json:"project_id"`
	UserID    uuid.UUID         `json:"user_id"`
	Role      ProjectMemberRole `json:"role"`
}

type UpdateProjectMemberRoleRow struct {
	ID              uuid.UUID         `json:"id"`
	ProjectID       uuid.UUID         `json:"project_id"`
	UserID          uuid.UUID         `json:"user_id"`
	Role            ProjectMemberRole `json:"role"`
	CreatedAt       time.Time         `json:"created_at"`
	UpdatedAt       time.Time         `json:"updated_at"`
	UserEmail       string            `json:"user_email"`
	UserDisplayName string            `json:"user_display_name"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) (UpdateProjectMemberRoleRow, error) {
	row := q.db.QueryRow(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	var i UpdateProjectMemberRoleRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserEmail,
		&i.UserDisplayName,
	)
	return i, err
}
