// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_status.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPublicStatusPage = `-- name: CreatePublicStatusPage :one
INSERT INTO public_status_pages (
    project_id,
    slug,
    title,
    description,
    enabled,
    default_chart_mode,
    default_chart_range,
    created_by_user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, project_id, slug, title, description, enabled, default_chart_mode, default_chart_range, created_by_user_id, created_at, updated_at, deleted_at
`

type CreatePublicStatusPageParams struct {
	ProjectID         uuid.UUID              `json:"project_id"`
	Slug              string                 `json:"slug"`
	Title             string                 `json:"title"`
	Description       *string                `json:"description"`
	Enabled           bool                   `json:"enabled"`
	DefaultChartMode  PublicStatusChartMode  `json:"default_chart_mode"`
	DefaultChartRange PublicStatusChartRange `json:"default_chart_range"`
	CreatedByUserID   uuid.UUID              `json:"created_by_user_id"`
}

func (q *Queries) CreatePublicStatusPage(ctx context.Context, arg CreatePublicStatusPageParams) (PublicStatusPage, error) {
	row := q.db.QueryRow(ctx, createPublicStatusPage,
		arg.ProjectID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Enabled,
		arg.DefaultChartMode,
		arg.DefaultChartRange,
		arg.CreatedByUserID,
	)
	var i PublicStatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Enabled,
		&i.DefaultChartMode,
		&i.DefaultChartRange,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPublicStatusPageElement = `-- name: CreatePublicStatusPageElement :one
INSERT INTO public_status_page_elements (
    public_page_id,
    project_id,
    parent_element_id,
    kind,
    check_id,
    title,
    description,
    sort_order,
    chart_mode,
    chart_range
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, public_page_id, project_id, parent_element_id, kind, check_id, title, description, sort_order, chart_mode, chart_range, created_at, updated_at
`

type CreatePublicStatusPageElementParams struct {
	PublicPageID    uuid.UUID               `json:"public_page_id"`
	ProjectID       uuid.UUID               `json:"project_id"`
	ParentElementID *uuid.UUID              `json:"parent_element_id"`
	Kind            PublicStatusElementKind `json:"kind"`
	CheckID         *uuid.UUID              `json:"check_id"`
	Title           *string                 `json:"title"`
	Description     *string                 `json:"description"`
	SortOrder       int32                   `json:"sort_order"`
	ChartMode       PublicStatusChartMode   `json:"chart_mode"`
	ChartRange      *PublicStatusChartRange `json:"chart_range"`
}

func (q *Queries) CreatePublicStatusPageElement(ctx context.Context, arg CreatePublicStatusPageElementParams) (PublicStatusPageElement, error) {
	row := q.db.QueryRow(ctx, createPublicStatusPageElement,
		arg.PublicPageID,
		arg.ProjectID,
		arg.ParentElementID,
		arg.Kind,
		arg.CheckID,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.ChartMode,
		arg.ChartRange,
	)
	var i PublicStatusPageElement
	err := row.Scan(
		&i.ID,
		&i.PublicPageID,
		&i.ProjectID,
		&i.ParentElementID,
		&i.Kind,
		&i.CheckID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.ChartMode,
		&i.ChartRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePublicStatusPageElement = `-- name: DeletePublicStatusPageElement :execrows
DELETE FROM public_status_page_elements
WHERE public_page_id = $1
  AND project_id = $2
  AND id = $3
`

type DeletePublicStatusPageElementParams struct {
	PublicPageID uuid.UUID `json:"public_page_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) DeletePublicStatusPageElement(ctx context.Context, arg DeletePublicStatusPageElementParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePublicStatusPageElement, arg.PublicPageID, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPublicStatusPage = `-- name: GetPublicStatusPage :one
SELECT id,
       project_id,
       slug,
       title,
       description,
       enabled,
       default_chart_mode,
       default_chart_range,
       created_by_user_id,
       created_at,
       updated_at,
       deleted_at
FROM public_status_pages
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetPublicStatusPageParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) GetPublicStatusPage(ctx context.Context, arg GetPublicStatusPageParams) (PublicStatusPage, error) {
	row := q.db.QueryRow(ctx, getPublicStatusPage, arg.ProjectID, arg.ID)
	var i PublicStatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Enabled,
		&i.DefaultChartMode,
		&i.DefaultChartRange,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPublicStatusPageBySlug = `-- name: GetPublicStatusPageBySlug :one
SELECT id,
       project_id,
       slug,
       title,
       description,
       enabled,
       default_chart_mode,
       default_chart_range,
       created_by_user_id,
       created_at,
       updated_at,
       deleted_at
FROM public_status_pages
WHERE slug = $1
  AND enabled = true
  AND deleted_at IS NULL
`

func (q *Queries) GetPublicStatusPageBySlug(ctx context.Context, slug string) (PublicStatusPage, error) {
	row := q.db.QueryRow(ctx, getPublicStatusPageBySlug, slug)
	var i PublicStatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Enabled,
		&i.DefaultChartMode,
		&i.DefaultChartRange,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPublicStatusPageElement = `-- name: GetPublicStatusPageElement :one
SELECT id,
       public_page_id,
       project_id,
       parent_element_id,
       kind,
       check_id,
       title,
       description,
       sort_order,
       chart_mode,
       chart_range,
       created_at,
       updated_at
FROM public_status_page_elements
WHERE public_page_id = $1
  AND project_id = $2
  AND id = $3
`

type GetPublicStatusPageElementParams struct {
	PublicPageID uuid.UUID `json:"public_page_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) GetPublicStatusPageElement(ctx context.Context, arg GetPublicStatusPageElementParams) (PublicStatusPageElement, error) {
	row := q.db.QueryRow(ctx, getPublicStatusPageElement, arg.PublicPageID, arg.ProjectID, arg.ID)
	var i PublicStatusPageElement
	err := row.Scan(
		&i.ID,
		&i.PublicPageID,
		&i.ProjectID,
		&i.ParentElementID,
		&i.Kind,
		&i.CheckID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.ChartMode,
		&i.ChartRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublicStatusAssignments = `-- name: ListPublicStatusAssignments :many
WITH page_checks AS (
    SELECT DISTINCT project_id, check_id
    FROM public_status_page_elements
    WHERE public_page_id = $1
      AND kind = 'check'
      AND check_id IS NOT NULL
)
SELECT checks.id AS check_id,
       checks.check_type,
       checks.interval_seconds,
       probes.id AS probe_id,
       probes.name AS probe_name,
       probes.location_name AS probe_location_name,
       COALESCE(latest.started_at, 'epoch'::timestamptz) AS latest_started_at,
       COALESCE(latest.status, '') AS latest_status,
       latest.latency_avg_ms,
       COALESCE(latest.loss_percent, 0::double precision) AS loss_percent,
       latest.connect_avg_ms,
       latest.failure_percent
FROM page_checks
JOIN probe_check_assignments
  ON probe_check_assignments.project_id = page_checks.project_id
 AND probe_check_assignments.check_id = page_checks.check_id
 AND probe_check_assignments.deleted_at IS NULL
JOIN probes
  ON probes.project_id = probe_check_assignments.project_id
 AND probes.id = probe_check_assignments.probe_id
 AND probes.deleted_at IS NULL
JOIN checks
  ON checks.project_id = probe_check_assignments.project_id
 AND checks.id = probe_check_assignments.check_id
 AND checks.deleted_at IS NULL
LEFT JOIN LATERAL (
    (
        SELECT ping_results.started_at,
               ping_results.status::text AS status,
               ping_results.rtt_avg_ms AS latency_avg_ms,
               ping_results.loss_percent AS loss_percent,
               NULL::double precision AS connect_avg_ms,
               NULL::double precision AS failure_percent
        FROM ping_results
        WHERE checks.check_type = 'ping'
          AND ping_results.probe_id = probes.internal_id
          AND ping_results.check_id = checks.internal_id
        ORDER BY ping_results.started_at DESC
        LIMIT 1
    )
    UNION ALL
    (
        SELECT tcp_results.started_at,
               tcp_results.status::text AS status,
               NULL::double precision AS latency_avg_ms,
               NULL::double precision AS loss_percent,
               tcp_results.connect_duration_ms AS connect_avg_ms,
               CASE WHEN tcp_results.status = 'successful' THEN 0::double precision ELSE 100::double precision END AS failure_percent
        FROM tcp_results
        WHERE checks.check_type = 'tcp'
          AND tcp_results.probe_id = probes.internal_id
          AND tcp_results.check_id = checks.internal_id
        ORDER BY tcp_results.started_at DESC
        LIMIT 1
    )
    UNION ALL
    (
        SELECT traceroute_results.started_at,
               traceroute_results.status::text AS status,
               NULL::double precision AS latency_avg_ms,
               NULL::double precision AS loss_percent,
               NULL::double precision AS connect_avg_ms,
               NULL::double precision AS failure_percent
        FROM traceroute_results
        WHERE checks.check_type = 'traceroute'
          AND traceroute_results.probe_id = probes.internal_id
          AND traceroute_results.check_id = checks.internal_id
        ORDER BY traceroute_results.started_at DESC
        LIMIT 1
    )
) latest ON TRUE
ORDER BY checks.id ASC, probes.name ASC, probes.id ASC
`

type ListPublicStatusAssignmentsRow struct {
	CheckID           uuid.UUID `json:"check_id"`
	CheckType         CheckType `json:"check_type"`
	IntervalSeconds   int32     `json:"interval_seconds"`
	ProbeID           uuid.UUID `json:"probe_id"`
	ProbeName         string    `json:"probe_name"`
	ProbeLocationName *string   `json:"probe_location_name"`
	LatestStartedAt   time.Time `json:"latest_started_at"`
	LatestStatus      string    `json:"latest_status"`
	LatencyAvgMs      *float64  `json:"latency_avg_ms"`
	LossPercent       float64   `json:"loss_percent"`
	ConnectAvgMs      *float64  `json:"connect_avg_ms"`
	FailurePercent    *float64  `json:"failure_percent"`
}

func (q *Queries) ListPublicStatusAssignments(ctx context.Context, publicPageID uuid.UUID) ([]ListPublicStatusAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicStatusAssignments, publicPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicStatusAssignmentsRow
	for rows.Next() {
		var i ListPublicStatusAssignmentsRow
		if err := rows.Scan(
			&i.CheckID,
			&i.CheckType,
			&i.IntervalSeconds,
			&i.ProbeID,
			&i.ProbeName,
			&i.ProbeLocationName,
			&i.LatestStartedAt,
			&i.LatestStatus,
			&i.LatencyAvgMs,
			&i.LossPercent,
			&i.ConnectAvgMs,
			&i.FailurePercent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicStatusIncidents = `-- name: ListPublicStatusIncidents :many
WITH page_checks AS (
    SELECT DISTINCT project_id, check_id
    FROM public_status_page_elements
    WHERE public_page_id = $2
      AND kind = 'check'
      AND check_id IS NOT NULL
)
SELECT alert_incidents.id,
       alert_incidents.project_id,
       alert_incidents.rule_id,
       alert_incidents.probe_id,
       alert_incidents.check_id,
       alert_incidents.check_type,
       alert_incidents.status,
       alert_incidents.severity,
       alert_incidents.last_evaluation_state,
       alert_incidents.opened_at,
       alert_incidents.resolved_at,
       alert_incidents.last_triggered_at,
       alert_incidents.last_value,
       alert_incidents.last_summary,
       checks.name AS check_name
FROM alert_incidents
JOIN page_checks
  ON page_checks.project_id = alert_incidents.project_id
 AND page_checks.check_id = alert_incidents.check_id
JOIN checks
  ON checks.project_id = alert_incidents.project_id
 AND checks.id = alert_incidents.check_id
WHERE alert_incidents.status IN ('open', 'acknowledged', 'resolved')
ORDER BY CASE WHEN alert_incidents.status IN ('open', 'acknowledged') THEN 0 ELSE 1 END,
         alert_incidents.opened_at DESC,
         alert_incidents.id DESC
LIMIT $1
`

type ListPublicStatusIncidentsParams struct {
	LimitCount   int32     `json:"limit_count"`
	PublicPageID uuid.UUID `json:"public_page_id"`
}

type ListPublicStatusIncidentsRow struct {
	ID                  uuid.UUID            `json:"id"`
	ProjectID           uuid.UUID            `json:"project_id"`
	RuleID              uuid.UUID            `json:"rule_id"`
	ProbeID             uuid.UUID            `json:"probe_id"`
	CheckID             uuid.UUID            `json:"check_id"`
	CheckType           CheckType            `json:"check_type"`
	Status              AlertIncidentStatus  `json:"status"`
	Severity            AlertSeverity        `json:"severity"`
	LastEvaluationState AlertEvaluationState `json:"last_evaluation_state"`
	OpenedAt            time.Time            `json:"opened_at"`
	ResolvedAt          *time.Time           `json:"resolved_at"`
	LastTriggeredAt     time.Time            `json:"last_triggered_at"`
	LastValue           *float64             `json:"last_value"`
	LastSummary         []byte               `json:"last_summary"`
	CheckName           string               `json:"check_name"`
}

func (q *Queries) ListPublicStatusIncidents(ctx context.Context, arg ListPublicStatusIncidentsParams) ([]ListPublicStatusIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicStatusIncidents, arg.LimitCount, arg.PublicPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicStatusIncidentsRow
	for rows.Next() {
		var i ListPublicStatusIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RuleID,
			&i.ProbeID,
			&i.CheckID,
			&i.CheckType,
			&i.Status,
			&i.Severity,
			&i.LastEvaluationState,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.LastTriggeredAt,
			&i.LastValue,
			&i.LastSummary,
			&i.CheckName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicStatusPageElements = `-- name: ListPublicStatusPageElements :many
SELECT public_status_page_elements.id,
       public_status_page_elements.public_page_id,
       public_status_page_elements.project_id,
       public_status_page_elements.parent_element_id,
       public_status_page_elements.kind,
       public_status_page_elements.check_id,
       public_status_page_elements.title,
       public_status_page_elements.description,
       public_status_page_elements.sort_order,
       public_status_page_elements.chart_mode,
       public_status_page_elements.chart_range,
       public_status_page_elements.created_at,
       public_status_page_elements.updated_at,
       checks.name AS check_name,
       checks.check_type AS check_type,
       checks.target AS check_target,
       checks.description AS check_description,
       checks.interval_seconds AS check_interval_seconds
FROM public_status_page_elements
LEFT JOIN checks
  ON checks.project_id = public_status_page_elements.project_id
 AND checks.id = public_status_page_elements.check_id
 AND checks.deleted_at IS NULL
WHERE public_status_page_elements.public_page_id = $1
  AND (
      public_status_page_elements.kind = 'folder'
      OR checks.id IS NOT NULL
  )
ORDER BY public_status_page_elements.parent_element_id NULLS FIRST,
         public_status_page_elements.sort_order ASC,
         public_status_page_elements.created_at ASC,
         public_status_page_elements.id ASC
`

type ListPublicStatusPageElementsRow struct {
	ID                   uuid.UUID               `json:"id"`
	PublicPageID         uuid.UUID               `json:"public_page_id"`
	ProjectID            uuid.UUID               `json:"project_id"`
	ParentElementID      *uuid.UUID              `json:"parent_element_id"`
	Kind                 PublicStatusElementKind `json:"kind"`
	CheckID              *uuid.UUID              `json:"check_id"`
	Title                *string                 `json:"title"`
	Description          *string                 `json:"description"`
	SortOrder            int32                   `json:"sort_order"`
	ChartMode            PublicStatusChartMode   `json:"chart_mode"`
	ChartRange           *PublicStatusChartRange `json:"chart_range"`
	CreatedAt            time.Time               `json:"created_at"`
	UpdatedAt            time.Time               `json:"updated_at"`
	CheckName            *string                 `json:"check_name"`
	CheckType            *CheckType              `json:"check_type"`
	CheckTarget          *string                 `json:"check_target"`
	CheckDescription     *string                 `json:"check_description"`
	CheckIntervalSeconds *int32                  `json:"check_interval_seconds"`
}

func (q *Queries) ListPublicStatusPageElements(ctx context.Context, publicPageID uuid.UUID) ([]ListPublicStatusPageElementsRow, error) {
	rows, err := q.db.Query(ctx, listPublicStatusPageElements, publicPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicStatusPageElementsRow
	for rows.Next() {
		var i ListPublicStatusPageElementsRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicPageID,
			&i.ProjectID,
			&i.ParentElementID,
			&i.Kind,
			&i.CheckID,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.ChartMode,
			&i.ChartRange,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CheckName,
			&i.CheckType,
			&i.CheckTarget,
			&i.CheckDescription,
			&i.CheckIntervalSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicStatusPages = `-- name: ListPublicStatusPages :many
SELECT id,
       project_id,
       slug,
       title,
       description,
       enabled,
       default_chart_mode,
       default_chart_range,
       created_by_user_id,
       created_at,
       updated_at,
       deleted_at
FROM public_status_pages
WHERE project_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPublicStatusPages(ctx context.Context, projectID uuid.UUID) ([]PublicStatusPage, error) {
	rows, err := q.db.Query(ctx, listPublicStatusPages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicStatusPage
	for rows.Next() {
		var i PublicStatusPage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Enabled,
			&i.DefaultChartMode,
			&i.DefaultChartRange,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePublicStatusPage = `-- name: SoftDeletePublicStatusPage :execrows
UPDATE public_status_pages
SET deleted_at = now(),
    enabled = false
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type SoftDeletePublicStatusPageParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SoftDeletePublicStatusPage(ctx context.Context, arg SoftDeletePublicStatusPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePublicStatusPage, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePublicStatusPage = `-- name: UpdatePublicStatusPage :one
UPDATE public_status_pages
SET slug = $1,
    title = $2,
    description = $3,
    enabled = $4,
    default_chart_mode = $5,
    default_chart_range = $6
WHERE project_id = $7
  AND id = $8
  AND deleted_at IS NULL
RETURNING id, project_id, slug, title, description, enabled, default_chart_mode, default_chart_range, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdatePublicStatusPageParams struct {
	Slug              string                 `json:"slug"`
	Title             string                 `json:"title"`
	Description       *string                `json:"description"`
	Enabled           bool                   `json:"enabled"`
	DefaultChartMode  PublicStatusChartMode  `json:"default_chart_mode"`
	DefaultChartRange PublicStatusChartRange `json:"default_chart_range"`
	ProjectID         uuid.UUID              `json:"project_id"`
	ID                uuid.UUID              `json:"id"`
}

func (q *Queries) UpdatePublicStatusPage(ctx context.Context, arg UpdatePublicStatusPageParams) (PublicStatusPage, error) {
	row := q.db.QueryRow(ctx, updatePublicStatusPage,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Enabled,
		arg.DefaultChartMode,
		arg.DefaultChartRange,
		arg.ProjectID,
		arg.ID,
	)
	var i PublicStatusPage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Enabled,
		&i.DefaultChartMode,
		&i.DefaultChartRange,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePublicStatusPageElement = `-- name: UpdatePublicStatusPageElement :one
UPDATE public_status_page_elements
SET parent_element_id = $1,
    kind = $2,
    check_id = $3,
    title = $4,
    description = $5,
    sort_order = $6,
    chart_mode = $7,
    chart_range = $8
WHERE public_page_id = $9
  AND project_id = $10
  AND id = $11
RETURNING id, public_page_id, project_id, parent_element_id, kind, check_id, title, description, sort_order, chart_mode, chart_range, created_at, updated_at
`

type UpdatePublicStatusPageElementParams struct {
	ParentElementID *uuid.UUID              `json:"parent_element_id"`
	Kind            PublicStatusElementKind `json:"kind"`
	CheckID         *uuid.UUID              `json:"check_id"`
	Title           *string                 `json:"title"`
	Description     *string                 `json:"description"`
	SortOrder       int32                   `json:"sort_order"`
	ChartMode       PublicStatusChartMode   `json:"chart_mode"`
	ChartRange      *PublicStatusChartRange `json:"chart_range"`
	PublicPageID    uuid.UUID               `json:"public_page_id"`
	ProjectID       uuid.UUID               `json:"project_id"`
	ID              uuid.UUID               `json:"id"`
}

func (q *Queries) UpdatePublicStatusPageElement(ctx context.Context, arg UpdatePublicStatusPageElementParams) (PublicStatusPageElement, error) {
	row := q.db.QueryRow(ctx, updatePublicStatusPageElement,
		arg.ParentElementID,
		arg.Kind,
		arg.CheckID,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.ChartMode,
		arg.ChartRange,
		arg.PublicPageID,
		arg.ProjectID,
		arg.ID,
	)
	var i PublicStatusPageElement
	err := row.Scan(
		&i.ID,
		&i.PublicPageID,
		&i.ProjectID,
		&i.ParentElementID,
		&i.Kind,
		&i.CheckID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.ChartMode,
		&i.ChartRange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
