// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
WITH created AS (
    INSERT INTO users (email, display_name, email_verified_at)
    VALUES ($1, $2, $3)
    RETURNING id, email, display_name, created_at, updated_at, email_verified_at, disabled_at
), credential AS (
    INSERT INTO password_credentials (user_id, password_hash)
    SELECT id, $4
    FROM created
    RETURNING user_id, password_hash
)
SELECT created.id,
       created.email,
       credential.password_hash,
       true::boolean AS has_password,
       created.display_name,
       created.email_verified_at,
       created.disabled_at,
       false::boolean AS is_system_admin,
       created.created_at,
       created.updated_at
FROM created
JOIN credential ON credential.user_id = created.id
`

type CreateUserParams struct {
	Email           string     `json:"email"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	PasswordHash    string     `json:"password_hash"`
}

type CreateUserRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.EmailVerifiedAt,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserPasswordCredential = `-- name: DeleteUserPasswordCredential :one
WITH deleted AS (
    DELETE FROM password_credentials
    WHERE password_credentials.user_id = $1
      AND EXISTS (SELECT 1 FROM user_identities WHERE user_identities.user_id = password_credentials.user_id)
    RETURNING user_id
)
SELECT users.id,
       users.email,
       ''::text AS password_hash,
       false::boolean AS has_password,
       users.display_name,
       users.email_verified_at,
       users.disabled_at,
       EXISTS (
           SELECT 1 FROM system_user_roles
           WHERE system_user_roles.user_id = users.id AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       users.created_at,
       users.updated_at
FROM users
JOIN deleted ON deleted.user_id = users.id
`

type DeleteUserPasswordCredentialRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) DeleteUserPasswordCredential(ctx context.Context, id uuid.UUID) (DeleteUserPasswordCredentialRow, error) {
	row := q.db.QueryRow(ctx, deleteUserPasswordCredential, id)
	var i DeleteUserPasswordCredentialRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableUser = `-- name: DisableUser :one
UPDATE users
SET disabled_at = COALESCE(users.disabled_at, $1)
WHERE users.id = $2
RETURNING users.id,
       users.email,
       COALESCE((SELECT password_hash FROM password_credentials WHERE user_id = users.id), '')::text AS password_hash,
       EXISTS(SELECT 1 FROM password_credentials WHERE user_id = users.id)::boolean AS has_password,
       users.display_name,
       users.email_verified_at,
       users.disabled_at,
       EXISTS (
           SELECT 1 FROM system_user_roles
           WHERE system_user_roles.user_id = users.id AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       users.created_at,
       users.updated_at
`

type DisableUserParams struct {
	DisabledAt *time.Time `json:"disabled_at"`
	ID         uuid.UUID  `json:"id"`
}

type DisableUserRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) DisableUser(ctx context.Context, arg DisableUserParams) (DisableUserRow, error) {
	row := q.db.QueryRow(ctx, disableUser, arg.DisabledAt, arg.ID)
	var i DisableUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT users.id,
       users.email,
       COALESCE(password_credentials.password_hash, '')::text AS password_hash,
       (password_credentials.user_id IS NOT NULL)::boolean AS has_password,
       users.display_name,
       users.email_verified_at,
       users.disabled_at,
       EXISTS (
           SELECT 1
           FROM system_user_roles
           WHERE system_user_roles.user_id = users.id
             AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       users.created_at,
       users.updated_at
FROM users
LEFT JOIN password_credentials ON password_credentials.user_id = users.id
WHERE users.email = $1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT users.id,
       users.email,
       COALESCE(password_credentials.password_hash, '')::text AS password_hash,
       (password_credentials.user_id IS NOT NULL)::boolean AS has_password,
       users.display_name,
       users.email_verified_at,
       users.disabled_at,
       EXISTS (
           SELECT 1
           FROM system_user_roles
           WHERE system_user_roles.user_id = users.id
             AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       users.created_at,
       users.updated_at
FROM users
LEFT JOIN password_credentials ON password_credentials.user_id = users.id
WHERE users.id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE users
SET email_verified_at = COALESCE(users.email_verified_at, $2)
WHERE users.id = $1
RETURNING users.id,
       users.email,
       COALESCE((SELECT password_hash FROM password_credentials WHERE user_id = users.id), '')::text AS password_hash,
       EXISTS(SELECT 1 FROM password_credentials WHERE user_id = users.id)::boolean AS has_password,
       users.display_name,
       users.email_verified_at,
       users.disabled_at,
       EXISTS (
           SELECT 1 FROM system_user_roles
           WHERE system_user_roles.user_id = users.id AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       users.created_at,
       users.updated_at
`

type MarkUserEmailVerifiedParams struct {
	ID              uuid.UUID  `json:"id"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
}

type MarkUserEmailVerifiedRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) (MarkUserEmailVerifiedRow, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, arg.ID, arg.EmailVerifiedAt)
	var i MarkUserEmailVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
WITH updated AS (
    UPDATE users
    SET display_name = $2
    WHERE id = $1
    RETURNING id, email, display_name, created_at, updated_at, email_verified_at, disabled_at
)
SELECT updated.id,
       updated.email,
       COALESCE(password_credentials.password_hash, '')::text AS password_hash,
       (password_credentials.user_id IS NOT NULL)::boolean AS has_password,
       updated.display_name,
       updated.email_verified_at,
       updated.disabled_at,
       EXISTS (
           SELECT 1 FROM system_user_roles
           WHERE system_user_roles.user_id = updated.id AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       updated.created_at,
       updated.updated_at
FROM updated
LEFT JOIN password_credentials ON password_credentials.user_id = updated.id
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

type UpdateUserDisplayNameRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
WITH updated AS (
    UPDATE users
    SET email = $2
    WHERE id = $1
    RETURNING id, email, display_name, created_at, updated_at, email_verified_at, disabled_at
)
SELECT updated.id,
       updated.email,
       COALESCE(password_credentials.password_hash, '')::text AS password_hash,
       (password_credentials.user_id IS NOT NULL)::boolean AS has_password,
       updated.display_name,
       updated.email_verified_at,
       updated.disabled_at,
       EXISTS (
           SELECT 1 FROM system_user_roles
           WHERE system_user_roles.user_id = updated.id AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       updated.created_at,
       updated.updated_at
FROM updated
LEFT JOIN password_credentials ON password_credentials.user_id = updated.id
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

type UpdateUserEmailRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
WITH credential AS (
    INSERT INTO password_credentials (user_id, password_hash)
    VALUES ($1, $2)
    ON CONFLICT (user_id) DO UPDATE SET password_hash = EXCLUDED.password_hash
    RETURNING user_id, password_hash
)
SELECT users.id,
       users.email,
       credential.password_hash,
       true::boolean AS has_password,
       users.display_name,
       users.email_verified_at,
       users.disabled_at,
       EXISTS (
           SELECT 1 FROM system_user_roles
           WHERE system_user_roles.user_id = users.id AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       users.created_at,
       users.updated_at
FROM users
JOIN credential ON credential.user_id = users.id
`

type UpdateUserPasswordHashParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

type UpdateUserPasswordHashRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	HasPassword     bool       `json:"has_password"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (UpdateUserPasswordHashRow, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordHash, arg.UserID, arg.PasswordHash)
	var i UpdateUserPasswordHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.HasPassword,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
