// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, email_verified_at)
VALUES ($1, $2, $3, $4)
RETURNING id,
          email,
          password_hash,
          display_name,
          email_verified_at,
          disabled_at,
          false::boolean AS is_system_admin,
          created_at,
          updated_at
`

type CreateUserParams struct {
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
}

type CreateUserRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.EmailVerifiedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableUser = `-- name: DisableUser :one
UPDATE users
SET disabled_at = COALESCE(disabled_at, $1)
WHERE id = $2
RETURNING id,
          email,
          password_hash,
          display_name,
          email_verified_at,
          disabled_at,
          EXISTS (
              SELECT 1
              FROM system_user_roles
              WHERE system_user_roles.user_id = users.id
                AND system_user_roles.role = 'admin'
          ) AS is_system_admin,
          created_at,
          updated_at
`

type DisableUserParams struct {
	DisabledAt *time.Time `json:"disabled_at"`
	ID         uuid.UUID  `json:"id"`
}

type DisableUserRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) DisableUser(ctx context.Context, arg DisableUserParams) (DisableUserRow, error) {
	row := q.db.QueryRow(ctx, disableUser, arg.DisabledAt, arg.ID)
	var i DisableUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id,
       email,
       password_hash,
       display_name,
       email_verified_at,
       disabled_at,
       EXISTS (
           SELECT 1
           FROM system_user_roles
           WHERE system_user_roles.user_id = users.id
             AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       created_at,
       updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id,
       email,
       password_hash,
       display_name,
       email_verified_at,
       disabled_at,
       EXISTS (
           SELECT 1
           FROM system_user_roles
           WHERE system_user_roles.user_id = users.id
             AND system_user_roles.role = 'admin'
       ) AS is_system_admin,
       created_at,
       updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markUserEmailVerified = `-- name: MarkUserEmailVerified :one
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, $1)
WHERE id = $2
RETURNING id,
          email,
          password_hash,
          display_name,
          email_verified_at,
          disabled_at,
          EXISTS (
              SELECT 1
              FROM system_user_roles
              WHERE system_user_roles.user_id = users.id
                AND system_user_roles.role = 'admin'
          ) AS is_system_admin,
          created_at,
          updated_at
`

type MarkUserEmailVerifiedParams struct {
	VerifiedAt *time.Time `json:"verified_at"`
	ID         uuid.UUID  `json:"id"`
}

type MarkUserEmailVerifiedRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) MarkUserEmailVerified(ctx context.Context, arg MarkUserEmailVerifiedParams) (MarkUserEmailVerifiedRow, error) {
	row := q.db.QueryRow(ctx, markUserEmailVerified, arg.VerifiedAt, arg.ID)
	var i MarkUserEmailVerifiedRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $2
WHERE id = $1
RETURNING id,
          email,
          password_hash,
          display_name,
          email_verified_at,
          disabled_at,
          EXISTS (
              SELECT 1
              FROM system_user_roles
              WHERE system_user_roles.user_id = users.id
                AND system_user_roles.role = 'admin'
          ) AS is_system_admin,
          created_at,
          updated_at
`

type UpdateUserDisplayNameParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
}

type UpdateUserDisplayNameRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $2
WHERE id = $1
RETURNING id,
          email,
          password_hash,
          display_name,
          email_verified_at,
          disabled_at,
          EXISTS (
              SELECT 1
              FROM system_user_roles
              WHERE system_user_roles.user_id = users.id
                AND system_user_roles.role = 'admin'
          ) AS is_system_admin,
          created_at,
          updated_at
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

type UpdateUserEmailRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
UPDATE users
SET password_hash = $2
WHERE id = $1
RETURNING id,
          email,
          password_hash,
          display_name,
          email_verified_at,
          disabled_at,
          EXISTS (
              SELECT 1
              FROM system_user_roles
              WHERE system_user_roles.user_id = users.id
                AND system_user_roles.role = 'admin'
          ) AS is_system_admin,
          created_at,
          updated_at
`

type UpdateUserPasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

type UpdateUserPasswordHashRow struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	PasswordHash    string     `json:"password_hash"`
	DisplayName     string     `json:"display_name"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	DisabledAt      *time.Time `json:"disabled_at"`
	IsSystemAdmin   bool       `json:"is_system_admin"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) (UpdateUserPasswordHashRow, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	var i UpdateUserPasswordHashRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.DisabledAt,
		&i.IsSystemAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
