-- +goose Up
ALTER TABLE notification_channels RENAME TO notifications;
ALTER TYPE notification_channel_type RENAME TO notification_type;

ALTER TABLE notifications RENAME CONSTRAINT notification_channels_pkey TO notifications_pkey;
ALTER TABLE notifications RENAME CONSTRAINT notification_channels_project_id_fkey TO notifications_project_id_fkey;
ALTER TABLE notifications RENAME CONSTRAINT notification_channels_created_by_user_id_fkey TO notifications_created_by_user_id_fkey;
ALTER TABLE notifications RENAME CONSTRAINT uq_notification_channels_project_id_id TO uq_notifications_project_id_id;
ALTER TABLE notifications RENAME CONSTRAINT notification_channels_name_not_empty TO notifications_name_not_empty;
ALTER TABLE notifications RENAME CONSTRAINT notification_channels_config_is_object TO notifications_config_is_object;
ALTER TABLE notifications RENAME CONSTRAINT notification_channels_deleted_at_after_created_at TO notifications_deleted_at_after_created_at;
ALTER INDEX idx_notification_channels_project_active RENAME TO idx_notifications_project_active;
ALTER INDEX idx_notification_channels_project_enabled_active RENAME TO idx_notifications_project_enabled_active;
ALTER TRIGGER set_notification_channels_updated_at ON notifications RENAME TO set_notifications_updated_at;

ALTER TABLE alert_notifications RENAME COLUMN channel_id TO notification_id;
ALTER TABLE alert_notifications RENAME CONSTRAINT fk_alert_notifications_project_channel TO fk_alert_notifications_project_notification;

ALTER TABLE notification_outbox RENAME COLUMN channel_id TO notification_id;
ALTER TABLE notification_outbox RENAME COLUMN channel_type TO notification_type;
ALTER TABLE notification_outbox RENAME CONSTRAINT fk_notification_outbox_project_channel TO fk_notification_outbox_project_notification;

-- +goose Down
ALTER TABLE notification_outbox RENAME CONSTRAINT fk_notification_outbox_project_notification TO fk_notification_outbox_project_channel;
ALTER TABLE notification_outbox RENAME COLUMN notification_type TO channel_type;
ALTER TABLE notification_outbox RENAME COLUMN notification_id TO channel_id;

ALTER TABLE alert_notifications RENAME CONSTRAINT fk_alert_notifications_project_notification TO fk_alert_notifications_project_channel;
ALTER TABLE alert_notifications RENAME COLUMN notification_id TO channel_id;

ALTER TRIGGER set_notifications_updated_at ON notifications RENAME TO set_notification_channels_updated_at;
ALTER INDEX idx_notifications_project_enabled_active RENAME TO idx_notification_channels_project_enabled_active;
ALTER INDEX idx_notifications_project_active RENAME TO idx_notification_channels_project_active;
ALTER TABLE notifications RENAME CONSTRAINT notifications_deleted_at_after_created_at TO notification_channels_deleted_at_after_created_at;
ALTER TABLE notifications RENAME CONSTRAINT notifications_config_is_object TO notification_channels_config_is_object;
ALTER TABLE notifications RENAME CONSTRAINT notifications_name_not_empty TO notification_channels_name_not_empty;
ALTER TABLE notifications RENAME CONSTRAINT uq_notifications_project_id_id TO uq_notification_channels_project_id_id;
ALTER TABLE notifications RENAME CONSTRAINT notifications_created_by_user_id_fkey TO notification_channels_created_by_user_id_fkey;
ALTER TABLE notifications RENAME CONSTRAINT notifications_project_id_fkey TO notification_channels_project_id_fkey;
ALTER TABLE notifications RENAME CONSTRAINT notifications_pkey TO notification_channels_pkey;

ALTER TYPE notification_type RENAME TO notification_channel_type;
ALTER TABLE notifications RENAME TO notification_channels;
