-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email CITEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE config_versions (
    config_version BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_by_user_id UUID NULL REFERENCES users(id),
    change_type TEXT NOT NULL,
    change_summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    checksum TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE probes (
    id UUID NOT NULL,
    config_version BIGINT NOT NULL REFERENCES config_versions(config_version),
    name TEXT NOT NULL,
    provider TEXT NULL,
    region TEXT NULL,
    hostname TEXT NULL,
    labels JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT true,
    deleted BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id, config_version)
);

CREATE TABLE probe_credentials (
    probe_id UUID PRIMARY KEY,
    secret_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_rotated_at TIMESTAMPTZ NULL
);

CREATE TABLE probe_status (
    probe_id UUID PRIMARY KEY,
    status TEXT NOT NULL,
    last_seen_at TIMESTAMPTZ NULL,
    agent_version TEXT NULL,
    ip_families TEXT[] NOT NULL DEFAULT '{}'::text[],
    capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
    health JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE targets (
    id UUID NOT NULL,
    config_version BIGINT NOT NULL REFERENCES config_versions(config_version),
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    target_type TEXT NOT NULL,
    description TEXT NULL,
    deleted BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id, config_version)
);

CREATE TABLE probe_targets (
    id UUID NOT NULL,
    config_version BIGINT NOT NULL REFERENCES config_versions(config_version),
    probe_id UUID NOT NULL,
    target_id UUID NOT NULL,
    name TEXT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    interval_seconds INTEGER NOT NULL,
    jitter_seconds INTEGER NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id, config_version)
);

CREATE TABLE probe_target_checks (
    id UUID NOT NULL,
    config_version BIGINT NOT NULL REFERENCES config_versions(config_version),
    probe_target_id UUID NOT NULL,
    check_type TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    schedule_override_seconds INTEGER NULL,
    deleted BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id, config_version)
);

CREATE TABLE probe_config_acks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    probe_id UUID NOT NULL,
    config_version BIGINT NOT NULL REFERENCES config_versions(config_version),
    status TEXT NOT NULL,
    error_message TEXT NULL,
    acked_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    probe_target_id UUID NOT NULL,
    check_id UUID NOT NULL,
    probe_id UUID NOT NULL,
    target_id UUID NOT NULL,
    check_type TEXT NOT NULL,
    config_version BIGINT NOT NULL REFERENCES config_versions(config_version),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NOT NULL,
    duration_ms INTEGER NOT NULL,
    status TEXT NOT NULL,
    summary JSONB NOT NULL DEFAULT '{}'::jsonb,
    samples JSONB NOT NULL DEFAULT '[]'::jsonb,
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_code TEXT NULL,
    error_message TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_results_probe_id_started_at ON results (probe_id, started_at DESC);
CREATE INDEX idx_results_probe_target_id_started_at ON results (probe_target_id, started_at DESC);
CREATE INDEX idx_results_check_id_started_at ON results (check_id, started_at DESC);
CREATE INDEX idx_results_check_type_started_at ON results (check_type, started_at DESC);
CREATE INDEX idx_results_config_version ON results (config_version);

-- +goose Down
DROP TABLE IF EXISTS results;
DROP TABLE IF EXISTS probe_config_acks;
DROP TABLE IF EXISTS probe_target_checks;
DROP TABLE IF EXISTS probe_targets;
DROP TABLE IF EXISTS targets;
DROP TABLE IF EXISTS probe_status;
DROP TABLE IF EXISTS probe_credentials;
DROP TABLE IF EXISTS probes;
DROP TABLE IF EXISTS config_versions;
DROP TABLE IF EXISTS users;
