global:
  scrape_interval: 2s

scrape_configs:
  - job_name: controller
    metrics_path: /metrics
    static_configs:
      - targets:
          - controller:8080

  - job_name: postgres
    metrics_path: /metrics
    static_configs:
      - targets:
          - postgres-exporter:9187
