# syntax=docker/dockerfile:1
# check=skip=SecretsUsedInArgOrEnv

FROM node:24-alpine AS app-build

WORKDIR /app

RUN npm install -g pnpm@11.0.8

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY web/package.json web/package.json
COPY packages/brand/package.json packages/brand/package.json
COPY packages/i18n/package.json packages/i18n/package.json
COPY packages/ui/package.json packages/ui/package.json

RUN pnpm install --frozen-lockfile --filter @netstamp/web... --filter @netstamp/ui

COPY web web
COPY packages/brand packages/brand
COPY packages/i18n packages/i18n
COPY packages/ui packages/ui

ARG VITE_NETSTAMP_DEMO_EMAIL=
ARG VITE_NETSTAMP_DEMO_PASSWORD=
ENV VITE_NETSTAMP_DEMO_EMAIL=$VITE_NETSTAMP_DEMO_EMAIL
ENV VITE_NETSTAMP_DEMO_PASSWORD=$VITE_NETSTAMP_DEMO_PASSWORD

ARG VITE_NETSTAMP_GA_MEASUREMENT_ID=
ARG VITE_NETSTAMP_GOOGLE_TAG_ID=
ARG VITE_NETSTAMP_CLARITY_PROJECT_ID=
ARG VITE_NETSTAMP_META_PIXEL_ID=
ARG VITE_NETSTAMP_FACEBOOK_PIXEL_ID=
ARG VITE_NETSTAMP_POSTHOG_KEY=
ARG VITE_NETSTAMP_POSTHOG_HOST=
ARG VITE_NETSTAMP_PLAUSIBLE_DOMAIN=
ARG VITE_NETSTAMP_PLAUSIBLE_SCRIPT_URL=
ARG VITE_NETSTAMP_UMAMI_WEBSITE_ID=
ARG VITE_NETSTAMP_UMAMI_SCRIPT_URL=
ARG VITE_NETSTAMP_TRACKING_CONSENT_MODE=regional
ARG VITE_NETSTAMP_TRACKING_CONSENT_COUNTRIES=
ENV VITE_NETSTAMP_GA_MEASUREMENT_ID=$VITE_NETSTAMP_GA_MEASUREMENT_ID
ENV VITE_NETSTAMP_GOOGLE_TAG_ID=$VITE_NETSTAMP_GOOGLE_TAG_ID
ENV VITE_NETSTAMP_CLARITY_PROJECT_ID=$VITE_NETSTAMP_CLARITY_PROJECT_ID
ENV VITE_NETSTAMP_META_PIXEL_ID=$VITE_NETSTAMP_META_PIXEL_ID
ENV VITE_NETSTAMP_FACEBOOK_PIXEL_ID=$VITE_NETSTAMP_FACEBOOK_PIXEL_ID
ENV VITE_NETSTAMP_POSTHOG_KEY=$VITE_NETSTAMP_POSTHOG_KEY
ENV VITE_NETSTAMP_POSTHOG_HOST=$VITE_NETSTAMP_POSTHOG_HOST
ENV VITE_NETSTAMP_PLAUSIBLE_DOMAIN=$VITE_NETSTAMP_PLAUSIBLE_DOMAIN
ENV VITE_NETSTAMP_PLAUSIBLE_SCRIPT_URL=$VITE_NETSTAMP_PLAUSIBLE_SCRIPT_URL
ENV VITE_NETSTAMP_UMAMI_WEBSITE_ID=$VITE_NETSTAMP_UMAMI_WEBSITE_ID
ENV VITE_NETSTAMP_UMAMI_SCRIPT_URL=$VITE_NETSTAMP_UMAMI_SCRIPT_URL
ENV VITE_NETSTAMP_TRACKING_CONSENT_MODE=$VITE_NETSTAMP_TRACKING_CONSENT_MODE
ENV VITE_NETSTAMP_TRACKING_CONSENT_COUNTRIES=$VITE_NETSTAMP_TRACKING_CONSENT_COUNTRIES

RUN pnpm --filter @netstamp/web build

FROM nginx:1.27-alpine

COPY deployments/dev/nginx.conf /etc/nginx/nginx.conf
COPY --from=app-build /app/web/dist /usr/share/nginx/web

EXPOSE 80
