// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: probes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProbe = `-- name: CreateProbe :one
INSERT INTO probes (project_id, name, enabled, location, city)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, enabled, location, city, created_at, updated_at, deleted_at
`

type CreateProbeParams struct {
	ProjectID uuid.UUID    `json:"project_id"`
	Name      string       `json:"name"`
	Enabled   bool         `json:"enabled"`
	Location  pgtype.Point `json:"location"`
	City      *string      `json:"city"`
}

func (q *Queries) CreateProbe(ctx context.Context, arg CreateProbeParams) (Probe, error) {
	row := q.db.QueryRow(ctx, createProbe,
		arg.ProjectID,
		arg.Name,
		arg.Enabled,
		arg.Location,
		arg.City,
	)
	var i Probe
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.Location,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProbeCredential = `-- name: CreateProbeCredential :one
INSERT INTO probe_credentials (probe_id, secret_hash)
VALUES ($1, $2)
RETURNING probe_id, secret_hash, created_at, last_rotated_at
`

type CreateProbeCredentialParams struct {
	ProbeID    uuid.UUID `json:"probe_id"`
	SecretHash string    `json:"secret_hash"`
}

func (q *Queries) CreateProbeCredential(ctx context.Context, arg CreateProbeCredentialParams) (ProbeCredential, error) {
	row := q.db.QueryRow(ctx, createProbeCredential, arg.ProbeID, arg.SecretHash)
	var i ProbeCredential
	err := row.Scan(
		&i.ProbeID,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastRotatedAt,
	)
	return i, err
}

const createProbeLabel = `-- name: CreateProbeLabel :exec
INSERT INTO probe_labels (project_id, probe_id, label_id)
VALUES ($1, $2, $3)
`

type CreateProbeLabelParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ProbeID   uuid.UUID `json:"probe_id"`
	LabelID   uuid.UUID `json:"label_id"`
}

func (q *Queries) CreateProbeLabel(ctx context.Context, arg CreateProbeLabelParams) error {
	_, err := q.db.Exec(ctx, createProbeLabel, arg.ProjectID, arg.ProbeID, arg.LabelID)
	return err
}

const createProbeStatus = `-- name: CreateProbeStatus :one
INSERT INTO probe_statuses (probe_id, status)
VALUES ($1, $2)
RETURNING probe_id, status, last_seen_at, agent_version, public_v4, public_v6, addrs, updated_at
`

type CreateProbeStatusParams struct {
	ProbeID uuid.UUID  `json:"probe_id"`
	Status  ProbeState `json:"status"`
}

func (q *Queries) CreateProbeStatus(ctx context.Context, arg CreateProbeStatusParams) (ProbeStatus, error) {
	row := q.db.QueryRow(ctx, createProbeStatus, arg.ProbeID, arg.Status)
	var i ProbeStatus
	err := row.Scan(
		&i.ProbeID,
		&i.Status,
		&i.LastSeenAt,
		&i.AgentVersion,
		&i.PublicV4,
		&i.PublicV6,
		&i.Addrs,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveLabelsByIDsForProject = `-- name: GetActiveLabelsByIDsForProject :many
WITH requested AS (
    SELECT label_id, position
    FROM unnest($2::uuid[]) WITH ORDINALITY AS requested(label_id, position)
)
SELECT labels.id,
       labels.project_id,
       labels.key,
       labels.value,
       labels.created_at,
       labels.updated_at,
       labels.deleted_at
FROM requested
JOIN labels
    ON labels.project_id = $1
    AND labels.id = requested.label_id
WHERE labels.deleted_at IS NULL
ORDER BY requested.position
`

type GetActiveLabelsByIDsForProjectParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	LabelIds  []uuid.UUID `json:"label_ids"`
}

func (q *Queries) GetActiveLabelsByIDsForProject(ctx context.Context, arg GetActiveLabelsByIDsForProjectParams) ([]Label, error) {
	rows, err := q.db.Query(ctx, getActiveLabelsByIDsForProject, arg.ProjectID, arg.LabelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
