// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTeamOwners = `-- name: CountActiveTeamOwners :one
SELECT count(*)::int4
FROM team_members
WHERE team_id = $1
  AND role = 'owner'
  AND deleted_at IS NULL
`

func (q *Queries) CountActiveTeamOwners(ctx context.Context, teamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countActiveTeamOwners, teamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, slug, created_by_user_id)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateTeamParams struct {
	Name            string    `json:"name"`
	Slug            string    `json:"slug"`
	CreatedByUserID uuid.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.Slug, arg.CreatedByUserID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTeamMember = `-- name: CreateTeamMember :one
WITH inserted AS (
    INSERT INTO team_members (team_id, user_id, role)
    VALUES ($1, $2, $3)
    RETURNING id, team_id, user_id, role, created_at, updated_at
)
SELECT inserted.id,
       inserted.team_id,
       inserted.user_id,
       users.email,
       inserted.role,
       inserted.created_at,
       inserted.updated_at
FROM inserted
JOIN users ON users.id = inserted.user_id
`

type CreateTeamMemberParams struct {
	TeamID uuid.UUID      `json:"team_id"`
	UserID uuid.UUID      `json:"user_id"`
	Role   TeamMemberRole `json:"role"`
}

type CreateTeamMemberRow struct {
	ID        uuid.UUID          `json:"id"`
	TeamID    uuid.UUID          `json:"team_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Email     string             `json:"email"`
	Role      TeamMemberRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (CreateTeamMemberRow, error) {
	row := q.db.QueryRow(ctx, createTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i CreateTeamMemberRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTeamMember = `-- name: GetActiveTeamMember :one
SELECT team_members.id,
       team_members.team_id,
       team_members.user_id,
       users.email,
       team_members.role,
       team_members.created_at,
       team_members.updated_at
FROM team_members
JOIN users ON users.id = team_members.user_id
JOIN teams ON teams.id = team_members.team_id
WHERE team_members.team_id = $1
  AND team_members.user_id = $2
  AND team_members.deleted_at IS NULL
  AND teams.deleted_at IS NULL
`

type GetActiveTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetActiveTeamMemberRow struct {
	ID        uuid.UUID          `json:"id"`
	TeamID    uuid.UUID          `json:"team_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Email     string             `json:"email"`
	Role      TeamMemberRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveTeamMember(ctx context.Context, arg GetActiveTeamMemberParams) (GetActiveTeamMemberRow, error) {
	row := q.db.QueryRow(ctx, getActiveTeamMember, arg.TeamID, arg.UserID)
	var i GetActiveTeamMemberRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTeamMemberRole = `-- name: GetActiveTeamMemberRole :one
SELECT team_members.role
FROM team_members
JOIN teams ON teams.id = team_members.team_id
WHERE team_members.team_id = $1
  AND team_members.user_id = $2
  AND team_members.deleted_at IS NULL
  AND teams.deleted_at IS NULL
`

type GetActiveTeamMemberRoleParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActiveTeamMemberRole(ctx context.Context, arg GetActiveTeamMemberRoleParams) (TeamMemberRole, error) {
	row := q.db.QueryRow(ctx, getActiveTeamMemberRole, arg.TeamID, arg.UserID)
	var role TeamMemberRole
	err := row.Scan(&role)
	return role, err
}

const getTeamBySlugForUser = `-- name: GetTeamBySlugForUser :one
SELECT teams.id, teams.name, teams.slug, teams.created_by_user_id, teams.created_at, teams.updated_at, teams.deleted_at
FROM teams
JOIN team_members
    ON team_members.team_id = teams.id
    AND team_members.user_id = $2
    AND team_members.deleted_at IS NULL
WHERE teams.slug = $1
  AND teams.deleted_at IS NULL
`

type GetTeamBySlugForUserParams struct {
	Slug   string    `json:"slug"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTeamBySlugForUser(ctx context.Context, arg GetTeamBySlugForUserParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamBySlugForUser, arg.Slug, arg.UserID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTeamForUser = `-- name: GetTeamForUser :one
SELECT teams.id, teams.name, teams.slug, teams.created_by_user_id, teams.created_at, teams.updated_at, teams.deleted_at
FROM teams
JOIN team_members
    ON team_members.team_id = teams.id
    AND team_members.user_id = $2
    AND team_members.deleted_at IS NULL
WHERE teams.id = $1
  AND teams.deleted_at IS NULL
`

type GetTeamForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTeamForUser(ctx context.Context, arg GetTeamForUserParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamForUser, arg.ID, arg.UserID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveTeamMembers = `-- name: ListActiveTeamMembers :many
SELECT team_members.id,
       team_members.team_id,
       team_members.user_id,
       users.email,
       team_members.role,
       team_members.created_at,
       team_members.updated_at
FROM team_members
JOIN users ON users.id = team_members.user_id
JOIN teams ON teams.id = team_members.team_id
WHERE team_members.team_id = $1
  AND team_members.deleted_at IS NULL
  AND teams.deleted_at IS NULL
ORDER BY team_members.created_at ASC, team_members.id ASC
`

type ListActiveTeamMembersRow struct {
	ID        uuid.UUID          `json:"id"`
	TeamID    uuid.UUID          `json:"team_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Email     string             `json:"email"`
	Role      TeamMemberRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListActiveTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listActiveTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTeamMembersRow
	for rows.Next() {
		var i ListActiveTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT teams.id, teams.name, teams.slug, teams.created_by_user_id, teams.created_at, teams.updated_at, teams.deleted_at
FROM teams
JOIN team_members
    ON team_members.team_id = teams.id
    AND team_members.user_id = $1
    AND team_members.deleted_at IS NULL
WHERE teams.deleted_at IS NULL
ORDER BY teams.created_at DESC, teams.id DESC
`

func (q *Queries) ListTeamsForUser(ctx context.Context, userID uuid.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTeam = `-- name: SoftDeleteTeam :one
UPDATE teams
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) SoftDeleteTeam(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteTeam, id)
	err := row.Scan(&id)
	return id, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $2,
    slug = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, name, slug, created_by_user_id, created_at, updated_at, deleted_at
`

type UpdateTeamParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Slug string    `json:"slug"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.ID, arg.Name, arg.Slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :one
WITH updated AS (
    UPDATE team_members
    SET role = $3
    WHERE team_id = $1
      AND user_id = $2
      AND deleted_at IS NULL
    RETURNING id, team_id, user_id, role, created_at, updated_at
)
SELECT updated.id,
       updated.team_id,
       updated.user_id,
       users.email,
       updated.role,
       updated.created_at,
       updated.updated_at
FROM updated
JOIN users ON users.id = updated.user_id
`

type UpdateTeamMemberRoleParams struct {
	TeamID uuid.UUID      `json:"team_id"`
	UserID uuid.UUID      `json:"user_id"`
	Role   TeamMemberRole `json:"role"`
}

type UpdateTeamMemberRoleRow struct {
	ID        uuid.UUID          `json:"id"`
	TeamID    uuid.UUID          `json:"team_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Email     string             `json:"email"`
	Role      TeamMemberRole     `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) (UpdateTeamMemberRoleRow, error) {
	row := q.db.QueryRow(ctx, updateTeamMemberRole, arg.TeamID, arg.UserID, arg.Role)
	var i UpdateTeamMemberRoleRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
