apiVersion: 1

datasources:
  - name: VictoriaTraces
    uid: victoria-traces
    type: jaeger
    access: proxy
    url: http://victoria-traces:10428/select/jaeger
    isDefault: true
    editable: true

  - name: VictoriaMetrics
    uid: victoria-metrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: false
    editable: true

  - name: VictoriaLogs
    uid: victoria-logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - name: trace_id
          matcherType: label
          matcherRegex: trace_id
          datasourceUid: victoria-traces
          url: "$${__value.raw}"
          urlDisplayLabel: Open trace
      logLevelRules:
        - field: level
          operator: equals
          value: error
          level: error
          enabled: true
        - field: level
          operator: equals
          value: warn
          level: warning
          enabled: true
        - field: level
          operator: equals
          value: info
          level: info
          enabled: true
        - field: level
          operator: equals
          value: debug
          level: debug
          enabled: true
