apiVersion: 1

datasources:
  - name: VictoriaTraces
    uid: victoria-traces
    type: jaeger
    access: proxy
    url: http://victoria-traces:10428/select/jaeger
    isDefault: true
    editable: true

  - name: VictoriaLogs
    uid: victoria-logs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victoria-logs:9428
    isDefault: false
    editable: true
