/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get API status */
		get: operations["getAPIStatus"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Login user
		 * @description Verify an email and password pair, then set an HTTP-only session cookie for the authenticated user. Invalid credentials always return the same unauthorized response so callers cannot distinguish an unknown email from a password mismatch.
		 */
		post: operations["loginUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Logout user
		 * @description Clear the HTTP-only session cookie.
		 */
		post: operations["logoutUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get current user
		 * @description Return the user identity embedded in a valid session cookie.
		 */
		get: operations["getCurrentUser"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Register user
		 * @description Create a user account with a normalized email address, display name, and password. On success, sets an HTTP-only session cookie for immediate API access.
		 */
		post: operations["registerUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/healthz": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get health status */
		get: operations["getHealth"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List projects */
		get: operations["listProjects"];
		put?: never;
		/** Create project */
		post: operations["createProject"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get project */
		get: operations["getProject"];
		put?: never;
		post?: never;
		/** Delete project */
		delete: operations["deleteProject"];
		options?: never;
		head?: never;
		/** Update project */
		patch: operations["updateProject"];
		trace?: never;
	};
	"/projects/{ref}/checks": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project checks */
		get: operations["listProjectChecks"];
		put?: never;
		/** Create project check */
		post: operations["createProjectCheck"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/checks/{check_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get project check */
		get: operations["getProjectCheck"];
		put?: never;
		post?: never;
		/** Delete project check */
		delete: operations["deleteProjectCheck"];
		options?: never;
		head?: never;
		/** Update project check */
		patch: operations["updateProjectCheck"];
		trace?: never;
	};
	"/projects/{ref}/labels": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project labels */
		get: operations["listProjectLabels"];
		put?: never;
		/** Create project label */
		post: operations["createProjectLabel"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/labels/{label_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete project label */
		delete: operations["deleteProjectLabel"];
		options?: never;
		head?: never;
		/** Update project label */
		patch: operations["updateProjectLabel"];
		trace?: never;
	};
	"/projects/{ref}/members": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project members */
		get: operations["listProjectMembers"];
		put?: never;
		/** Add project member */
		post: operations["addProjectMember"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/members/{user_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Remove project member */
		delete: operations["removeProjectMember"];
		options?: never;
		head?: never;
		/** Update project member role */
		patch: operations["updateProjectMemberRole"];
		trace?: never;
	};
	"/projects/{ref}/probes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project probes */
		get: operations["listProjectProbes"];
		put?: never;
		/** Create project probe */
		post: operations["createProjectProbe"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/probes/{probe_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get project probe */
		get: operations["getProjectProbe"];
		put?: never;
		post?: never;
		/** Delete project probe */
		delete: operations["deleteProjectProbe"];
		options?: never;
		head?: never;
		/** Update project probe */
		patch: operations["updateProjectProbe"];
		trace?: never;
	};
	"/projects/{ref}/probes/{probe_id}/secret-rotations": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Rotate project probe secret */
		post: operations["rotateProjectProbeSecret"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/results/ping/series": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Query project ping result series */
		get: operations["queryProjectPingResultSeries"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/results/traceroute/runs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Query project traceroute result runs */
		get: operations["queryProjectTracerouteResultRuns"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/runtime/probes/{probe_id}/assignments": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List probe runtime assignments */
		get: operations["listProbeRuntimeAssignments"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/runtime/probes/{probe_id}/heartbeat": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Update probe runtime status */
		post: operations["probeRuntimeHeartbeat"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/runtime/probes/{probe_id}/hello": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Start probe runtime session */
		post: operations["probeRuntimeHello"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/runtime/probes/{probe_id}/results": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Submit probe runtime results */
		post: operations["submitProbeRuntimeResults"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		AddMemberInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/AddMemberInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Project member role.
			 * @example viewer
			 */
			role?: string;
			/** @description User ID to add to the project. */
			userId?: string;
		};
		Assignment: {
			check?: components["schemas"]["Check"];
			checkVersion: string;
			id: string;
			probe?: components["schemas"]["Probe"];
			projectId: string;
			selectorVersion: string;
		};
		AssignmentsOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/AssignmentsOutputBody.json
			 */
			readonly $schema?: string;
			assignments: components["schemas"]["Assignment"][] | null;
			config: components["schemas"]["RuntimeConfig"];
			/** Format: date-time */
			serverTime: string;
		};
		Check: {
			/** Format: date-time */
			createdAt: string;
			description: string | null;
			id: string;
			/** Format: int32 */
			intervalSeconds: number;
			labels: components["schemas"]["Label"][] | null;
			name: string;
			pingConfig?: components["schemas"]["Config"];
			projectId: string;
			selector: unknown;
			target: string;
			tracerouteConfig?: components["schemas"]["TracerouteConfig"];
			type: string;
			/** Format: date-time */
			updatedAt: string;
		};
		CheckOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/CheckOutputBody.json
			 */
			readonly $schema?: string;
			check: components["schemas"]["Check"];
		};
		CheckPingConfigInput: {
			/**
			 * @description Optional IP family preference.
			 * @example inet
			 * @enum {string}
			 */
			ipFamily?: "inet" | "inet6";
			/**
			 * Format: int32
			 * @description ICMP packet count.
			 * @example 4
			 */
			packetCount?: number;
			/**
			 * Format: int32
			 * @description ICMP payload size in bytes.
			 * @example 56
			 */
			packetSizeBytes?: number;
			/**
			 * Format: int32
			 * @description Ping timeout in milliseconds.
			 * @example 3000
			 */
			timeoutMs?: number;
		};
		CheckTracerouteConfigInput: {
			/**
			 * @description Optional IP family preference.
			 * @example inet
			 * @enum {string}
			 */
			ipFamily?: "inet" | "inet6";
			/**
			 * Format: int32
			 * @description Maximum hop count.
			 * @example 30
			 */
			maxHops?: number;
			/**
			 * Format: int32
			 * @description Probe payload size in bytes.
			 * @example 56
			 */
			packetSizeBytes?: number;
			/**
			 * Format: int32
			 * @description Destination port for UDP/TCP traceroute.
			 * @example 33434
			 */
			port?: number;
			/**
			 * @description Traceroute protocol.
			 * @example icmp
			 * @enum {string}
			 */
			protocol?: "icmp" | "udp" | "tcp";
			/**
			 * Format: int32
			 * @description Probe attempts per hop.
			 * @example 3
			 */
			queriesPerHop?: number;
			/**
			 * Format: int32
			 * @description Traceroute timeout in milliseconds.
			 * @example 3000
			 */
			timeoutMs?: number;
		};
		Config: {
			ipFamily?: string;
			/** Format: int32 */
			packetCount: number;
			/** Format: int32 */
			packetSizeBytes: number;
			/** Format: int32 */
			timeoutMs: number;
		};
		CreateCheckInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/CreateCheckInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Optional check description.
			 * @example Latency and loss to controller API.
			 */
			description?: string;
			/**
			 * Format: int32
			 * @description Check interval in seconds.
			 * @example 30
			 */
			intervalSeconds: number;
			/** @description Existing project label IDs to attach to the check. */
			labelIds?: string[] | null;
			/**
			 * @description Check display name.
			 * @example api-latency
			 */
			name: string;
			/** @description Ping-specific check configuration. Omitted fields use defaults. */
			pingConfig?: components["schemas"]["CheckPingConfigInput"];
			/** @description Selector object for later probe matching. */
			selector?: {
				[key: string]: unknown;
			};
			/**
			 * @description Hostname or address to check.
			 * @example api.netstamp.io
			 */
			target: string;
			/** @description Traceroute-specific check configuration. Omitted fields use defaults. */
			tracerouteConfig?: components["schemas"]["CheckTracerouteConfigInput"];
			/**
			 * @description Check type.
			 * @example ping
			 * @enum {string}
			 */
			type: "ping" | "traceroute";
		};
		CreateLabelInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/CreateLabelInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Label key.
			 * @example region
			 */
			key?: string;
			/**
			 * @description Label value.
			 * @example tokyo
			 */
			value?: string;
		};
		CreateProbeInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/CreateProbeInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Whether the probe is enabled. Defaults to true when omitted.
			 * @default true
			 * @example true
			 */
			enabled: boolean;
			/** @description Existing project label IDs to attach to the probe. */
			labelIds?: string[] | null;
			/**
			 * Format: double
			 * @description Probe latitude. Must be provided with longitude.
			 * @example 35.6762
			 */
			latitude?: number;
			/**
			 * Format: double
			 * @description Probe longitude. Must be provided with latitude.
			 * @example 139.6503
			 */
			longitude?: number;
			/**
			 * @description Probe display name.
			 * @example tokyo-vps-1
			 */
			name?: string;
			/** @description ISO 3166-2 subdivision code, e.g. JP-12 for Chiba Prefecture, Japan */
			subdivisionCode?: string;
		};
		CreateProbeOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/CreateProbeOutputBody.json
			 */
			readonly $schema?: string;
			probe: components["schemas"]["Probe"];
			secret: string;
		};
		CreateProjectInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/CreateProjectInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Project display name.
			 * @example Engineering
			 */
			name?: string;
			/**
			 * @description Stable project slug.
			 * @example engineering
			 */
			slug?: string;
		};
		ErrorDetail: {
			/** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
			location?: string;
			/** @description Error message text */
			message?: string;
			/** @description The value at the given location */
			value?: unknown;
		};
		ErrorModel: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/ErrorModel.json
			 */
			readonly $schema?: string;
			/**
			 * @description A human-readable explanation specific to this occurrence of the problem.
			 * @example Property foo is required but is missing.
			 */
			detail?: string;
			/** @description Optional list of individual error details */
			errors?: components["schemas"]["ErrorDetail"][] | null;
			/**
			 * Format: uri
			 * @description A URI reference that identifies the specific occurrence of the problem.
			 * @example https://example.com/error-log/abc123
			 */
			instance?: string;
			/**
			 * Format: int64
			 * @description HTTP status code
			 * @example 400
			 */
			status?: number;
			/**
			 * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
			 * @example Bad Request
			 */
			title?: string;
			/**
			 * Format: uri
			 * @description A URI reference to human-readable documentation for the error.
			 * @default about:blank
			 * @example https://example.com/errors/example
			 */
			type: string;
		};
		HealthBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/HealthBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Current health status.
			 * @example ok
			 */
			status: string;
		};
		HeartbeatOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/HeartbeatOutputBody.json
			 */
			readonly $schema?: string;
			/** Format: date-time */
			serverTime: string;
		};
		HelloOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/HelloOutputBody.json
			 */
			readonly $schema?: string;
			config: components["schemas"]["RuntimeConfig"];
			minimumSupportedAgentVersion: string;
			/** Format: date-time */
			serverTime: string;
		};
		Label: {
			/** Format: date-time */
			createdAt: string;
			id: string;
			key: string;
			projectId: string;
			/** Format: date-time */
			updatedAt: string;
			value: string;
		};
		LabelOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/LabelOutputBody.json
			 */
			readonly $schema?: string;
			label: components["schemas"]["Label"];
		};
		ListChecksOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/ListChecksOutputBody.json
			 */
			readonly $schema?: string;
			checks: components["schemas"]["Check"][] | null;
		};
		ListLabelsOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/ListLabelsOutputBody.json
			 */
			readonly $schema?: string;
			labels: components["schemas"]["Label"][] | null;
		};
		ListMembersOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/ListMembersOutputBody.json
			 */
			readonly $schema?: string;
			members: components["schemas"]["Member"][] | null;
		};
		ListProbesOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/ListProbesOutputBody.json
			 */
			readonly $schema?: string;
			probes: components["schemas"]["Probe"][] | null;
		};
		ListProjectsOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/ListProjectsOutputBody.json
			 */
			readonly $schema?: string;
			projects: components["schemas"]["Project"][] | null;
		};
		LoginInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/LoginInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * Format: email
			 * @description Email address used to sign in. It is normalized before lookup.
			 * @example user@example.com
			 */
			email: string;
			/**
			 * @description Plain-text password to verify. It is never returned by the API.
			 * @example correct-horse-battery-staple
			 */
			password: string;
		};
		LoginOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/LoginOutputBody.json
			 */
			readonly $schema?: string;
			/** @description Authenticated user. */
			user: components["schemas"]["UserResponse"];
		};
		MeOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/MeOutputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Always true when the session cookie is valid.
			 * @example true
			 */
			authenticated: boolean;
			/** @description Current user fetched live from the database. */
			user: components["schemas"]["UserResponse"];
		};
		Member: {
			/** Format: date-time */
			createdAt: string;
			id: string;
			projectId: string;
			role: string;
			/** Format: date-time */
			updatedAt: string;
			userId: string;
		};
		MemberOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/MemberOutputBody.json
			 */
			readonly $schema?: string;
			member: components["schemas"]["Member"];
		};
		PingResultBody: {
			/**
			 * Format: int32
			 * @description Total check duration in milliseconds.
			 * @example 1000
			 */
			durationMs: number;
			/**
			 * @description Optional machine-readable error code.
			 * @example icmp_timeout
			 */
			errorCode?: string;
			/**
			 * @description Optional executor error message.
			 * @example request timed out
			 */
			errorMessage?: string;
			/**
			 * Format: date-time
			 * @description UTC time when the ping check finished.
			 * @example 2026-05-13T10:00:01Z
			 */
			finishedAt: string;
			/**
			 * @description IP family used for the check.
			 * @example inet
			 * @enum {string}
			 */
			ipFamily?: "inet" | "inet6";
			/**
			 * Format: double
			 * @description Packet loss percentage.
			 * @example 0
			 */
			lossPercent: number;
			/**
			 * Format: int32
			 * @description Packets received.
			 * @example 4
			 */
			receivedCount: number;
			/**
			 * Format: ip
			 * @description Resolved IP address used for the ping.
			 * @example 1.1.1.1
			 */
			resolvedIp?: string;
			/**
			 * Format: double
			 * @description Average RTT in milliseconds.
			 * @example 12.3
			 */
			rttAvgMs?: number;
			/**
			 * Format: double
			 * @description Maximum RTT in milliseconds.
			 * @example 15.6
			 */
			rttMaxMs?: number;
			/**
			 * Format: double
			 * @description Median RTT in milliseconds.
			 * @example 12
			 */
			rttMedianMs?: number;
			/**
			 * Format: double
			 * @description Minimum RTT in milliseconds.
			 * @example 10.1
			 */
			rttMinMs?: number;
			/** @description RTT sample values in milliseconds. */
			rttSamplesMs?: number[] | null;
			/**
			 * Format: double
			 * @description RTT standard deviation in milliseconds.
			 * @example 1.7
			 */
			rttStddevMs?: number;
			/**
			 * Format: int32
			 * @description Packets sent.
			 * @example 4
			 */
			sentCount: number;
			/**
			 * Format: date-time
			 * @description UTC time when the ping check started.
			 * @example 2026-05-13T10:00:00Z
			 */
			startedAt: string;
			/**
			 * @description Ping result status.
			 * @example successful
			 * @enum {string}
			 */
			status: "successful" | "timeout" | "error";
		};
		Probe: {
			/** Format: date-time */
			createdAt: string;
			enabled: boolean;
			id: string;
			labels: components["schemas"]["Label"][] | null;
			/** Format: double */
			latitude: number | null;
			/** Format: double */
			longitude: number | null;
			name: string;
			projectId: string;
			status: components["schemas"]["Status"];
			subdivisionCode: string | null;
			/** Format: date-time */
			updatedAt: string;
		};
		ProbeOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/ProbeOutputBody.json
			 */
			readonly $schema?: string;
			probe: components["schemas"]["Probe"];
		};
		Project: {
			/** Format: date-time */
			createdAt: string;
			createdByUserId: string;
			id: string;
			name: string;
			slug: string;
			/** Format: date-time */
			updatedAt: string;
		};
		ProjectOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/ProjectOutputBody.json
			 */
			readonly $schema?: string;
			project: components["schemas"]["Project"];
		};
		QueryMetadataBody: {
			/**
			 * Format: int64
			 * @example 1778662800000
			 */
			from: number;
			/**
			 * Format: int32
			 * @example 600
			 */
			maxDataPoints: number;
			/** @example bucket */
			resolution: string;
			/**
			 * Format: int64
			 * @example 1778749200000
			 */
			to: number;
			/**
			 * Format: int64
			 * @example 487
			 */
			totalPoints: number;
		};
		QueryPingSeriesBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/QueryPingSeriesBody.json
			 */
			readonly $schema?: string;
			query: components["schemas"]["QueryMetadataBody"];
			series: components["schemas"]["SeriesBody"][] | null;
		};
		QueryTracerouteRunsBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/QueryTracerouteRunsBody.json
			 */
			readonly $schema?: string;
			query: components["schemas"]["TracerouteRunQueryMetadataBody"];
			runs: components["schemas"]["TracerouteResultRunBody"][] | null;
		};
		RegisterInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/RegisterInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Name shown in the app.
			 * @example Jane Doe
			 */
			displayName: string;
			/**
			 * Format: email
			 * @description Email address used to sign in.
			 * @example user@example.com
			 */
			email: string;
			/**
			 * @description Plain-text password. It is stored only as an Argon2id hash.
			 * @example correct-horse-battery-staple
			 */
			password: string;
		};
		RegisterOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/RegisterOutputBody.json
			 */
			readonly $schema?: string;
			/** @description Created user. */
			user: components["schemas"]["UserResponse"];
		};
		RootBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/RootBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Human-readable API status message.
			 * @example Netstamp API is running
			 */
			message: string;
		};
		RotateSecretOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/RotateSecretOutputBody.json
			 */
			readonly $schema?: string;
			probe: components["schemas"]["Probe"];
			secret: string;
		};
		RuntimeConfig: {
			/** Format: int32 */
			assignmentPollIntervalSeconds: number;
			/** Format: int32 */
			heartbeatIntervalSeconds: number;
			/** Format: int32 */
			initialBackoffSeconds: number;
			/** Format: int32 */
			maxAttempts: number;
			/** Format: int32 */
			maxBackoffSeconds: number;
			/** Format: int32 */
			maxConcurrentWorkers: number;
		};
		RuntimeResultGroupBody: {
			/**
			 * Format: uuid
			 * @description Assigned check ID.
			 * @example 44444444-4444-4444-4444-444444444444
			 */
			checkId: string;
			/** @description Ping result payloads for this check. */
			ping?: components["schemas"]["PingResultBody"][] | null;
			/** @description Traceroute result payloads for this check. */
			traceroute?: components["schemas"]["RuntimeTracerouteResultBody"][] | null;
			/**
			 * @description Check result type. Must match the assigned check type.
			 * @example ping
			 * @enum {string}
			 */
			type: "ping" | "traceroute";
		};
		RuntimeStatusBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/RuntimeStatusBody.json
			 */
			readonly $schema?: string;
			/** @description Probe local or observed interface addresses. */
			addrs?: string[] | null;
			/**
			 * @description Probe agent version.
			 * @example netstamp-probe/0.1.0
			 */
			agentVersion?: string;
			/**
			 * @description Observed autonomous system.
			 * @example AS15169 Google LLC
			 */
			as?: string;
			/**
			 * Format: ip
			 * @description Observed public IPv4 address.
			 * @example 203.0.113.10
			 */
			publicV4?: string;
			/**
			 * Format: ip
			 * @description Observed public IPv6 address.
			 * @example 2001:db8::10
			 */
			publicV6?: string;
		};
		RuntimeTracerouteHopBody: {
			/**
			 * Format: ip
			 * @description Hop IP address.
			 * @example 192.0.2.1
			 */
			address?: string;
			/**
			 * @description Optional machine-readable hop error code.
			 * @example hop_timeout
			 */
			errorCode?: string;
			/**
			 * @description Optional hop error message.
			 * @example request timed out
			 */
			errorMessage?: string;
			/**
			 * Format: int32
			 * @description One-based hop index.
			 * @example 1
			 */
			hopIndex: number;
			/**
			 * @description Hop reverse DNS hostname.
			 * @example gateway.local
			 */
			hostname?: string;
			/**
			 * Format: double
			 * @description Probe loss percentage for this hop.
			 * @example 0
			 */
			lossPercent: number;
			/**
			 * Format: int32
			 * @description Probe attempts received for this hop.
			 * @example 3
			 */
			receivedCount: number;
			/**
			 * Format: double
			 * @description Average RTT in milliseconds.
			 * @example 1.7
			 */
			rttAvgMs?: number;
			/**
			 * Format: double
			 * @description Maximum RTT in milliseconds.
			 * @example 1.9
			 */
			rttMaxMs?: number;
			/**
			 * Format: double
			 * @description Median RTT in milliseconds.
			 * @example 1.7
			 */
			rttMedianMs?: number;
			/**
			 * Format: double
			 * @description Minimum RTT in milliseconds.
			 * @example 1.5
			 */
			rttMinMs?: number;
			/** @description RTT sample values in milliseconds. */
			rttSamplesMs?: number[] | null;
			/**
			 * Format: double
			 * @description RTT standard deviation in milliseconds.
			 * @example 0.2
			 */
			rttStddevMs?: number;
			/**
			 * Format: int32
			 * @description Probe attempts sent for this hop.
			 * @example 3
			 */
			sentCount: number;
		};
		RuntimeTracerouteResultBody: {
			/**
			 * @description Whether the traceroute reached the destination.
			 * @example false
			 */
			destinationReached: boolean;
			/**
			 * Format: int32
			 * @description Total check duration in milliseconds.
			 * @example 4000
			 */
			durationMs: number;
			/**
			 * @description Optional machine-readable error code.
			 * @example destination_unreached
			 */
			errorCode?: string;
			/**
			 * @description Optional executor error message.
			 * @example destination was not reached before max hops
			 */
			errorMessage?: string;
			/**
			 * Format: date-time
			 * @description UTC time when the traceroute check finished.
			 * @example 2026-05-13T10:00:04Z
			 */
			finishedAt: string;
			/**
			 * Format: int32
			 * @description Observed hop count.
			 * @example 12
			 */
			hopCount: number;
			/** @description Per-hop traceroute samples. */
			hops?: components["schemas"]["RuntimeTracerouteHopBody"][] | null;
			/**
			 * @description IP family used for the check.
			 * @example inet
			 * @enum {string}
			 */
			ipFamily?: "inet" | "inet6";
			/**
			 * Format: ip
			 * @description Resolved destination IP address.
			 * @example 93.184.216.34
			 */
			resolvedIp?: string;
			/**
			 * Format: date-time
			 * @description UTC time when the traceroute check started.
			 * @example 2026-05-13T10:00:00Z
			 */
			startedAt: string;
			/**
			 * @description Traceroute result status.
			 * @example partial
			 * @enum {string}
			 */
			status: "successful" | "timeout" | "error" | "partial";
		};
		SeriesBody: {
			labels: {
				[key: string]: string;
			};
			/** @example rttAvgMs */
			name: string;
			/** @description Tuple points in the shape [epochMilliseconds, value]. */
			points: (number[] | null)[] | null;
			/** @example ms */
			unit: string;
		};
		Status: {
			addrs: string[] | null;
			agentVersion: string | null;
			as: string | null;
			/** Format: date-time */
			lastSeenAt: string | null;
			probeId: string;
			/** Format: ip */
			publicV4: string | null;
			/** Format: ip */
			publicV6: string | null;
			state: string;
			/** Format: date-time */
			updatedAt: string;
		};
		SubmitResultsBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/SubmitResultsBody.json
			 */
			readonly $schema?: string;
			/** @description Result groups keyed by check and check type. */
			results: components["schemas"]["RuntimeResultGroupBody"][] | null;
		};
		SubmitResultsOutputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/SubmitResultsOutputBody.json
			 */
			readonly $schema?: string;
			/** Format: int64 */
			accepted: number;
			/** Format: date-time */
			serverTime: string;
		};
		TracerouteConfig: {
			ipFamily?: string;
			/** Format: int32 */
			maxHops: number;
			/** Format: int32 */
			packetSizeBytes: number;
			/** Format: int32 */
			port: number;
			protocol: string;
			/** Format: int32 */
			queriesPerHop: number;
			/** Format: int32 */
			timeoutMs: number;
		};
		TracerouteResultHopBody: {
			/** Format: ip */
			address?: string;
			errorCode?: string;
			errorMessage?: string;
			/** Format: int32 */
			hopIndex: number;
			hostname?: string;
			/** Format: double */
			lossPercent: number;
			/** Format: int32 */
			receivedCount: number;
			/** Format: double */
			rttAvgMs?: number;
			/** Format: double */
			rttMaxMs?: number;
			/** Format: double */
			rttMedianMs?: number;
			/** Format: double */
			rttMinMs?: number;
			rttSamplesMs?: number[] | null;
			/** Format: double */
			rttStddevMs?: number;
			/** Format: int32 */
			sentCount: number;
		};
		TracerouteResultRunBody: {
			destinationReached: boolean;
			/** Format: int32 */
			durationMs: number;
			errorCode?: string;
			errorMessage?: string;
			/** Format: date-time */
			finishedAt: string;
			/** Format: int32 */
			hopCount: number;
			hops: components["schemas"]["TracerouteResultHopBody"][] | null;
			ipFamily?: string;
			/** Format: ip */
			resolvedIp?: string;
			/** Format: date-time */
			startedAt: string;
			status: string;
		};
		TracerouteRunQueryMetadataBody: {
			/**
			 * Format: int64
			 * @example 1778662800000
			 */
			from: number;
			/**
			 * Format: int32
			 * @example 100
			 */
			limit: number;
			/**
			 * Format: int64
			 * @example 1778662800000
			 */
			nextCursor?: number;
			/**
			 * Format: int64
			 * @example 1778749200000
			 */
			to: number;
		};
		UpdateCheckInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/UpdateCheckInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Optional check description.
			 * @example Latency and loss to controller API.
			 */
			description?: string;
			/**
			 * Format: int32
			 * @description Check interval in seconds.
			 * @example 30
			 */
			intervalSeconds?: number;
			/** @description Replacement project label IDs for the check. */
			labelIds?: string[];
			/**
			 * @description Check display name.
			 * @example api-latency
			 */
			name?: string;
			/** @description Ping-specific check configuration fields to update. */
			pingConfig?: components["schemas"]["CheckPingConfigInput"];
			/** @description Selector object for later probe matching. */
			selector?: {
				[key: string]: unknown;
			};
			/**
			 * @description Hostname or address to check.
			 * @example api.netstamp.io
			 */
			target?: string;
			/** @description Traceroute-specific check configuration fields to update. */
			tracerouteConfig?: components["schemas"]["CheckTracerouteConfigInput"];
			/**
			 * @description Check type. Cannot be changed after creation in v1.
			 * @example ping
			 * @enum {string}
			 */
			type?: "ping" | "traceroute";
		};
		UpdateLabelInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/UpdateLabelInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Label key.
			 * @example region
			 */
			key?: string;
			/**
			 * @description Label value.
			 * @example tokyo
			 */
			value?: string;
		};
		UpdateMemberRoleInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/UpdateMemberRoleInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Project member role.
			 * @example viewer
			 * @enum {string}
			 */
			role?: "viewer" | "editor" | "admin";
		};
		UpdateProbeInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/UpdateProbeInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Whether the probe is enabled. Omitted values leave the current setting unchanged.
			 * @example true
			 */
			enabled?: boolean;
			/** @description Existing project label IDs to attach to the probe. */
			labelIds?: string[];
			/**
			 * Format: double
			 * @description Probe latitude. Must be provided with longitude.
			 * @example 35.6762
			 */
			latitude?: number;
			/**
			 * Format: double
			 * @description Probe longitude. Must be provided with latitude.
			 * @example 139.6503
			 */
			longitude?: number;
			/**
			 * @description Probe display name.
			 * @example tokyo-vps-1
			 */
			name?: string;
			/** @description ISO 3166-2 subdivision code, e.g. JP-12 for Chiba Prefecture, Japan */
			subdivisionCode?: string;
		};
		UpdateProjectInputBody: {
			/**
			 * Format: uri
			 * @description A URL to the JSON Schema for this object.
			 * @example /api/v1/schemas/UpdateProjectInputBody.json
			 */
			readonly $schema?: string;
			/**
			 * @description Project display name.
			 * @example Engineering
			 */
			name?: string;
			/**
			 * @description Stable project slug.
			 * @example engineering
			 */
			slug?: string;
		};
		UserResponse: {
			/**
			 * @description Name shown in the app.
			 * @example Jane Doe
			 */
			displayName: string;
			/**
			 * Format: email
			 * @description Normalized email address used to sign in.
			 * @example user@example.com
			 */
			email: string;
			/**
			 * Format: uuid
			 * @description User UUID.
			 * @example 11111111-1111-1111-1111-111111111111
			 */
			id: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getAPIStatus: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RootBody"];
				};
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	loginUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginInputBody"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LoginOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	logoutUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Error */
			default: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	getCurrentUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MeOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	registerUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RegisterInputBody"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RegisterOutputBody"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HealthBody"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Service Unavailable */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	listProjects: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ListProjectsOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	createProject: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateProjectInputBody"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	getProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	deleteProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	updateProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateProjectInputBody"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	listProjectChecks: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project slug or lowercase UUID. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ListChecksOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	createProjectCheck: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project slug or lowercase UUID. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateCheckInputBody"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CheckOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	getProjectCheck: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project slug or lowercase UUID. */
				ref: string;
				/** @description Check ID. */
				check_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CheckOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	deleteProjectCheck: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project slug or lowercase UUID. */
				ref: string;
				/** @description Check ID. */
				check_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	updateProjectCheck: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project slug or lowercase UUID. */
				ref: string;
				/** @description Check ID. */
				check_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCheckInputBody"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CheckOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	listProjectLabels: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ListLabelsOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	createProjectLabel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateLabelInputBody"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LabelOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	deleteProjectLabel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
				/** @description Label ID. */
				label_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	updateProjectLabel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
				/** @description Label ID. */
				label_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateLabelInputBody"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LabelOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	listProjectMembers: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ListMembersOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	addProjectMember: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AddMemberInputBody"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemberOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	removeProjectMember: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
				/** @description User ID. */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	updateProjectMemberRole: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
				/** @description User ID. */
				user_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateMemberRoleInputBody"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemberOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	listProjectProbes: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ListProbesOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	createProjectProbe: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateProbeInputBody"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CreateProbeOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	getProjectProbe: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
				/** @description Probe ID. */
				probe_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProbeOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	deleteProjectProbe: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
				/** @description Probe ID. */
				probe_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	updateProjectProbe: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
				/** @description Probe ID. */
				probe_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateProbeInputBody"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProbeOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	rotateProjectProbeSecret: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Project UUID or slug. */
				ref: string;
				/** @description Probe ID. */
				probe_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RotateSecretOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	queryProjectPingResultSeries: {
		parameters: {
			query: {
				/** @description Probe ID to query. */
				probeId: string;
				/** @description Check ID to query. */
				checkId: string;
				/** @description Inclusive range start as epoch milliseconds. */
				from?: number;
				/** @description Exclusive range end as epoch milliseconds. */
				to?: number;
				/** @description Ping metric to aggregate: rttAvgMs, lossPercent, or successRate. */
				metric?: string;
				/** @description Maximum target points per series. */
				maxDataPoints?: number;
			};
			header?: never;
			path: {
				/** @description Project ID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["QueryPingSeriesBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	queryProjectTracerouteResultRuns: {
		parameters: {
			query: {
				/** @description Probe ID to query. */
				probeId: string;
				/** @description Check ID to query. */
				checkId: string;
				/** @description Inclusive range start as epoch milliseconds. */
				from?: number;
				/** @description Exclusive range end as epoch milliseconds. */
				to?: number;
				/** @description Maximum traceroute runs to return. */
				limit?: number;
				/** @description Pagination cursor as a run startedAt epoch millisecond timestamp. */
				cursor?: number;
			};
			header?: never;
			path: {
				/** @description Project ID or slug. */
				ref: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["QueryTracerouteRunsBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	listProbeRuntimeAssignments: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Probe ID. */
				probe_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AssignmentsOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	probeRuntimeHeartbeat: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Probe ID. */
				probe_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RuntimeStatusBody"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HeartbeatOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	probeRuntimeHello: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Probe ID. */
				probe_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HelloOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
	submitProbeRuntimeResults: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Probe ID. */
				probe_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SubmitResultsBody"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SubmitResultsOutputBody"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Forbidden */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/problem+json": components["schemas"]["ErrorModel"];
				};
			};
		};
	};
}
