/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get API status */
		get: operations["getAPIStatus"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Login user
		 * @description Verify an email and password pair, then set an HTTP-only session cookie for the authenticated user. Invalid credentials always return the same unauthorized response.
		 */
		post: operations["loginUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Logout user
		 * @description Clear the HTTP-only session cookie.
		 */
		post: operations["logoutUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get current user
		 * @description Return the user identity embedded in a valid session cookie.
		 */
		get: operations["getCurrentUser"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/auth/register": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Register user
		 * @description Create a user account with a normalized email address, display name, and password. On success, sets an HTTP-only session cookie for immediate API access.
		 */
		post: operations["registerUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/healthz": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get health status */
		get: operations["getHealth"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List projects */
		get: operations["listProjects"];
		put?: never;
		/** Create project */
		post: operations["createProject"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get project */
		get: operations["getProject"];
		put?: never;
		post?: never;
		/** Delete project */
		delete: operations["deleteProject"];
		options?: never;
		head?: never;
		/** Update project */
		patch: operations["updateProject"];
		trace?: never;
	};
	"/projects/{ref}/checks": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project checks */
		get: operations["listProjectChecks"];
		put?: never;
		/** Create project check */
		post: operations["createProjectCheck"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/checks/{check_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get project check */
		get: operations["getProjectCheck"];
		put?: never;
		post?: never;
		/** Delete project check */
		delete: operations["deleteProjectCheck"];
		options?: never;
		head?: never;
		/** Update project check */
		patch: operations["updateProjectCheck"];
		trace?: never;
	};
	"/projects/{ref}/labels": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project labels */
		get: operations["listProjectLabels"];
		put?: never;
		/** Create project label */
		post: operations["createProjectLabel"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/labels/{label_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete project label */
		delete: operations["deleteProjectLabel"];
		options?: never;
		head?: never;
		/** Update project label */
		patch: operations["updateProjectLabel"];
		trace?: never;
	};
	"/projects/{ref}/members": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project members */
		get: operations["listProjectMembers"];
		put?: never;
		/** Add project member */
		post: operations["addProjectMember"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/members/{user_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Remove project member */
		delete: operations["removeProjectMember"];
		options?: never;
		head?: never;
		/** Update project member role */
		patch: operations["updateProjectMemberRole"];
		trace?: never;
	};
	"/projects/{ref}/probes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List project probes */
		get: operations["listProjectProbes"];
		put?: never;
		/** Create project probe */
		post: operations["createProjectProbe"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/probes/{probe_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get project probe */
		get: operations["getProjectProbe"];
		put?: never;
		post?: never;
		/** Delete project probe */
		delete: operations["deleteProjectProbe"];
		options?: never;
		head?: never;
		/** Update project probe */
		patch: operations["updateProjectProbe"];
		trace?: never;
	};
	"/projects/{ref}/probes/{probe_id}/secret-rotations": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Rotate project probe secret */
		post: operations["rotateProjectProbeSecret"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/results/ping/series": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Query project ping result series */
		get: operations["queryProjectPingResultSeries"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/projects/{ref}/results/traceroute/runs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Query project traceroute result runs */
		get: operations["queryProjectTracerouteResultRuns"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/runtime/probes/{probe_id}/assignments": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List probe runtime assignments */
		get: operations["listProbeRuntimeAssignments"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/runtime/probes/{probe_id}/heartbeat": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Update probe runtime status */
		post: operations["probeRuntimeHeartbeat"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/runtime/probes/{probe_id}/hello": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Start probe runtime session */
		post: operations["probeRuntimeHello"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/runtime/probes/{probe_id}/results": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Submit probe runtime results */
		post: operations["submitProbeRuntimeResults"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/**
		 * @example {
		 *       "message": "Netstamp API is running"
		 *     }
		 */
		APIStatusResponse: {
			/** @enum {string} */
			message: "Netstamp API is running";
		};
		/**
		 * @example {
		 *       "userId": "11111111-1111-1111-1111-111111111111",
		 *       "role": "viewer"
		 *     }
		 */
		AddProjectMemberRequest: {
			userId: components["schemas"]["uuid"];
			/** @enum {string} */
			role: "admin" | "editor" | "viewer";
		};
		/**
		 * @example {
		 *       "id": "77777777-7777-7777-7777-777777777777",
		 *       "projectId": "22222222-2222-2222-2222-222222222222",
		 *       "checkVersion": "01HXYZ7K6P4E4M3F0CB1W9DYJ5",
		 *       "selectorVersion": "01HXYZ7K6P4E4M3F0CB1W9DYJ6",
		 *       "check": {
		 *         "id": "44444444-4444-4444-4444-444444444444",
		 *         "projectId": "22222222-2222-2222-2222-222222222222",
		 *         "name": "api-latency",
		 *         "type": "ping",
		 *         "target": "api.netstamp.io",
		 *         "intervalSeconds": 30,
		 *         "labels": [],
		 *         "createdAt": "2026-05-13T10:00:00Z",
		 *         "updatedAt": "2026-05-13T10:00:00Z",
		 *         "pingConfig": {
		 *           "packetCount": 4,
		 *           "packetSizeBytes": 56,
		 *           "timeoutMs": 3000
		 *         }
		 *       }
		 *     }
		 */
		Assignment: {
			id: components["schemas"]["uuid"];
			projectId: components["schemas"]["uuid"];
			checkVersion: string;
			selectorVersion: string;
			check?: components["schemas"]["Check"];
			probe?: components["schemas"]["Probe"];
		};
		/**
		 * @example {
		 *       "user": {
		 *         "id": "11111111-1111-1111-1111-111111111111",
		 *         "email": "user@example.com",
		 *         "displayName": "Jane Doe"
		 *       }
		 *     }
		 */
		AuthUserResponse: {
			user: components["schemas"]["User"];
		};
		/**
		 * @example {
		 *       "id": "44444444-4444-4444-4444-444444444444",
		 *       "projectId": "22222222-2222-2222-2222-222222222222",
		 *       "name": "api-latency",
		 *       "type": "ping",
		 *       "target": "api.netstamp.io",
		 *       "selector": {
		 *         "region": "tokyo"
		 *       },
		 *       "description": "Latency and loss to controller API.",
		 *       "intervalSeconds": 30,
		 *       "labels": [
		 *         {
		 *           "id": "66666666-6666-6666-6666-666666666666",
		 *           "projectId": "22222222-2222-2222-2222-222222222222",
		 *           "key": "region",
		 *           "value": "tokyo",
		 *           "createdAt": "2026-05-13T10:00:00Z",
		 *           "updatedAt": "2026-05-13T10:00:00Z"
		 *         }
		 *       ],
		 *       "createdAt": "2026-05-13T10:00:00Z",
		 *       "updatedAt": "2026-05-13T10:00:00Z",
		 *       "pingConfig": {
		 *         "packetCount": 4,
		 *         "packetSizeBytes": 56,
		 *         "timeoutMs": 3000,
		 *         "ipFamily": "inet"
		 *       }
		 *     }
		 */
		Check: {
			id: components["schemas"]["uuid"];
			projectId: components["schemas"]["uuid"];
			name: string;
			/** @enum {string} */
			type: "ping" | "traceroute";
			target: string;
			selector?: Record<string, never>;
			description?: string;
			/** Format: int32 */
			intervalSeconds: number;
			labels: components["schemas"]["Label"][];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
			pingConfig?: components["schemas"]["PingConfig"];
			tracerouteConfig?: components["schemas"]["TracerouteConfig"];
		};
		/**
		 * @example {
		 *       "checks": [
		 *         {
		 *           "id": "44444444-4444-4444-4444-444444444444",
		 *           "projectId": "22222222-2222-2222-2222-222222222222",
		 *           "name": "api-latency",
		 *           "type": "ping",
		 *           "target": "api.netstamp.io",
		 *           "selector": {
		 *             "region": "tokyo"
		 *           },
		 *           "intervalSeconds": 30,
		 *           "labels": [],
		 *           "createdAt": "2026-05-13T10:00:00Z",
		 *           "updatedAt": "2026-05-13T10:00:00Z",
		 *           "pingConfig": {
		 *             "packetCount": 4,
		 *             "packetSizeBytes": 56,
		 *             "timeoutMs": 3000,
		 *             "ipFamily": "inet"
		 *           }
		 *         }
		 *       ]
		 *     }
		 */
		CheckListResponse: {
			checks: components["schemas"]["Check"][];
		};
		/**
		 * @example {
		 *       "check": {
		 *         "id": "44444444-4444-4444-4444-444444444444",
		 *         "projectId": "22222222-2222-2222-2222-222222222222",
		 *         "name": "api-latency",
		 *         "type": "ping",
		 *         "target": "api.netstamp.io",
		 *         "selector": {
		 *           "region": "tokyo"
		 *         },
		 *         "description": "Latency and loss to controller API.",
		 *         "intervalSeconds": 30,
		 *         "labels": [],
		 *         "createdAt": "2026-05-13T10:00:00Z",
		 *         "updatedAt": "2026-05-13T10:00:00Z",
		 *         "pingConfig": {
		 *           "packetCount": 4,
		 *           "packetSizeBytes": 56,
		 *           "timeoutMs": 3000,
		 *           "ipFamily": "inet"
		 *         }
		 *       }
		 *     }
		 */
		CheckResponse: {
			check: components["schemas"]["Check"];
		};
		/**
		 * @example {
		 *       "name": "api-latency",
		 *       "type": "ping",
		 *       "target": "api.netstamp.io",
		 *       "selector": {
		 *         "region": "tokyo"
		 *       },
		 *       "description": "Latency and loss to controller API.",
		 *       "intervalSeconds": 30,
		 *       "labelIds": [
		 *         "66666666-6666-6666-6666-666666666666"
		 *       ],
		 *       "pingConfig": {
		 *         "packetCount": 4,
		 *         "packetSizeBytes": 56,
		 *         "timeoutMs": 3000,
		 *         "ipFamily": "inet"
		 *       }
		 *     }
		 */
		CreateCheckRequest: {
			name: string;
			/** @enum {string} */
			type: "ping" | "traceroute";
			target: string;
			selector?: Record<string, never>;
			description?: string;
			/** Format: int32 */
			intervalSeconds: number;
			labelIds?: components["schemas"]["uuid"][];
			pingConfig?: components["schemas"]["PingConfigPatch"];
			tracerouteConfig?: components["schemas"]["TracerouteConfigPatch"];
		};
		/**
		 * @example {
		 *       "key": "region",
		 *       "value": "tokyo"
		 *     }
		 */
		CreateLabelRequest: {
			key: string;
			value: string;
		};
		/**
		 * @example {
		 *       "name": "tokyo-vps-1",
		 *       "enabled": true,
		 *       "subdivisionCode": "JP-13",
		 *       "latitude": 35.6762,
		 *       "longitude": 139.6503,
		 *       "labelIds": [
		 *         "66666666-6666-6666-6666-666666666666"
		 *       ]
		 *     }
		 */
		CreateProbeRequest: {
			name: string;
			/** @default true */
			enabled: boolean;
			subdivisionCode?: string;
			/** Format: double */
			latitude?: number;
			/** Format: double */
			longitude?: number;
			labelIds?: components["schemas"]["uuid"][];
		};
		/**
		 * @example {
		 *       "name": "Engineering",
		 *       "slug": "engineering"
		 *     }
		 */
		CreateProjectRequest: {
			name: string;
			slug: string;
		};
		/**
		 * @example {
		 *       "authenticated": true,
		 *       "user": {
		 *         "id": "11111111-1111-1111-1111-111111111111",
		 *         "email": "user@example.com",
		 *         "displayName": "Jane Doe"
		 *       }
		 *     }
		 */
		CurrentUserResponse: {
			/** @enum {boolean} */
			authenticated: true;
			user: components["schemas"]["User"];
		};
		/**
		 * @example {
		 *       "status": "ok"
		 *     }
		 */
		HealthResponse: {
			/** @enum {string} */
			status: "ok";
		};
		/**
		 * @example {
		 *       "id": "66666666-6666-6666-6666-666666666666",
		 *       "projectId": "22222222-2222-2222-2222-222222222222",
		 *       "key": "region",
		 *       "value": "tokyo",
		 *       "createdAt": "2026-05-13T10:00:00Z",
		 *       "updatedAt": "2026-05-13T10:00:00Z"
		 *     }
		 */
		Label: {
			id: components["schemas"]["uuid"];
			projectId: components["schemas"]["uuid"];
			key: string;
			value: string;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		/**
		 * @example {
		 *       "labels": [
		 *         {
		 *           "id": "66666666-6666-6666-6666-666666666666",
		 *           "projectId": "22222222-2222-2222-2222-222222222222",
		 *           "key": "region",
		 *           "value": "tokyo",
		 *           "createdAt": "2026-05-13T10:00:00Z",
		 *           "updatedAt": "2026-05-13T10:00:00Z"
		 *         }
		 *       ]
		 *     }
		 */
		LabelListResponse: {
			labels: components["schemas"]["Label"][];
		};
		/**
		 * @example {
		 *       "label": {
		 *         "id": "66666666-6666-6666-6666-666666666666",
		 *         "projectId": "22222222-2222-2222-2222-222222222222",
		 *         "key": "region",
		 *         "value": "tokyo",
		 *         "createdAt": "2026-05-13T10:00:00Z",
		 *         "updatedAt": "2026-05-13T10:00:00Z"
		 *       }
		 *     }
		 */
		LabelResponse: {
			label: components["schemas"]["Label"];
		};
		/**
		 * @example {
		 *       "email": "user@example.com",
		 *       "password": "correct-horse-battery-staple"
		 *     }
		 */
		LoginUserRequest: {
			/** @description Email address used to sign in. It is normalized before lookup. */
			email: components["schemas"]["email"];
			/**
			 * Format: password
			 * @description Plain-text password to verify. It is never returned by the API.
			 */
			password: string;
		};
		/**
		 * @example {
		 *       "packetCount": 4,
		 *       "packetSizeBytes": 56,
		 *       "timeoutMs": 3000,
		 *       "ipFamily": "inet"
		 *     }
		 */
		PingConfig: {
			/** Format: int32 */
			packetCount: number;
			/** Format: int32 */
			packetSizeBytes: number;
			/** Format: int32 */
			timeoutMs: number;
			/** @enum {string} */
			ipFamily?: "inet" | "inet6";
		};
		/**
		 * @example {
		 *       "packetCount": 4,
		 *       "packetSizeBytes": 56,
		 *       "timeoutMs": 3000,
		 *       "ipFamily": "inet"
		 *     }
		 */
		PingConfigPatch: {
			/** Format: int32 */
			packetCount?: number;
			/** Format: int32 */
			packetSizeBytes?: number;
			/** Format: int32 */
			timeoutMs?: number;
			/** @enum {string} */
			ipFamily?: "inet" | "inet6";
		};
		/**
		 * @example {
		 *       "startedAt": "2026-05-13T10:00:00Z",
		 *       "finishedAt": "2026-05-13T10:00:01Z",
		 *       "durationMs": 1000,
		 *       "status": "successful",
		 *       "sentCount": 4,
		 *       "receivedCount": 4,
		 *       "lossPercent": 0,
		 *       "rttMinMs": 10.1,
		 *       "rttAvgMs": 12.3,
		 *       "rttMedianMs": 12,
		 *       "rttMaxMs": 15.6,
		 *       "rttStddevMs": 1.7,
		 *       "rttSamplesMs": [
		 *         10.1,
		 *         12,
		 *         11.5,
		 *         15.6
		 *       ],
		 *       "resolvedIp": "1.1.1.1",
		 *       "ipFamily": "inet"
		 *     }
		 */
		PingResult: {
			/** Format: date-time */
			startedAt: string;
			/** Format: date-time */
			finishedAt: string;
			/** Format: int32 */
			durationMs: number;
			/** @enum {string} */
			status: "successful" | "timeout" | "error";
			/** Format: int32 */
			sentCount: number;
			/** Format: int32 */
			receivedCount: number;
			/** Format: double */
			lossPercent: number;
			/** Format: double */
			rttMinMs?: number;
			/** Format: double */
			rttAvgMs?: number;
			/** Format: double */
			rttMedianMs?: number;
			/** Format: double */
			rttMaxMs?: number;
			/** Format: double */
			rttStddevMs?: number;
			rttSamplesMs?: number[];
			resolvedIp?: components["schemas"]["ipAddress"];
			/** @enum {string} */
			ipFamily?: "inet" | "inet6";
			errorCode?: string;
			errorMessage?: string;
		};
		/**
		 * @example {
		 *       "from": 1778662800000,
		 *       "to": 1778749200000,
		 *       "maxDataPoints": 600,
		 *       "resolution": "bucket",
		 *       "totalPoints": 487
		 *     }
		 */
		PingSeriesQueryMetadata: {
			/** Format: int64 */
			from: number;
			/** Format: int64 */
			to: number;
			/** Format: int32 */
			maxDataPoints: number;
			resolution: string;
			/** Format: int64 */
			totalPoints: number;
		};
		/**
		 * @example {
		 *       "series": [
		 *         {
		 *           "name": "rttAvgMs",
		 *           "labels": {
		 *             "probeId": "33333333-3333-3333-3333-333333333333",
		 *             "checkId": "44444444-4444-4444-4444-444444444444",
		 *             "checkType": "ping"
		 *           },
		 *           "unit": "ms",
		 *           "points": [
		 *             [
		 *               1778666400000,
		 *               12.3
		 *             ]
		 *           ]
		 *         }
		 *       ],
		 *       "query": {
		 *         "from": 1778662800000,
		 *         "to": 1778749200000,
		 *         "maxDataPoints": 600,
		 *         "resolution": "bucket",
		 *         "totalPoints": 487
		 *       }
		 *     }
		 */
		PingSeriesResponse: {
			series: components["schemas"]["Series"][];
			query: components["schemas"]["PingSeriesQueryMetadata"];
		};
		/**
		 * @example {
		 *       "id": "33333333-3333-3333-3333-333333333333",
		 *       "projectId": "22222222-2222-2222-2222-222222222222",
		 *       "name": "tokyo-vps-1",
		 *       "enabled": true,
		 *       "subdivisionCode": "JP-13",
		 *       "latitude": 35.6762,
		 *       "longitude": 139.6503,
		 *       "labels": [],
		 *       "status": {
		 *         "probeId": "33333333-3333-3333-3333-333333333333",
		 *         "state": "online",
		 *         "lastSeenAt": "2026-05-13T10:00:00Z",
		 *         "updatedAt": "2026-05-13T10:00:00Z"
		 *       },
		 *       "createdAt": "2026-05-13T10:00:00Z",
		 *       "updatedAt": "2026-05-13T10:00:00Z"
		 *     }
		 */
		Probe: {
			id: components["schemas"]["uuid"];
			projectId: components["schemas"]["uuid"];
			name: string;
			enabled: boolean;
			subdivisionCode?: string;
			/** Format: double */
			latitude?: number;
			/** Format: double */
			longitude?: number;
			labels: components["schemas"]["Label"][];
			status?: components["schemas"]["ProbeStatus"];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		/**
		 * @example {
		 *       "probes": [
		 *         {
		 *           "id": "33333333-3333-3333-3333-333333333333",
		 *           "projectId": "22222222-2222-2222-2222-222222222222",
		 *           "name": "tokyo-vps-1",
		 *           "enabled": true,
		 *           "labels": [],
		 *           "createdAt": "2026-05-13T10:00:00Z",
		 *           "updatedAt": "2026-05-13T10:00:00Z"
		 *         }
		 *       ]
		 *     }
		 */
		ProbeListResponse: {
			probes: components["schemas"]["Probe"][];
		};
		/**
		 * @example {
		 *       "probe": {
		 *         "id": "33333333-3333-3333-3333-333333333333",
		 *         "projectId": "22222222-2222-2222-2222-222222222222",
		 *         "name": "tokyo-vps-1",
		 *         "enabled": true,
		 *         "subdivisionCode": "JP-13",
		 *         "latitude": 35.6762,
		 *         "longitude": 139.6503,
		 *         "labels": [],
		 *         "createdAt": "2026-05-13T10:00:00Z",
		 *         "updatedAt": "2026-05-13T10:00:00Z"
		 *       }
		 *     }
		 */
		ProbeResponse: {
			probe: components["schemas"]["Probe"];
		};
		/**
		 * @example {
		 *       "probe": {
		 *         "id": "33333333-3333-3333-3333-333333333333",
		 *         "projectId": "22222222-2222-2222-2222-222222222222",
		 *         "name": "tokyo-vps-1",
		 *         "enabled": true,
		 *         "labels": [],
		 *         "createdAt": "2026-05-13T10:00:00Z",
		 *         "updatedAt": "2026-05-13T10:00:00Z"
		 *       },
		 *       "secret": "nsp_6b5fbd35d3a1417f9c0c8c2e"
		 *     }
		 */
		ProbeSecretResponse: {
			probe: components["schemas"]["Probe"];
			/**
			 * Format: password
			 * @description Plaintext probe secret. It is returned only at creation and rotation time.
			 */
			secret: string;
		};
		/**
		 * @example {
		 *       "probeId": "33333333-3333-3333-3333-333333333333",
		 *       "state": "online",
		 *       "lastSeenAt": "2026-05-13T10:00:00Z",
		 *       "agentVersion": "netstamp-probe/0.1.0",
		 *       "publicV4": "203.0.113.10",
		 *       "publicV6": "2001:db8::10",
		 *       "as": "AS15169 Google LLC",
		 *       "addrs": [
		 *         "10.0.0.10"
		 *       ],
		 *       "updatedAt": "2026-05-13T10:00:00Z"
		 *     }
		 */
		ProbeStatus: {
			probeId: components["schemas"]["uuid"];
			/** @enum {string} */
			state: "online" | "offline";
			/** Format: date-time */
			lastSeenAt?: string;
			agentVersion?: string;
			publicV4?: components["schemas"]["ipAddress"];
			publicV6?: components["schemas"]["ipAddress"];
			as?: string;
			addrs?: components["schemas"]["ipAddress"][];
			/** Format: date-time */
			updatedAt: string;
		};
		/**
		 * @example {
		 *       "title": "Unprocessable Entity",
		 *       "status": 422,
		 *       "detail": "invalid project input",
		 *       "errors": [
		 *         {
		 *           "message": "must be at least 1 character",
		 *           "location": "body.name",
		 *           "value": ""
		 *         }
		 *       ]
		 *     }
		 */
		ProblemDetails: {
			/**
			 * Format: uri
			 * @default about:blank
			 */
			type: string;
			title?: string;
			/** Format: int32 */
			status?: number;
			detail?: string;
			/** Format: uri */
			instance?: string;
			errors?: components["schemas"]["ProblemErrorDetail"][];
		};
		/**
		 * @example {
		 *       "message": "expected required property name to be present",
		 *       "location": "body.name",
		 *       "value": ""
		 *     }
		 */
		ProblemErrorDetail: {
			/** @description Human-readable explanation for this field or sub-error. */
			message?: string;
			/** @description Path-like location such as body.name, query.probeId, or path.ref. */
			location?: string;
			/** @description Echoed invalid value, when the server chooses to return it. */
			value?: unknown;
		};
		/**
		 * @example {
		 *       "id": "22222222-2222-2222-2222-222222222222",
		 *       "name": "Engineering",
		 *       "slug": "engineering",
		 *       "createdByUserId": "11111111-1111-1111-1111-111111111111",
		 *       "createdAt": "2026-05-13T10:00:00Z",
		 *       "updatedAt": "2026-05-13T10:00:00Z"
		 *     }
		 */
		Project: {
			id: components["schemas"]["uuid"];
			name: string;
			slug: string;
			createdByUserId: components["schemas"]["uuid"];
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		/**
		 * @example {
		 *       "projects": [
		 *         {
		 *           "id": "22222222-2222-2222-2222-222222222222",
		 *           "name": "Engineering",
		 *           "slug": "engineering",
		 *           "createdByUserId": "11111111-1111-1111-1111-111111111111",
		 *           "createdAt": "2026-05-13T10:00:00Z",
		 *           "updatedAt": "2026-05-13T10:00:00Z"
		 *         }
		 *       ]
		 *     }
		 */
		ProjectListResponse: {
			projects: components["schemas"]["Project"][];
		};
		/**
		 * @example {
		 *       "id": "55555555-5555-5555-5555-555555555555",
		 *       "projectId": "22222222-2222-2222-2222-222222222222",
		 *       "userId": "11111111-1111-1111-1111-111111111111",
		 *       "role": "owner",
		 *       "createdAt": "2026-05-13T10:00:00Z",
		 *       "updatedAt": "2026-05-13T10:00:00Z"
		 *     }
		 */
		ProjectMember: {
			id: components["schemas"]["uuid"];
			projectId: components["schemas"]["uuid"];
			userId: components["schemas"]["uuid"];
			/** @enum {string} */
			role: "owner" | "admin" | "editor" | "viewer";
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		/**
		 * @example {
		 *       "members": [
		 *         {
		 *           "id": "55555555-5555-5555-5555-555555555555",
		 *           "projectId": "22222222-2222-2222-2222-222222222222",
		 *           "userId": "11111111-1111-1111-1111-111111111111",
		 *           "role": "owner",
		 *           "createdAt": "2026-05-13T10:00:00Z",
		 *           "updatedAt": "2026-05-13T10:00:00Z"
		 *         }
		 *       ]
		 *     }
		 */
		ProjectMemberListResponse: {
			members: components["schemas"]["ProjectMember"][];
		};
		/**
		 * @example {
		 *       "member": {
		 *         "id": "55555555-5555-5555-5555-555555555555",
		 *         "projectId": "22222222-2222-2222-2222-222222222222",
		 *         "userId": "11111111-1111-1111-1111-111111111111",
		 *         "role": "owner",
		 *         "createdAt": "2026-05-13T10:00:00Z",
		 *         "updatedAt": "2026-05-13T10:00:00Z"
		 *       }
		 *     }
		 */
		ProjectMemberResponse: {
			member: components["schemas"]["ProjectMember"];
		};
		/**
		 * @example {
		 *       "project": {
		 *         "id": "22222222-2222-2222-2222-222222222222",
		 *         "name": "Engineering",
		 *         "slug": "engineering",
		 *         "createdByUserId": "11111111-1111-1111-1111-111111111111",
		 *         "createdAt": "2026-05-13T10:00:00Z",
		 *         "updatedAt": "2026-05-13T10:00:00Z"
		 *       }
		 *     }
		 */
		ProjectResponse: {
			project: components["schemas"]["Project"];
		};
		/**
		 * @example {
		 *       "email": "user@example.com",
		 *       "displayName": "Jane Doe",
		 *       "password": "correct-horse-battery-staple"
		 *     }
		 */
		RegisterUserRequest: {
			/** @description Email address used to sign in. */
			email: components["schemas"]["email"];
			/** @description Name shown in the app. */
			displayName: string;
			/**
			 * Format: password
			 * @description Plain-text password. It is stored only as an Argon2id hash.
			 */
			password: string;
		};
		/**
		 * @example {
		 *       "serverTime": "2026-05-13T10:00:00Z",
		 *       "config": {
		 *         "heartbeatIntervalSeconds": 30,
		 *         "assignmentPollIntervalSeconds": 30,
		 *         "maxConcurrentWorkers": 16,
		 *         "initialBackoffSeconds": 1,
		 *         "maxBackoffSeconds": 30,
		 *         "maxAttempts": 5
		 *       },
		 *       "assignments": []
		 *     }
		 */
		RuntimeAssignmentsResponse: {
			/** Format: date-time */
			serverTime: string;
			config: components["schemas"]["RuntimeConfig"];
			assignments: components["schemas"]["Assignment"][];
		};
		/**
		 * @example {
		 *       "heartbeatIntervalSeconds": 30,
		 *       "assignmentPollIntervalSeconds": 30,
		 *       "maxConcurrentWorkers": 16,
		 *       "initialBackoffSeconds": 1,
		 *       "maxBackoffSeconds": 30,
		 *       "maxAttempts": 5
		 *     }
		 */
		RuntimeConfig: {
			/** Format: int32 */
			heartbeatIntervalSeconds: number;
			/** Format: int32 */
			assignmentPollIntervalSeconds: number;
			/** Format: int32 */
			maxConcurrentWorkers: number;
			/** Format: int32 */
			initialBackoffSeconds: number;
			/** Format: int32 */
			maxBackoffSeconds: number;
			/** Format: int32 */
			maxAttempts: number;
		};
		/**
		 * @example {
		 *       "serverTime": "2026-05-13T10:00:00Z"
		 *     }
		 */
		RuntimeHeartbeatResponse: {
			/** Format: date-time */
			serverTime: string;
		};
		/**
		 * @example {
		 *       "serverTime": "2026-05-13T10:00:00Z",
		 *       "minimumSupportedAgentVersion": "0.1.0",
		 *       "config": {
		 *         "heartbeatIntervalSeconds": 30,
		 *         "assignmentPollIntervalSeconds": 30,
		 *         "maxConcurrentWorkers": 16,
		 *         "initialBackoffSeconds": 1,
		 *         "maxBackoffSeconds": 30,
		 *         "maxAttempts": 5
		 *       }
		 *     }
		 */
		RuntimeHelloResponse: {
			/** Format: date-time */
			serverTime: string;
			minimumSupportedAgentVersion: string;
			config: components["schemas"]["RuntimeConfig"];
		};
		/**
		 * @example {
		 *       "checkId": "44444444-4444-4444-4444-444444444444",
		 *       "type": "ping",
		 *       "ping": [
		 *         {
		 *           "startedAt": "2026-05-13T10:00:00Z",
		 *           "finishedAt": "2026-05-13T10:00:01Z",
		 *           "durationMs": 1000,
		 *           "status": "successful",
		 *           "sentCount": 4,
		 *           "receivedCount": 4,
		 *           "lossPercent": 0,
		 *           "rttAvgMs": 12.3,
		 *           "rttSamplesMs": [
		 *             10.1,
		 *             12,
		 *             11.5,
		 *             15.6
		 *           ],
		 *           "resolvedIp": "1.1.1.1",
		 *           "ipFamily": "inet"
		 *         }
		 *       ]
		 *     }
		 */
		RuntimeResultGroup: {
			checkId: components["schemas"]["uuid"];
			/** @enum {string} */
			type: "ping" | "traceroute";
			ping?: components["schemas"]["PingResult"][];
			traceroute?: components["schemas"]["TracerouteResult"][];
		};
		/**
		 * @example {
		 *       "agentVersion": "netstamp-probe/0.1.0",
		 *       "publicV4": "203.0.113.10",
		 *       "publicV6": "2001:db8::10",
		 *       "as": "AS15169 Google LLC",
		 *       "addrs": [
		 *         "10.0.0.10"
		 *       ]
		 *     }
		 */
		RuntimeStatusRequest: {
			agentVersion?: string;
			publicV4?: components["schemas"]["ipAddress"];
			publicV6?: components["schemas"]["ipAddress"];
			as?: string;
			addrs?: components["schemas"]["ipAddress"][];
		};
		/**
		 * @example {
		 *       "name": "rttAvgMs",
		 *       "labels": {
		 *         "probeId": "33333333-3333-3333-3333-333333333333",
		 *         "checkId": "44444444-4444-4444-4444-444444444444",
		 *         "checkType": "ping"
		 *       },
		 *       "unit": "ms",
		 *       "points": [
		 *         [
		 *           1778666400000,
		 *           12.3
		 *         ]
		 *       ]
		 *     }
		 */
		Series: {
			name: string;
			labels: Record<string, never>;
			unit: string;
			points: [number, number][];
		};
		/**
		 * @example {
		 *       "results": [
		 *         {
		 *           "checkId": "44444444-4444-4444-4444-444444444444",
		 *           "type": "ping",
		 *           "ping": [
		 *             {
		 *               "startedAt": "2026-05-13T10:00:00Z",
		 *               "finishedAt": "2026-05-13T10:00:01Z",
		 *               "durationMs": 1000,
		 *               "status": "successful",
		 *               "sentCount": 4,
		 *               "receivedCount": 4,
		 *               "lossPercent": 0
		 *             }
		 *           ]
		 *         }
		 *       ]
		 *     }
		 */
		SubmitResultsRequest: {
			results: components["schemas"]["RuntimeResultGroup"][];
		};
		/**
		 * @example {
		 *       "accepted": 1,
		 *       "serverTime": "2026-05-13T10:00:02Z"
		 *     }
		 */
		SubmitResultsResponse: {
			/** Format: int32 */
			accepted: number;
			/** Format: date-time */
			serverTime: string;
		};
		/**
		 * @example {
		 *       "protocol": "icmp",
		 *       "maxHops": 30,
		 *       "timeoutMs": 3000,
		 *       "queriesPerHop": 3,
		 *       "packetSizeBytes": 56,
		 *       "port": 33434,
		 *       "ipFamily": "inet"
		 *     }
		 */
		TracerouteConfig: {
			/** @enum {string} */
			protocol: "icmp" | "udp";
			/** Format: int32 */
			maxHops: number;
			/** Format: int32 */
			timeoutMs: number;
			/** Format: int32 */
			queriesPerHop: number;
			/** Format: int32 */
			packetSizeBytes: number;
			/** Format: int32 */
			port: number;
			/** @enum {string} */
			ipFamily?: "inet" | "inet6";
		};
		/**
		 * @example {
		 *       "protocol": "icmp",
		 *       "maxHops": 30,
		 *       "timeoutMs": 3000,
		 *       "queriesPerHop": 3,
		 *       "packetSizeBytes": 56,
		 *       "port": 33434,
		 *       "ipFamily": "inet"
		 *     }
		 */
		TracerouteConfigPatch: {
			/** @enum {string} */
			protocol?: "icmp" | "udp";
			/** Format: int32 */
			maxHops?: number;
			/** Format: int32 */
			timeoutMs?: number;
			/** Format: int32 */
			queriesPerHop?: number;
			/** Format: int32 */
			packetSizeBytes?: number;
			/** Format: int32 */
			port?: number;
			/** @enum {string} */
			ipFamily?: "inet" | "inet6";
		};
		/**
		 * @example {
		 *       "hopIndex": 1,
		 *       "address": "192.0.2.1",
		 *       "hostname": "gateway.local",
		 *       "sentCount": 3,
		 *       "receivedCount": 3,
		 *       "lossPercent": 0,
		 *       "rttMinMs": 1.5,
		 *       "rttAvgMs": 1.7,
		 *       "rttMedianMs": 1.7,
		 *       "rttMaxMs": 1.9,
		 *       "rttStddevMs": 0.2,
		 *       "rttSamplesMs": [
		 *         1.5,
		 *         1.7,
		 *         1.9
		 *       ]
		 *     }
		 */
		TracerouteHop: {
			/** Format: int32 */
			hopIndex: number;
			address?: components["schemas"]["ipAddress"];
			hostname?: string;
			/** Format: int32 */
			sentCount: number;
			/** Format: int32 */
			receivedCount: number;
			/** Format: double */
			lossPercent: number;
			/** Format: double */
			rttMinMs?: number;
			/** Format: double */
			rttAvgMs?: number;
			/** Format: double */
			rttMedianMs?: number;
			/** Format: double */
			rttMaxMs?: number;
			/** Format: double */
			rttStddevMs?: number;
			rttSamplesMs?: number[];
			errorCode?: string;
			errorMessage?: string;
		};
		/**
		 * @example {
		 *       "startedAt": "2026-05-13T10:00:00Z",
		 *       "finishedAt": "2026-05-13T10:00:04Z",
		 *       "durationMs": 4000,
		 *       "status": "partial",
		 *       "resolvedIp": "93.184.216.34",
		 *       "ipFamily": "inet",
		 *       "destinationReached": false,
		 *       "hopCount": 12,
		 *       "hops": [
		 *         {
		 *           "hopIndex": 1,
		 *           "address": "192.0.2.1",
		 *           "sentCount": 3,
		 *           "receivedCount": 3,
		 *           "lossPercent": 0
		 *         }
		 *       ],
		 *       "errorCode": "destination_unreached",
		 *       "errorMessage": "destination was not reached before max hops"
		 *     }
		 */
		TracerouteResult: {
			/** Format: date-time */
			startedAt: string;
			/** Format: date-time */
			finishedAt: string;
			/** Format: int32 */
			durationMs: number;
			/** @enum {string} */
			status: "successful" | "timeout" | "error" | "partial";
			resolvedIp?: components["schemas"]["ipAddress"];
			/** @enum {string} */
			ipFamily?: "inet" | "inet6";
			destinationReached: boolean;
			/** Format: int32 */
			hopCount: number;
			hops?: components["schemas"]["TracerouteHop"][];
			errorCode?: string;
			errorMessage?: string;
		};
		/**
		 * @example {
		 *       "from": 1778662800000,
		 *       "to": 1778749200000,
		 *       "limit": 100,
		 *       "nextCursor": 1778666400000
		 *     }
		 */
		TracerouteRunsQueryMetadata: {
			/** Format: int64 */
			from: number;
			/** Format: int64 */
			to: number;
			/** Format: int32 */
			limit: number;
			/** Format: int64 */
			nextCursor?: number;
		};
		/**
		 * @example {
		 *       "runs": [
		 *         {
		 *           "startedAt": "2026-05-13T10:00:00Z",
		 *           "finishedAt": "2026-05-13T10:00:04Z",
		 *           "durationMs": 4000,
		 *           "status": "partial",
		 *           "destinationReached": false,
		 *           "hopCount": 12,
		 *           "hops": [
		 *             {
		 *               "hopIndex": 1,
		 *               "sentCount": 3,
		 *               "receivedCount": 3,
		 *               "lossPercent": 0
		 *             }
		 *           ]
		 *         }
		 *       ],
		 *       "query": {
		 *         "from": 1778662800000,
		 *         "to": 1778749200000,
		 *         "limit": 100
		 *       }
		 *     }
		 */
		TracerouteRunsResponse: {
			runs: components["schemas"]["TracerouteResult"][];
			query: components["schemas"]["TracerouteRunsQueryMetadata"];
		};
		/**
		 * @example {
		 *       "name": "api-latency",
		 *       "target": "api.netstamp.io",
		 *       "intervalSeconds": 60,
		 *       "labelIds": [
		 *         "66666666-6666-6666-6666-666666666666"
		 *       ],
		 *       "pingConfig": {
		 *         "timeoutMs": 5000
		 *       }
		 *     }
		 */
		UpdateCheckRequest: {
			name?: string;
			/** @enum {string} */
			type?: "ping" | "traceroute";
			target?: string;
			selector?: Record<string, never>;
			description?: string;
			/** Format: int32 */
			intervalSeconds?: number;
			pingConfig?: components["schemas"]["PingConfigPatch"];
			tracerouteConfig?: components["schemas"]["TracerouteConfigPatch"];
			labelIds?: components["schemas"]["uuid"][];
		};
		/**
		 * @example {
		 *       "key": "metro",
		 *       "value": "tokyo"
		 *     }
		 */
		UpdateLabelRequest: {
			key?: string;
			value?: string;
		};
		/**
		 * @example {
		 *       "name": "tokyo-vps-2",
		 *       "enabled": false,
		 *       "labelIds": [
		 *         "66666666-6666-6666-6666-666666666666"
		 *       ]
		 *     }
		 */
		UpdateProbeRequest: {
			name?: string;
			enabled?: boolean;
			subdivisionCode?: string;
			/** Format: double */
			latitude?: number;
			/** Format: double */
			longitude?: number;
			labelIds?: components["schemas"]["uuid"][];
		};
		/**
		 * @example {
		 *       "role": "editor"
		 *     }
		 */
		UpdateProjectMemberRoleRequest: {
			/** @enum {string} */
			role: "admin" | "editor" | "viewer";
		};
		/**
		 * @example {
		 *       "name": "Platform Engineering",
		 *       "slug": "platform-engineering"
		 *     }
		 */
		UpdateProjectRequest: {
			name?: string;
			slug?: string;
		};
		/**
		 * @example {
		 *       "id": "11111111-1111-1111-1111-111111111111",
		 *       "email": "user@example.com",
		 *       "displayName": "Jane Doe"
		 *     }
		 */
		User: {
			/** @description User UUID. */
			id: components["schemas"]["uuid"];
			/** @description Normalized email address used to sign in. */
			email: components["schemas"]["email"];
			/** @description Name shown in the app. */
			displayName: string;
		};
		/** Format: email */
		email: string;
		ipAddress: string;
		/** Format: uuid */
		uuid: string;
	};
	responses: never;
	parameters: {
		CheckIdPathParam: components["schemas"]["uuid"];
		LabelIdPathParam: components["schemas"]["uuid"];
		"PingSeriesQuery.checkId": components["schemas"]["uuid"];
		"PingSeriesQuery.from": number;
		"PingSeriesQuery.maxDataPoints": number;
		"PingSeriesQuery.metric": "rttAvgMs" | "lossPercent" | "successRate";
		"PingSeriesQuery.probeId": components["schemas"]["uuid"];
		"PingSeriesQuery.to": number;
		ProbeIdPathParam: components["schemas"]["uuid"];
		ProjectRefParam: string;
		"TracerouteRunsQuery.checkId": components["schemas"]["uuid"];
		"TracerouteRunsQuery.cursor": number;
		"TracerouteRunsQuery.from": number;
		"TracerouteRunsQuery.limit": number;
		"TracerouteRunsQuery.probeId": components["schemas"]["uuid"];
		"TracerouteRunsQuery.to": number;
		UserIdPathParam: components["schemas"]["uuid"];
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	getAPIStatus: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["APIStatusResponse"];
				};
			};
		};
	};
	loginUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["LoginUserRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					"Set-Cookie": string;
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthUserResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	logoutUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					"Set-Cookie": string;
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getCurrentUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CurrentUserResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	registerUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RegisterUserRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					"Set-Cookie": string;
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["AuthUserResponse"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getHealth: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HealthResponse"];
				};
			};
			/** @description Service unavailable. */
			503: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listProjects: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectListResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	createProject: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateProjectRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	deleteProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateProject: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateProjectRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listProjectChecks: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CheckListResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	createProjectCheck: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateCheckRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CheckResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getProjectCheck: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				check_id: components["parameters"]["CheckIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CheckResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	deleteProjectCheck: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				check_id: components["parameters"]["CheckIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateProjectCheck: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				check_id: components["parameters"]["CheckIdPathParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateCheckRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CheckResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listProjectLabels: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LabelListResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	createProjectLabel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateLabelRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LabelResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	deleteProjectLabel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				label_id: components["parameters"]["LabelIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateProjectLabel: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				label_id: components["parameters"]["LabelIdPathParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateLabelRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["LabelResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listProjectMembers: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectMemberListResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	addProjectMember: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["AddProjectMemberRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectMemberResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	removeProjectMember: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				user_id: components["parameters"]["UserIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateProjectMemberRole: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				user_id: components["parameters"]["UserIdPathParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateProjectMemberRoleRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProjectMemberResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The request conflicts with the current state of the server. */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listProjectProbes: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProbeListResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	createProjectProbe: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateProbeRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded and a new resource has been created as a result. */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProbeSecretResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	getProjectProbe: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				probe_id: components["parameters"]["ProbeIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProbeResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	deleteProjectProbe: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				probe_id: components["parameters"]["ProbeIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description There is no content to send for this request, but the headers may be useful. */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	updateProjectProbe: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				probe_id: components["parameters"]["ProbeIdPathParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateProbeRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProbeResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	rotateProjectProbeSecret: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
				probe_id: components["parameters"]["ProbeIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProbeSecretResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	queryProjectPingResultSeries: {
		parameters: {
			query: {
				probeId: components["parameters"]["PingSeriesQuery.probeId"];
				checkId: components["parameters"]["PingSeriesQuery.checkId"];
				from?: components["parameters"]["PingSeriesQuery.from"];
				to?: components["parameters"]["PingSeriesQuery.to"];
				metric: components["parameters"]["PingSeriesQuery.metric"];
				maxDataPoints?: components["parameters"]["PingSeriesQuery.maxDataPoints"];
			};
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PingSeriesResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	queryProjectTracerouteResultRuns: {
		parameters: {
			query: {
				probeId: components["parameters"]["TracerouteRunsQuery.probeId"];
				checkId: components["parameters"]["TracerouteRunsQuery.checkId"];
				from?: components["parameters"]["TracerouteRunsQuery.from"];
				to?: components["parameters"]["TracerouteRunsQuery.to"];
				limit?: components["parameters"]["TracerouteRunsQuery.limit"];
				cursor?: components["parameters"]["TracerouteRunsQuery.cursor"];
			};
			header?: never;
			path: {
				ref: components["parameters"]["ProjectRefParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["TracerouteRunsResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	listProbeRuntimeAssignments: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				probe_id: components["parameters"]["ProbeIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RuntimeAssignmentsResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	probeRuntimeHeartbeat: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				probe_id: components["parameters"]["ProbeIdPathParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["RuntimeStatusRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RuntimeHeartbeatResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	probeRuntimeHello: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				probe_id: components["parameters"]["ProbeIdPathParam"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RuntimeHelloResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	submitProbeRuntimeResults: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				probe_id: components["parameters"]["ProbeIdPathParam"];
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SubmitResultsRequest"];
			};
		};
		responses: {
			/** @description The request has succeeded. */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SubmitResultsResponse"];
				};
			};
			/** @description Access is unauthorized. */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Access is forbidden. */
			403: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description The server cannot find the requested resource. */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Client error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Server error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
}
