import type { components } from "./openapi";

export type AddMemberInput = components["schemas"]["AddProjectMemberRequest"];
export type ApiCheck = components["schemas"]["Check"];
export type ApiLabel = components["schemas"]["Label"];
export type ApiMember = components["schemas"]["ProjectMember"];
export type ApiProbe = components["schemas"]["Probe"];
export type ApiProject = components["schemas"]["Project"];
export type CreateCheckInput = components["schemas"]["CreateCheckRequest"];
export type CreateLabelInput = components["schemas"]["CreateLabelRequest"];
export type CreateProbeInput = components["schemas"]["CreateProbeRequest"];
export type CreateProjectInput = components["schemas"]["CreateProjectRequest"];
export type LoginInput = components["schemas"]["LoginUserRequest"];
export type ProjectMemberRole = NonNullable<components["schemas"]["UpdateProjectMemberRoleRequest"]["role"]>;
export type RegisterInput = components["schemas"]["RegisterUserRequest"];
export type UpdateCheckInput = components["schemas"]["UpdateCheckRequest"];
export type UpdateLabelInput = components["schemas"]["UpdateLabelRequest"];
export type UpdateProbeInput = components["schemas"]["UpdateProbeRequest"];
export type UpdateProjectInput = components["schemas"]["UpdateProjectRequest"];
export type UserResponse = components["schemas"]["User"];
